/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseAbandonEvaluationInstruction,
  parseAcceptOfferInstruction,
  parseClaimSettlementInstruction,
  parseClaimStagePassInstruction,
  parseCloseRequestInstruction,
  parseCreateSolfxAccountInstruction,
  parseDeclineOfferInstruction,
  parseEvalClosePositionInstruction,
  parseEvalObserveEquityInstruction,
  parseEvalOpenPositionInstruction,
  parseEvalTriggerStopInstruction,
  parseForfeitStakeInstruction,
  parseFundedCancelStopInstruction,
  parseFundedClosePositionInstruction,
  parseFundedOpenPositionInstruction,
  parseFundedPlaceTakeProfitInstruction,
  parseFundMandateInstruction,
  parseFundSolfxCollateralInstruction,
  parseInitializeConfigInstruction,
  parseInitializeTraderProfileInstruction,
  parseObserveMandateEquityInstruction,
  parsePostInvestorListingInstruction,
  parsePostListingInstruction,
  parsePostOfferInstruction,
  parsePostRequestInstruction,
  parseRecomputeTierInstruction,
  parseReconcilePositionInstruction,
  parseRequestSettlementInstruction,
  parseRevokeOfferInstruction,
  parseSetPausedInstruction,
  parseStartEvaluationInstruction,
  parseUpdateInvestorListingInstruction,
  parseUpdateListingInstruction,
  parseWindDownCancelStopInstruction,
  parseWindDownPositionInstruction,
  type ParsedAbandonEvaluationInstruction,
  type ParsedAcceptOfferInstruction,
  type ParsedClaimSettlementInstruction,
  type ParsedClaimStagePassInstruction,
  type ParsedCloseRequestInstruction,
  type ParsedCreateSolfxAccountInstruction,
  type ParsedDeclineOfferInstruction,
  type ParsedEvalClosePositionInstruction,
  type ParsedEvalObserveEquityInstruction,
  type ParsedEvalOpenPositionInstruction,
  type ParsedEvalTriggerStopInstruction,
  type ParsedForfeitStakeInstruction,
  type ParsedFundedCancelStopInstruction,
  type ParsedFundedClosePositionInstruction,
  type ParsedFundedOpenPositionInstruction,
  type ParsedFundedPlaceTakeProfitInstruction,
  type ParsedFundMandateInstruction,
  type ParsedFundSolfxCollateralInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedInitializeTraderProfileInstruction,
  type ParsedObserveMandateEquityInstruction,
  type ParsedPostInvestorListingInstruction,
  type ParsedPostListingInstruction,
  type ParsedPostOfferInstruction,
  type ParsedPostRequestInstruction,
  type ParsedRecomputeTierInstruction,
  type ParsedReconcilePositionInstruction,
  type ParsedRequestSettlementInstruction,
  type ParsedRevokeOfferInstruction,
  type ParsedSetPausedInstruction,
  type ParsedStartEvaluationInstruction,
  type ParsedUpdateInvestorListingInstruction,
  type ParsedUpdateListingInstruction,
  type ParsedWindDownCancelStopInstruction,
  type ParsedWindDownPositionInstruction,
} from "../instructions";

export const NOXFUNDS_PROGRAM_ADDRESS =
  "9B7qLbLk9PdRfiMEEK9Jzeen1nG8xzA7YvXsELS1DPUx" as Address<"9B7qLbLk9PdRfiMEEK9Jzeen1nG8xzA7YvXsELS1DPUx">;

export enum NoxfundsAccount {
  Evaluation,
  FundingRequest,
  InvestorListing,
  Mandate,
  MandateOffer,
  NoxConfig,
  TraderListing,
  TraderProfile,
  VirtualPosition,
}

export function identifyNoxfundsAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): NoxfundsAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([212, 70, 25, 106, 239, 24, 93, 220]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.Evaluation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([78, 109, 168, 114, 238, 219, 124, 44]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.FundingRequest;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([157, 178, 167, 218, 163, 179, 227, 121]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.InvestorListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([113, 216, 98, 159, 185, 63, 55, 18]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.Mandate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 239, 145, 190, 228, 246, 19, 141]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.MandateOffer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 160, 106, 28, 4, 223, 249, 200]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.NoxConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([26, 76, 11, 24, 74, 161, 177, 13]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.TraderListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([99, 135, 170, 100, 49, 79, 225, 169]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.TraderProfile;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([197, 31, 155, 182, 114, 82, 179, 126]),
      ),
      0,
    )
  ) {
    return NoxfundsAccount.VirtualPosition;
  }
  throw new Error(
    "The provided account could not be identified as a noxfunds account.",
  );
}

export enum NoxfundsInstruction {
  AbandonEvaluation,
  AcceptOffer,
  ClaimSettlement,
  ClaimStagePass,
  CloseRequest,
  CreateSolfxAccount,
  DeclineOffer,
  EvalClosePosition,
  EvalObserveEquity,
  EvalOpenPosition,
  EvalTriggerStop,
  ForfeitStake,
  FundMandate,
  FundSolfxCollateral,
  FundedCancelStop,
  FundedClosePosition,
  FundedOpenPosition,
  FundedPlaceTakeProfit,
  InitializeConfig,
  InitializeTraderProfile,
  ObserveMandateEquity,
  PostInvestorListing,
  PostListing,
  PostOffer,
  PostRequest,
  RecomputeTier,
  ReconcilePosition,
  RequestSettlement,
  RevokeOffer,
  SetPaused,
  StartEvaluation,
  UpdateInvestorListing,
  UpdateListing,
  WindDownCancelStop,
  WindDownPosition,
}

export function identifyNoxfundsInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): NoxfundsInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 34, 15, 195, 27, 14, 4, 206]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.AbandonEvaluation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([227, 82, 234, 131, 1, 18, 48, 2]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.AcceptOffer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([85, 208, 73, 229, 143, 98, 83, 212]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.ClaimSettlement;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([31, 92, 188, 154, 205, 34, 118, 4]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.ClaimStagePass;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([170, 46, 165, 120, 223, 102, 115, 2]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.CloseRequest;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([82, 18, 172, 49, 89, 98, 47, 142]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.CreateSolfxAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([204, 98, 121, 232, 122, 145, 35, 96]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.DeclineOffer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([40, 137, 84, 57, 105, 46, 100, 9]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.EvalClosePosition;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([71, 249, 117, 82, 47, 216, 124, 7]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.EvalObserveEquity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([44, 175, 249, 12, 240, 36, 239, 100]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.EvalOpenPosition;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([43, 85, 122, 170, 91, 181, 194, 204]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.EvalTriggerStop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 161, 131, 64, 84, 25, 41, 228]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.ForfeitStake;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([233, 15, 136, 238, 108, 122, 197, 29]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundMandate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([29, 23, 27, 204, 167, 94, 187, 211]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundSolfxCollateral;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([134, 246, 181, 255, 164, 74, 78, 238]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundedCancelStop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([227, 179, 83, 193, 193, 251, 156, 231]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundedClosePosition;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([109, 93, 55, 146, 36, 186, 248, 83]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundedOpenPosition;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([195, 75, 243, 152, 49, 23, 236, 177]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.FundedPlaceTakeProfit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.InitializeConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([195, 249, 92, 96, 42, 151, 172, 99]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.InitializeTraderProfile;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([198, 172, 192, 97, 103, 219, 39, 91]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.ObserveMandateEquity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([202, 230, 166, 98, 148, 139, 66, 144]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.PostInvestorListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([98, 60, 128, 203, 78, 140, 201, 202]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.PostListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([73, 150, 193, 114, 200, 133, 74, 58]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.PostOffer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([4, 59, 143, 187, 32, 9, 161, 253]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.PostRequest;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([88, 190, 225, 127, 27, 185, 123, 147]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.RecomputeTier;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([112, 179, 103, 225, 241, 95, 12, 78]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.ReconcilePosition;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 127, 110, 105, 43, 95, 115, 41]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.RequestSettlement;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([248, 93, 83, 25, 45, 66, 150, 134]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.RevokeOffer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([91, 60, 125, 192, 176, 225, 166, 218]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.SetPaused;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 126, 223, 83, 56, 34, 155, 210]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.StartEvaluation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([150, 88, 208, 182, 78, 177, 166, 218]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.UpdateInvestorListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 174, 210, 68, 116, 40, 242, 253]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.UpdateListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([47, 86, 164, 53, 15, 111, 233, 112]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.WindDownCancelStop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([65, 158, 128, 30, 106, 110, 180, 11]),
      ),
      0,
    )
  ) {
    return NoxfundsInstruction.WindDownPosition;
  }
  throw new Error(
    "The provided instruction could not be identified as a noxfunds instruction.",
  );
}

export type ParsedNoxfundsInstruction<
  TProgram extends string = "9B7qLbLk9PdRfiMEEK9Jzeen1nG8xzA7YvXsELS1DPUx",
> =
  | ({
      instructionType: NoxfundsInstruction.AbandonEvaluation;
    } & ParsedAbandonEvaluationInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.AcceptOffer;
    } & ParsedAcceptOfferInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.ClaimSettlement;
    } & ParsedClaimSettlementInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.ClaimStagePass;
    } & ParsedClaimStagePassInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.CloseRequest;
    } & ParsedCloseRequestInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.CreateSolfxAccount;
    } & ParsedCreateSolfxAccountInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.DeclineOffer;
    } & ParsedDeclineOfferInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.EvalClosePosition;
    } & ParsedEvalClosePositionInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.EvalObserveEquity;
    } & ParsedEvalObserveEquityInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.EvalOpenPosition;
    } & ParsedEvalOpenPositionInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.EvalTriggerStop;
    } & ParsedEvalTriggerStopInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.ForfeitStake;
    } & ParsedForfeitStakeInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundMandate;
    } & ParsedFundMandateInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundSolfxCollateral;
    } & ParsedFundSolfxCollateralInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundedCancelStop;
    } & ParsedFundedCancelStopInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundedClosePosition;
    } & ParsedFundedClosePositionInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundedOpenPosition;
    } & ParsedFundedOpenPositionInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.FundedPlaceTakeProfit;
    } & ParsedFundedPlaceTakeProfitInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.InitializeTraderProfile;
    } & ParsedInitializeTraderProfileInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.ObserveMandateEquity;
    } & ParsedObserveMandateEquityInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.PostInvestorListing;
    } & ParsedPostInvestorListingInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.PostListing;
    } & ParsedPostListingInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.PostOffer;
    } & ParsedPostOfferInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.PostRequest;
    } & ParsedPostRequestInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.RecomputeTier;
    } & ParsedRecomputeTierInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.ReconcilePosition;
    } & ParsedReconcilePositionInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.RequestSettlement;
    } & ParsedRequestSettlementInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.RevokeOffer;
    } & ParsedRevokeOfferInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.SetPaused;
    } & ParsedSetPausedInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.StartEvaluation;
    } & ParsedStartEvaluationInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.UpdateInvestorListing;
    } & ParsedUpdateInvestorListingInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.UpdateListing;
    } & ParsedUpdateListingInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.WindDownCancelStop;
    } & ParsedWindDownCancelStopInstruction<TProgram>)
  | ({
      instructionType: NoxfundsInstruction.WindDownPosition;
    } & ParsedWindDownPositionInstruction<TProgram>);

export function parseNoxfundsInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedNoxfundsInstruction<TProgram> {
  const instructionType = identifyNoxfundsInstruction(instruction);
  switch (instructionType) {
    case NoxfundsInstruction.AbandonEvaluation: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.AbandonEvaluation,
        ...parseAbandonEvaluationInstruction(instruction),
      };
    }
    case NoxfundsInstruction.AcceptOffer: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.AcceptOffer,
        ...parseAcceptOfferInstruction(instruction),
      };
    }
    case NoxfundsInstruction.ClaimSettlement: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.ClaimSettlement,
        ...parseClaimSettlementInstruction(instruction),
      };
    }
    case NoxfundsInstruction.ClaimStagePass: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.ClaimStagePass,
        ...parseClaimStagePassInstruction(instruction),
      };
    }
    case NoxfundsInstruction.CloseRequest: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.CloseRequest,
        ...parseCloseRequestInstruction(instruction),
      };
    }
    case NoxfundsInstruction.CreateSolfxAccount: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.CreateSolfxAccount,
        ...parseCreateSolfxAccountInstruction(instruction),
      };
    }
    case NoxfundsInstruction.DeclineOffer: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.DeclineOffer,
        ...parseDeclineOfferInstruction(instruction),
      };
    }
    case NoxfundsInstruction.EvalClosePosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.EvalClosePosition,
        ...parseEvalClosePositionInstruction(instruction),
      };
    }
    case NoxfundsInstruction.EvalObserveEquity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.EvalObserveEquity,
        ...parseEvalObserveEquityInstruction(instruction),
      };
    }
    case NoxfundsInstruction.EvalOpenPosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.EvalOpenPosition,
        ...parseEvalOpenPositionInstruction(instruction),
      };
    }
    case NoxfundsInstruction.EvalTriggerStop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.EvalTriggerStop,
        ...parseEvalTriggerStopInstruction(instruction),
      };
    }
    case NoxfundsInstruction.ForfeitStake: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.ForfeitStake,
        ...parseForfeitStakeInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundMandate: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundMandate,
        ...parseFundMandateInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundSolfxCollateral: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundSolfxCollateral,
        ...parseFundSolfxCollateralInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundedCancelStop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundedCancelStop,
        ...parseFundedCancelStopInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundedClosePosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundedClosePosition,
        ...parseFundedClosePositionInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundedOpenPosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundedOpenPosition,
        ...parseFundedOpenPositionInstruction(instruction),
      };
    }
    case NoxfundsInstruction.FundedPlaceTakeProfit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.FundedPlaceTakeProfit,
        ...parseFundedPlaceTakeProfitInstruction(instruction),
      };
    }
    case NoxfundsInstruction.InitializeConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.InitializeConfig,
        ...parseInitializeConfigInstruction(instruction),
      };
    }
    case NoxfundsInstruction.InitializeTraderProfile: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.InitializeTraderProfile,
        ...parseInitializeTraderProfileInstruction(instruction),
      };
    }
    case NoxfundsInstruction.ObserveMandateEquity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.ObserveMandateEquity,
        ...parseObserveMandateEquityInstruction(instruction),
      };
    }
    case NoxfundsInstruction.PostInvestorListing: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.PostInvestorListing,
        ...parsePostInvestorListingInstruction(instruction),
      };
    }
    case NoxfundsInstruction.PostListing: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.PostListing,
        ...parsePostListingInstruction(instruction),
      };
    }
    case NoxfundsInstruction.PostOffer: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.PostOffer,
        ...parsePostOfferInstruction(instruction),
      };
    }
    case NoxfundsInstruction.PostRequest: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.PostRequest,
        ...parsePostRequestInstruction(instruction),
      };
    }
    case NoxfundsInstruction.RecomputeTier: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.RecomputeTier,
        ...parseRecomputeTierInstruction(instruction),
      };
    }
    case NoxfundsInstruction.ReconcilePosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.ReconcilePosition,
        ...parseReconcilePositionInstruction(instruction),
      };
    }
    case NoxfundsInstruction.RequestSettlement: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.RequestSettlement,
        ...parseRequestSettlementInstruction(instruction),
      };
    }
    case NoxfundsInstruction.RevokeOffer: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.RevokeOffer,
        ...parseRevokeOfferInstruction(instruction),
      };
    }
    case NoxfundsInstruction.SetPaused: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.SetPaused,
        ...parseSetPausedInstruction(instruction),
      };
    }
    case NoxfundsInstruction.StartEvaluation: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.StartEvaluation,
        ...parseStartEvaluationInstruction(instruction),
      };
    }
    case NoxfundsInstruction.UpdateInvestorListing: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.UpdateInvestorListing,
        ...parseUpdateInvestorListingInstruction(instruction),
      };
    }
    case NoxfundsInstruction.UpdateListing: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.UpdateListing,
        ...parseUpdateListingInstruction(instruction),
      };
    }
    case NoxfundsInstruction.WindDownCancelStop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.WindDownCancelStop,
        ...parseWindDownCancelStopInstruction(instruction),
      };
    }
    case NoxfundsInstruction.WindDownPosition: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NoxfundsInstruction.WindDownPosition,
        ...parseWindDownPositionInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
