/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getDirectionDecoder,
  getDirectionEncoder,
  getEntryKindDecoder,
  getEntryKindEncoder,
  type Direction,
  type DirectionArgs,
  type EntryKind,
  type EntryKindArgs,
} from "../types";

export const EVAL_ENTRY_ORDER_DISCRIMINATOR = new Uint8Array([
  7, 195, 135, 196, 209, 156, 33, 246,
]);

export function getEvalEntryOrderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVAL_ENTRY_ORDER_DISCRIMINATOR,
  );
}

export type EvalEntryOrder = {
  discriminator: ReadonlyUint8Array;
  evaluation: Address;
  trader: Address;
  orderId: number;
  marketIndex: number;
  /** The `VirtualPosition` nonce it opens at. Chosen at placement so the address is known. */
  nonce: number;
  direction: Direction;
  kind: EntryKind;
  triggerPrice: bigint;
  sizeBase: bigint;
  stopLossPrice: bigint;
  /** Zero for none. */
  takeProfitPrice: bigint;
  /** Unix time after which it cannot fill and anyone may cancel it. Zero: until cancelled. */
  expiresAt: bigint;
  createdAt: bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export type EvalEntryOrderArgs = {
  evaluation: Address;
  trader: Address;
  orderId: number;
  marketIndex: number;
  /** The `VirtualPosition` nonce it opens at. Chosen at placement so the address is known. */
  nonce: number;
  direction: DirectionArgs;
  kind: EntryKindArgs;
  triggerPrice: number | bigint;
  sizeBase: number | bigint;
  stopLossPrice: number | bigint;
  /** Zero for none. */
  takeProfitPrice: number | bigint;
  /** Unix time after which it cannot fill and anyone may cancel it. Zero: until cancelled. */
  expiresAt: number | bigint;
  createdAt: number | bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link EvalEntryOrderArgs} account data. */
export function getEvalEntryOrderEncoder(): FixedSizeEncoder<EvalEntryOrderArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["evaluation", getAddressEncoder()],
      ["trader", getAddressEncoder()],
      ["orderId", getU8Encoder()],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["direction", getDirectionEncoder()],
      ["kind", getEntryKindEncoder()],
      ["triggerPrice", getI64Encoder()],
      ["sizeBase", getU64Encoder()],
      ["stopLossPrice", getI64Encoder()],
      ["takeProfitPrice", getI64Encoder()],
      ["expiresAt", getI64Encoder()],
      ["createdAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: EVAL_ENTRY_ORDER_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link EvalEntryOrder} account data. */
export function getEvalEntryOrderDecoder(): FixedSizeDecoder<EvalEntryOrder> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["evaluation", getAddressDecoder()],
    ["trader", getAddressDecoder()],
    ["orderId", getU8Decoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["direction", getDirectionDecoder()],
    ["kind", getEntryKindDecoder()],
    ["triggerPrice", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
    ["stopLossPrice", getI64Decoder()],
    ["takeProfitPrice", getI64Decoder()],
    ["expiresAt", getI64Decoder()],
    ["createdAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link EvalEntryOrder} account data. */
export function getEvalEntryOrderCodec(): FixedSizeCodec<
  EvalEntryOrderArgs,
  EvalEntryOrder
> {
  return combineCodec(getEvalEntryOrderEncoder(), getEvalEntryOrderDecoder());
}

export function decodeEvalEntryOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<EvalEntryOrder, TAddress>;
export function decodeEvalEntryOrder<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<EvalEntryOrder, TAddress>;
export function decodeEvalEntryOrder<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<EvalEntryOrder, TAddress> | MaybeAccount<EvalEntryOrder, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getEvalEntryOrderDecoder(),
  );
}

export async function fetchEvalEntryOrder<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<EvalEntryOrder, TAddress>> {
  const maybeAccount = await fetchMaybeEvalEntryOrder(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeEvalEntryOrder<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<EvalEntryOrder, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeEvalEntryOrder(maybeAccount);
}

export async function fetchAllEvalEntryOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<EvalEntryOrder>[]> {
  const maybeAccounts = await fetchAllMaybeEvalEntryOrder(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeEvalEntryOrder(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<EvalEntryOrder>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeEvalEntryOrder(maybeAccount),
  );
}

export function getEvalEntryOrderSize(): number {
  return 159;
}
