/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const FUNDING_REQUEST_DISCRIMINATOR = new Uint8Array([
  78, 109, 168, 114, 238, 219, 124, 44,
]);

export function getFundingRequestDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDING_REQUEST_DISCRIMINATOR,
  );
}

export type FundingRequest = {
  discriminator: ReadonlyUint8Array;
  trader: Address;
  investor: Address;
  wantedPrincipal: bigint;
  wantedSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  createdAt: bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export type FundingRequestArgs = {
  trader: Address;
  investor: Address;
  wantedPrincipal: number | bigint;
  wantedSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  createdAt: number | bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link FundingRequestArgs} account data. */
export function getFundingRequestEncoder(): FixedSizeEncoder<FundingRequestArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["trader", getAddressEncoder()],
      ["investor", getAddressEncoder()],
      ["wantedPrincipal", getU64Encoder()],
      ["wantedSplitBps", getU16Encoder()],
      ["note", fixEncoderSize(getBytesEncoder(), 180)],
      ["noteLen", getU8Encoder()],
      ["createdAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 16)],
    ]),
    (value) => ({ ...value, discriminator: FUNDING_REQUEST_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link FundingRequest} account data. */
export function getFundingRequestDecoder(): FixedSizeDecoder<FundingRequest> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["trader", getAddressDecoder()],
    ["investor", getAddressDecoder()],
    ["wantedPrincipal", getU64Decoder()],
    ["wantedSplitBps", getU16Decoder()],
    ["note", fixDecoderSize(getBytesDecoder(), 180)],
    ["noteLen", getU8Decoder()],
    ["createdAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 16)],
  ]);
}

/** Gets the codec for {@link FundingRequest} account data. */
export function getFundingRequestCodec(): FixedSizeCodec<
  FundingRequestArgs,
  FundingRequest
> {
  return combineCodec(getFundingRequestEncoder(), getFundingRequestDecoder());
}

export function decodeFundingRequest<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<FundingRequest, TAddress>;
export function decodeFundingRequest<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<FundingRequest, TAddress>;
export function decodeFundingRequest<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<FundingRequest, TAddress> | MaybeAccount<FundingRequest, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getFundingRequestDecoder(),
  );
}

export async function fetchFundingRequest<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<FundingRequest, TAddress>> {
  const maybeAccount = await fetchMaybeFundingRequest(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeFundingRequest<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<FundingRequest, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeFundingRequest(maybeAccount);
}

export async function fetchAllFundingRequest(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<FundingRequest>[]> {
  const maybeAccounts = await fetchAllMaybeFundingRequest(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeFundingRequest(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<FundingRequest>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeFundingRequest(maybeAccount),
  );
}

export function getFundingRequestSize(): number {
  return 288;
}
