/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const INVESTOR_LISTING_DISCRIMINATOR = new Uint8Array([
  157, 178, 167, 218, 163, 179, 227, 121,
]);

export function getInvestorListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INVESTOR_LISTING_DISCRIMINATOR,
  );
}

export type InvestorListing = {
  discriminator: ReadonlyUint8Array;
  investor: Address;
  /** The band of principal this investor is prepared to put behind one trader. */
  minPrincipal: bigint;
  maxPrincipal: bigint;
  maxDrawdownBps: number;
  maxRiskPerTradeBps: number;
  allowedMarkets: bigint;
  offeredSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  open: boolean;
  createdAt: bigint;
  updatedAt: bigint;
  bump: number;
  /**
   * A display name, so the marketplace reads as people rather than as base58.
   *
   * Carved out of the reserved bytes rather than appended, so `INIT_SPACE` does not move: every
   * listing already on chain stays valid and decodes with an empty nickname, because those
   * bytes are zero. Growing the account instead would have meant a realloc, a migration, and
   * rent nobody agreed to. The address stays beside it everywhere — a name is a convenience,
   * never an identity, and two traders may choose the same one.
   */
  nickname: ReadonlyUint8Array;
  nicknameLen: number;
  reserved: ReadonlyUint8Array;
};

export type InvestorListingArgs = {
  investor: Address;
  /** The band of principal this investor is prepared to put behind one trader. */
  minPrincipal: number | bigint;
  maxPrincipal: number | bigint;
  maxDrawdownBps: number;
  maxRiskPerTradeBps: number;
  allowedMarkets: number | bigint;
  offeredSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  open: boolean;
  createdAt: number | bigint;
  updatedAt: number | bigint;
  bump: number;
  /**
   * A display name, so the marketplace reads as people rather than as base58.
   *
   * Carved out of the reserved bytes rather than appended, so `INIT_SPACE` does not move: every
   * listing already on chain stays valid and decodes with an empty nickname, because those
   * bytes are zero. Growing the account instead would have meant a realloc, a migration, and
   * rent nobody agreed to. The address stays beside it everywhere — a name is a convenience,
   * never an identity, and two traders may choose the same one.
   */
  nickname: ReadonlyUint8Array;
  nicknameLen: number;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link InvestorListingArgs} account data. */
export function getInvestorListingEncoder(): FixedSizeEncoder<InvestorListingArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["investor", getAddressEncoder()],
      ["minPrincipal", getU64Encoder()],
      ["maxPrincipal", getU64Encoder()],
      ["maxDrawdownBps", getU16Encoder()],
      ["maxRiskPerTradeBps", getU16Encoder()],
      ["allowedMarkets", getU128Encoder()],
      ["offeredSplitBps", getU16Encoder()],
      ["note", fixEncoderSize(getBytesEncoder(), 180)],
      ["noteLen", getU8Encoder()],
      ["open", getBooleanEncoder()],
      ["createdAt", getI64Encoder()],
      ["updatedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["nickname", fixEncoderSize(getBytesEncoder(), 24)],
      ["nicknameLen", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 7)],
    ]),
    (value) => ({ ...value, discriminator: INVESTOR_LISTING_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link InvestorListing} account data. */
export function getInvestorListingDecoder(): FixedSizeDecoder<InvestorListing> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["investor", getAddressDecoder()],
    ["minPrincipal", getU64Decoder()],
    ["maxPrincipal", getU64Decoder()],
    ["maxDrawdownBps", getU16Decoder()],
    ["maxRiskPerTradeBps", getU16Decoder()],
    ["allowedMarkets", getU128Decoder()],
    ["offeredSplitBps", getU16Decoder()],
    ["note", fixDecoderSize(getBytesDecoder(), 180)],
    ["noteLen", getU8Decoder()],
    ["open", getBooleanDecoder()],
    ["createdAt", getI64Decoder()],
    ["updatedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["nickname", fixDecoderSize(getBytesDecoder(), 24)],
    ["nicknameLen", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 7)],
  ]);
}

/** Gets the codec for {@link InvestorListing} account data. */
export function getInvestorListingCodec(): FixedSizeCodec<
  InvestorListingArgs,
  InvestorListing
> {
  return combineCodec(getInvestorListingEncoder(), getInvestorListingDecoder());
}

export function decodeInvestorListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<InvestorListing, TAddress>;
export function decodeInvestorListing<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<InvestorListing, TAddress>;
export function decodeInvestorListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  Account<InvestorListing, TAddress> | MaybeAccount<InvestorListing, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getInvestorListingDecoder(),
  );
}

export async function fetchInvestorListing<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<InvestorListing, TAddress>> {
  const maybeAccount = await fetchMaybeInvestorListing(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeInvestorListing<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<InvestorListing, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeInvestorListing(maybeAccount);
}

export async function fetchAllInvestorListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<InvestorListing>[]> {
  const maybeAccounts = await fetchAllMaybeInvestorListing(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeInvestorListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<InvestorListing>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeInvestorListing(maybeAccount),
  );
}

export function getInvestorListingSize(): number {
  return 309;
}
