/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getMandateStateDecoder,
  getMandateStateEncoder,
  getPositionSlotDecoder,
  getPositionSlotEncoder,
  type MandateState,
  type MandateStateArgs,
  type PositionSlot,
  type PositionSlotArgs,
} from "../types";

export const MANDATE_DISCRIMINATOR = new Uint8Array([
  113, 216, 98, 159, 185, 63, 55, 18,
]);

export function getMandateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MANDATE_DISCRIMINATOR);
}

export type Mandate = {
  discriminator: ReadonlyUint8Array;
  investor: Address;
  trader: Address;
  /** Lets one investor fund the same trader more than once. */
  seq: number;
  /** The SolFX `UserAccount` this mandate's signer authorises. */
  solfxUserAccount: Address;
  /**
   * Bump of the dataless signer PDA. Stored so no instruction re-derives it — that costs
   * ~1,500 CU for nothing, and this program signs two CPIs per trade.
   */
  signerBump: number;
  /** What the investor put in, in USDC at `QUOTE_PRECISION`. */
  principal: bigint;
  /**
   * High-water mark of equity. Only ever rises, so a trader cannot reset their drawdown by
   * closing out or withdrawing.
   */
  peakEquity: bigint;
  /** Ceiling on a single trade's notional, in USDC. */
  maxTradeNotional: bigint;
  /** Ceiling on the sum of all open notional, in USDC. */
  maxTotalNotional: bigint;
  /** Trailing from `peak_equity`. 300 = 3%. */
  maxDrawdownBps: number;
  maxDailyLossBps: number;
  /**
   * Risk at the stop, as bps of equity. This is the rule no centralized firm can enforce
   * *before* the fill, and it is only checkable because the stop is mandatory and placed in
   * the same transaction.
   */
  maxRiskPerTradeBps: number;
  /** A stop 99% away is not a stop. */
  maxStopDistanceBps: number;
  maxConcurrentPositions: number;
  /**
   * Bitmap over `market_index`. `u128`, so 128 markets — SolFX lists 29 today and the
   * upper tiers plausibly reach 50–60, which left `u64` uncomfortably close.
   */
  allowedMarkets: bigint;
  /** The no-scalping rule. Applies to **voluntary** closes only; a stop-out is exempt. */
  minHoldSlots: bigint;
  /** Trader's share of net profit. 7000 = 70%. */
  traderSplitBps: number;
  state: MandateState;
  /**
   * How many SolFX positions this mandate currently holds open. Maintained here because
   * SolFX stores no per-account position count, and the concurrency rule needs one.
   */
  openPositions: number;
  /**
   * Sum of the notional of every open position, in USDC, as booked at entry.
   *
   * Booked at entry rather than marked, for the same reason SolFX stores `entry_notional`
   * on a position: a figure that moves with the price would make the total drift on a
   * mandate that merely held, and the rule is about how much exposure the trader *took*.
   */
  openNotional: bigint;
  /** Equity at the last observation, in USDC. Zero until the first crank. */
  lastEquity: bigint;
  /**
   * When that observation happened. The crank cadence is the honesty of the drawdown rule,
   * so it is recorded rather than implied.
   */
  lastObservedAt: bigint;
  /**
   * The positions currently open, one slot each. `open_positions` and `open_notional` are
   * kept equal to what these slots sum to; they are stored for cheap reads by the rules.
   */
  slots: Array<PositionSlot>;
  openedAt: bigint;
  bump: number;
  /**
   * Bump of the mandate's USDC vault at `["vault", mandate]`, stored so every instruction that
   * touches the vault re-checks its address without re-deriving it.
   */
  vaultBump: number;
  /**
   * SolFX free collateral as NOXFUNDS last accounted for it.
   *
   * Moved only by the effect of NOXFUNDS' own instructions — never re-read from the account —
   * so `free_collateral - last_free_collateral` is always exactly what positions closed
   * *outside* NOXFUNDS (a stop, a take-profit, a liquidation) have credited back. That is how
   * `reconcile_position` learns what a stop-out made after the position account is gone.
   * Signed because a trader may spend a credit before it is reconciled.
   */
  lastFreeCollateral: bigint;
  /** Margin plus open fee of every tracked open position: what SolFX debited to open them. */
  bookedMarginFees: bigint;
  /** The UTC day `day_start_equity` belongs to, as `unix_timestamp / 86_400`. */
  day: bigint;
  /** Equity when `day` began, as last observed — the daily loss limit's baseline. */
  dayStartEquity: bigint;
  /**
   * Net result of every trade recorded against this mandate. Decides whether it settled in
   * profit, because the vault balance can be inflated by anyone sending USDC to it.
   */
  realizedPnl: bigint;
  reserved: ReadonlyUint8Array;
};

export type MandateArgs = {
  investor: Address;
  trader: Address;
  /** Lets one investor fund the same trader more than once. */
  seq: number;
  /** The SolFX `UserAccount` this mandate's signer authorises. */
  solfxUserAccount: Address;
  /**
   * Bump of the dataless signer PDA. Stored so no instruction re-derives it — that costs
   * ~1,500 CU for nothing, and this program signs two CPIs per trade.
   */
  signerBump: number;
  /** What the investor put in, in USDC at `QUOTE_PRECISION`. */
  principal: number | bigint;
  /**
   * High-water mark of equity. Only ever rises, so a trader cannot reset their drawdown by
   * closing out or withdrawing.
   */
  peakEquity: number | bigint;
  /** Ceiling on a single trade's notional, in USDC. */
  maxTradeNotional: number | bigint;
  /** Ceiling on the sum of all open notional, in USDC. */
  maxTotalNotional: number | bigint;
  /** Trailing from `peak_equity`. 300 = 3%. */
  maxDrawdownBps: number;
  maxDailyLossBps: number;
  /**
   * Risk at the stop, as bps of equity. This is the rule no centralized firm can enforce
   * *before* the fill, and it is only checkable because the stop is mandatory and placed in
   * the same transaction.
   */
  maxRiskPerTradeBps: number;
  /** A stop 99% away is not a stop. */
  maxStopDistanceBps: number;
  maxConcurrentPositions: number;
  /**
   * Bitmap over `market_index`. `u128`, so 128 markets — SolFX lists 29 today and the
   * upper tiers plausibly reach 50–60, which left `u64` uncomfortably close.
   */
  allowedMarkets: number | bigint;
  /** The no-scalping rule. Applies to **voluntary** closes only; a stop-out is exempt. */
  minHoldSlots: number | bigint;
  /** Trader's share of net profit. 7000 = 70%. */
  traderSplitBps: number;
  state: MandateStateArgs;
  /**
   * How many SolFX positions this mandate currently holds open. Maintained here because
   * SolFX stores no per-account position count, and the concurrency rule needs one.
   */
  openPositions: number;
  /**
   * Sum of the notional of every open position, in USDC, as booked at entry.
   *
   * Booked at entry rather than marked, for the same reason SolFX stores `entry_notional`
   * on a position: a figure that moves with the price would make the total drift on a
   * mandate that merely held, and the rule is about how much exposure the trader *took*.
   */
  openNotional: number | bigint;
  /** Equity at the last observation, in USDC. Zero until the first crank. */
  lastEquity: number | bigint;
  /**
   * When that observation happened. The crank cadence is the honesty of the drawdown rule,
   * so it is recorded rather than implied.
   */
  lastObservedAt: number | bigint;
  /**
   * The positions currently open, one slot each. `open_positions` and `open_notional` are
   * kept equal to what these slots sum to; they are stored for cheap reads by the rules.
   */
  slots: Array<PositionSlotArgs>;
  openedAt: number | bigint;
  bump: number;
  /**
   * Bump of the mandate's USDC vault at `["vault", mandate]`, stored so every instruction that
   * touches the vault re-checks its address without re-deriving it.
   */
  vaultBump: number;
  /**
   * SolFX free collateral as NOXFUNDS last accounted for it.
   *
   * Moved only by the effect of NOXFUNDS' own instructions — never re-read from the account —
   * so `free_collateral - last_free_collateral` is always exactly what positions closed
   * *outside* NOXFUNDS (a stop, a take-profit, a liquidation) have credited back. That is how
   * `reconcile_position` learns what a stop-out made after the position account is gone.
   * Signed because a trader may spend a credit before it is reconciled.
   */
  lastFreeCollateral: number | bigint;
  /** Margin plus open fee of every tracked open position: what SolFX debited to open them. */
  bookedMarginFees: number | bigint;
  /** The UTC day `day_start_equity` belongs to, as `unix_timestamp / 86_400`. */
  day: number | bigint;
  /** Equity when `day` began, as last observed — the daily loss limit's baseline. */
  dayStartEquity: number | bigint;
  /**
   * Net result of every trade recorded against this mandate. Decides whether it settled in
   * profit, because the vault balance can be inflated by anyone sending USDC to it.
   */
  realizedPnl: number | bigint;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link MandateArgs} account data. */
export function getMandateEncoder(): FixedSizeEncoder<MandateArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["investor", getAddressEncoder()],
      ["trader", getAddressEncoder()],
      ["seq", getU8Encoder()],
      ["solfxUserAccount", getAddressEncoder()],
      ["signerBump", getU8Encoder()],
      ["principal", getU64Encoder()],
      ["peakEquity", getU64Encoder()],
      ["maxTradeNotional", getU64Encoder()],
      ["maxTotalNotional", getU64Encoder()],
      ["maxDrawdownBps", getU16Encoder()],
      ["maxDailyLossBps", getU16Encoder()],
      ["maxRiskPerTradeBps", getU16Encoder()],
      ["maxStopDistanceBps", getU16Encoder()],
      ["maxConcurrentPositions", getU8Encoder()],
      ["allowedMarkets", getU128Encoder()],
      ["minHoldSlots", getU64Encoder()],
      ["traderSplitBps", getU16Encoder()],
      ["state", getMandateStateEncoder()],
      ["openPositions", getU8Encoder()],
      ["openNotional", getU64Encoder()],
      ["lastEquity", getU64Encoder()],
      ["lastObservedAt", getI64Encoder()],
      ["slots", getArrayEncoder(getPositionSlotEncoder(), { size: 8 })],
      ["openedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["vaultBump", getU8Encoder()],
      ["lastFreeCollateral", getI64Encoder()],
      ["bookedMarginFees", getU64Encoder()],
      ["day", getI64Encoder()],
      ["dayStartEquity", getU64Encoder()],
      ["realizedPnl", getI64Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 23)],
    ]),
    (value) => ({ ...value, discriminator: MANDATE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Mandate} account data. */
export function getMandateDecoder(): FixedSizeDecoder<Mandate> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["investor", getAddressDecoder()],
    ["trader", getAddressDecoder()],
    ["seq", getU8Decoder()],
    ["solfxUserAccount", getAddressDecoder()],
    ["signerBump", getU8Decoder()],
    ["principal", getU64Decoder()],
    ["peakEquity", getU64Decoder()],
    ["maxTradeNotional", getU64Decoder()],
    ["maxTotalNotional", getU64Decoder()],
    ["maxDrawdownBps", getU16Decoder()],
    ["maxDailyLossBps", getU16Decoder()],
    ["maxRiskPerTradeBps", getU16Decoder()],
    ["maxStopDistanceBps", getU16Decoder()],
    ["maxConcurrentPositions", getU8Decoder()],
    ["allowedMarkets", getU128Decoder()],
    ["minHoldSlots", getU64Decoder()],
    ["traderSplitBps", getU16Decoder()],
    ["state", getMandateStateDecoder()],
    ["openPositions", getU8Decoder()],
    ["openNotional", getU64Decoder()],
    ["lastEquity", getU64Decoder()],
    ["lastObservedAt", getI64Decoder()],
    ["slots", getArrayDecoder(getPositionSlotDecoder(), { size: 8 })],
    ["openedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["vaultBump", getU8Decoder()],
    ["lastFreeCollateral", getI64Decoder()],
    ["bookedMarginFees", getU64Decoder()],
    ["day", getI64Decoder()],
    ["dayStartEquity", getU64Decoder()],
    ["realizedPnl", getI64Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 23)],
  ]);
}

/** Gets the codec for {@link Mandate} account data. */
export function getMandateCodec(): FixedSizeCodec<MandateArgs, Mandate> {
  return combineCodec(getMandateEncoder(), getMandateDecoder());
}

export function decodeMandate<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Mandate, TAddress>;
export function decodeMandate<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Mandate, TAddress>;
export function decodeMandate<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Mandate, TAddress> | MaybeAccount<Mandate, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMandateDecoder(),
  );
}

export async function fetchMandate<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Mandate, TAddress>> {
  const maybeAccount = await fetchMaybeMandate(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMandate<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Mandate, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMandate(maybeAccount);
}

export async function fetchAllMandate(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Mandate>[]> {
  const maybeAccounts = await fetchAllMaybeMandate(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMandate(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Mandate>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMandate(maybeAccount));
}

export function getMandateSize(): number {
  return 368;
}
