/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TRADER_LISTING_DISCRIMINATOR = new Uint8Array([
  26, 76, 11, 24, 74, 161, 177, 13,
]);

export function getTraderListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRADER_LISTING_DISCRIMINATOR,
  );
}

export type TraderListing = {
  discriminator: ReadonlyUint8Array;
  trader: Address;
  /**
   * The band of principal this trader will accept. An investor offering outside it is not
   * refused on chain — the listing is advertising, not a rule — but the frontend can grey
   * the offer form out, and a mismatch is visible to both sides before anyone signs.
   */
  minPrincipal: bigint;
  maxPrincipal: bigint;
  /**
   * The markets the trader is asking to be allowed. Bitmap over `market_index`, same shape
   * as `Mandate::allowed_markets`.
   */
  wantedMarkets: bigint;
  /**
   * The split the trader is asking for, in bps of net profit. Advisory: the binding number
   * is the one on the offer the investor actually signs.
   */
  wantedSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  /**
   * Closed listings stay on chain rather than being deleted, so a trader cannot quietly
   * withdraw a listing an investor is midway through responding to and leave a dangling
   * reference. Reopening is a single flag.
   */
  open: boolean;
  createdAt: bigint;
  updatedAt: bigint;
  bump: number;
  nickname: ReadonlyUint8Array;
  nicknameLen: number;
  reserved: ReadonlyUint8Array;
};

export type TraderListingArgs = {
  trader: Address;
  /**
   * The band of principal this trader will accept. An investor offering outside it is not
   * refused on chain — the listing is advertising, not a rule — but the frontend can grey
   * the offer form out, and a mismatch is visible to both sides before anyone signs.
   */
  minPrincipal: number | bigint;
  maxPrincipal: number | bigint;
  /**
   * The markets the trader is asking to be allowed. Bitmap over `market_index`, same shape
   * as `Mandate::allowed_markets`.
   */
  wantedMarkets: number | bigint;
  /**
   * The split the trader is asking for, in bps of net profit. Advisory: the binding number
   * is the one on the offer the investor actually signs.
   */
  wantedSplitBps: number;
  note: ReadonlyUint8Array;
  noteLen: number;
  /**
   * Closed listings stay on chain rather than being deleted, so a trader cannot quietly
   * withdraw a listing an investor is midway through responding to and leave a dangling
   * reference. Reopening is a single flag.
   */
  open: boolean;
  createdAt: number | bigint;
  updatedAt: number | bigint;
  bump: number;
  nickname: ReadonlyUint8Array;
  nicknameLen: number;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link TraderListingArgs} account data. */
export function getTraderListingEncoder(): FixedSizeEncoder<TraderListingArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["trader", getAddressEncoder()],
      ["minPrincipal", getU64Encoder()],
      ["maxPrincipal", getU64Encoder()],
      ["wantedMarkets", getU128Encoder()],
      ["wantedSplitBps", getU16Encoder()],
      ["note", fixEncoderSize(getBytesEncoder(), 180)],
      ["noteLen", getU8Encoder()],
      ["open", getBooleanEncoder()],
      ["createdAt", getI64Encoder()],
      ["updatedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
      ["nickname", fixEncoderSize(getBytesEncoder(), 24)],
      ["nicknameLen", getU8Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 7)],
    ]),
    (value) => ({ ...value, discriminator: TRADER_LISTING_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link TraderListing} account data. */
export function getTraderListingDecoder(): FixedSizeDecoder<TraderListing> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["trader", getAddressDecoder()],
    ["minPrincipal", getU64Decoder()],
    ["maxPrincipal", getU64Decoder()],
    ["wantedMarkets", getU128Decoder()],
    ["wantedSplitBps", getU16Decoder()],
    ["note", fixDecoderSize(getBytesDecoder(), 180)],
    ["noteLen", getU8Decoder()],
    ["open", getBooleanDecoder()],
    ["createdAt", getI64Decoder()],
    ["updatedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["nickname", fixDecoderSize(getBytesDecoder(), 24)],
    ["nicknameLen", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 7)],
  ]);
}

/** Gets the codec for {@link TraderListing} account data. */
export function getTraderListingCodec(): FixedSizeCodec<
  TraderListingArgs,
  TraderListing
> {
  return combineCodec(getTraderListingEncoder(), getTraderListingDecoder());
}

export function decodeTraderListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<TraderListing, TAddress>;
export function decodeTraderListing<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<TraderListing, TAddress>;
export function decodeTraderListing<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<TraderListing, TAddress> | MaybeAccount<TraderListing, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTraderListingDecoder(),
  );
}

export async function fetchTraderListing<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TraderListing, TAddress>> {
  const maybeAccount = await fetchMaybeTraderListing(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTraderListing<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TraderListing, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTraderListing(maybeAccount);
}

export async function fetchAllTraderListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TraderListing>[]> {
  const maybeAccounts = await fetchAllMaybeTraderListing(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTraderListing(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TraderListing>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTraderListing(maybeAccount));
}

export function getTraderListingSize(): number {
  return 305;
}
