/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getDirectionDecoder,
  getDirectionEncoder,
  type Direction,
  type DirectionArgs,
} from "../types";

export const VIRTUAL_POSITION_DISCRIMINATOR = new Uint8Array([
  197, 31, 155, 182, 114, 82, 179, 126,
]);

export function getVirtualPositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VIRTUAL_POSITION_DISCRIMINATOR,
  );
}

export type VirtualPosition = {
  discriminator: ReadonlyUint8Array;
  evaluation: Address;
  marketIndex: number;
  nonce: number;
  direction: Direction;
  sizeBase: bigint;
  /** The execution price — spread and skew included — exactly as `open_position` fills. */
  entryPrice: bigint;
  /** Notional at entry, in USDC. The carry basis, as on a real position. */
  entryNotional: bigint;
  stopPrice: bigint;
  openFee: bigint;
  /** `Market::cum_borrow_index` at entry, so carry accrues exactly as a real position's does. */
  cumBorrowEntry: bigint;
  openedAt: bigint;
  bump: number;
};

export type VirtualPositionArgs = {
  evaluation: Address;
  marketIndex: number;
  nonce: number;
  direction: DirectionArgs;
  sizeBase: number | bigint;
  /** The execution price — spread and skew included — exactly as `open_position` fills. */
  entryPrice: number | bigint;
  /** Notional at entry, in USDC. The carry basis, as on a real position. */
  entryNotional: number | bigint;
  stopPrice: number | bigint;
  openFee: number | bigint;
  /** `Market::cum_borrow_index` at entry, so carry accrues exactly as a real position's does. */
  cumBorrowEntry: number | bigint;
  openedAt: number | bigint;
  bump: number;
};

/** Gets the encoder for {@link VirtualPositionArgs} account data. */
export function getVirtualPositionEncoder(): FixedSizeEncoder<VirtualPositionArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["evaluation", getAddressEncoder()],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["direction", getDirectionEncoder()],
      ["sizeBase", getU64Encoder()],
      ["entryPrice", getI64Encoder()],
      ["entryNotional", getU64Encoder()],
      ["stopPrice", getI64Encoder()],
      ["openFee", getU64Encoder()],
      ["cumBorrowEntry", getU128Encoder()],
      ["openedAt", getI64Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: VIRTUAL_POSITION_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link VirtualPosition} account data. */
export function getVirtualPositionDecoder(): FixedSizeDecoder<VirtualPosition> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["evaluation", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["direction", getDirectionDecoder()],
    ["sizeBase", getU64Decoder()],
    ["entryPrice", getI64Decoder()],
    ["entryNotional", getU64Decoder()],
    ["stopPrice", getI64Decoder()],
    ["openFee", getU64Decoder()],
    ["cumBorrowEntry", getU128Decoder()],
    ["openedAt", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link VirtualPosition} account data. */
export function getVirtualPositionCodec(): FixedSizeCodec<
  VirtualPositionArgs,
  VirtualPosition
> {
  return combineCodec(getVirtualPositionEncoder(), getVirtualPositionDecoder());
}

export function decodeVirtualPosition<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<VirtualPosition, TAddress>;
export function decodeVirtualPosition<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<VirtualPosition, TAddress>;
export function decodeVirtualPosition<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  Account<VirtualPosition, TAddress> | MaybeAccount<VirtualPosition, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getVirtualPositionDecoder(),
  );
}

export async function fetchVirtualPosition<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<VirtualPosition, TAddress>> {
  const maybeAccount = await fetchMaybeVirtualPosition(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeVirtualPosition<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<VirtualPosition, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeVirtualPosition(maybeAccount);
}

export async function fetchAllVirtualPosition(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<VirtualPosition>[]> {
  const maybeAccounts = await fetchAllMaybeVirtualPosition(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeVirtualPosition(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<VirtualPosition>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeVirtualPosition(maybeAccount),
  );
}

export function getVirtualPositionSize(): number {
  return 109;
}
