/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  findConfigPda,
  findMandateSignerPda,
  findMandateVaultPda,
  findOfferVaultPda,
  findTraderProfilePda,
} from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const ACCEPT_OFFER_DISCRIMINATOR = new Uint8Array([
  227, 82, 234, 131, 1, 18, 48, 2,
]);

export function getAcceptOfferDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ACCEPT_OFFER_DISCRIMINATOR,
  );
}

export type AcceptOfferInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountOffer extends string | AccountMeta<string> = string,
  TAccountTraderProfile extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountSolfxUserAccount extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountOfferVault extends string | AccountMeta<string> = string,
  TAccountMandateVault extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountOffer extends string
        ? WritableAccount<TAccountOffer>
        : TAccountOffer,
      TAccountTraderProfile extends string
        ? WritableAccount<TAccountTraderProfile>
        : TAccountTraderProfile,
      TAccountMandate extends string
        ? WritableAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountSolfxUserAccount extends string
        ? ReadonlyAccount<TAccountSolfxUserAccount>
        : TAccountSolfxUserAccount,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountOfferVault extends string
        ? WritableAccount<TAccountOfferVault>
        : TAccountOfferVault,
      TAccountMandateVault extends string
        ? WritableAccount<TAccountMandateVault>
        : TAccountMandateVault,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AcceptOfferInstructionData = { discriminator: ReadonlyUint8Array };

export type AcceptOfferInstructionDataArgs = {};

export function getAcceptOfferInstructionDataEncoder(): FixedSizeEncoder<AcceptOfferInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: ACCEPT_OFFER_DISCRIMINATOR }),
  );
}

export function getAcceptOfferInstructionDataDecoder(): FixedSizeDecoder<AcceptOfferInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getAcceptOfferInstructionDataCodec(): FixedSizeCodec<
  AcceptOfferInstructionDataArgs,
  AcceptOfferInstructionData
> {
  return combineCodec(
    getAcceptOfferInstructionDataEncoder(),
    getAcceptOfferInstructionDataDecoder(),
  );
}

export type AcceptOfferAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountOffer extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountSolfxUserAccount extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountOfferVault extends string = string,
  TAccountMandateVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The trader the offer is addressed to, and the only account that can do this. */
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  offer: Address<TAccountOffer>;
  traderProfile?: Address<TAccountTraderProfile>;
  /**
   * The mandate the offer becomes.
   *
   * Note the payer: the **trader**. An offer's escrow holds exactly the principal and nothing
   * for rent, and the investor is not a signer on this transaction, so the account cannot be
   * funded from either. That is the right incentive anyway — accepting capital costs the
   * trader the rent, which prices in a trader who accepts offers they do not intend to trade.
   */
  mandate: Address<TAccountMandate>;
  /**
   * Dataless, so the System Program will accept it as the `from` of the rent transfers that
   * `open_position` and `place_trigger_order` perform. See `Mandate`'s documentation.
   */
  mandateSigner?: Address<TAccountMandateSigner>;
  /**
   * `solfx-core` will create for the mandate signer, and is checked here to be exactly that.
   *
   * It used to be recorded as passed. Every later instruction is pinned to the stored address
   * and settlement requires a real SolFX account there, so a trader who named anything else
   * emptied the investor's escrow into a vault no instruction could pay out of again, for the
   * price of the mandate's rent (internal review R-1, 2026-09-23). It does not exist yet —
   * `create_solfx_account` makes it — so this is a seeds check on the address alone.
   */
  solfxUserAccount?: Address<TAccountSolfxUserAccount>;
  usdcMint: Address<TAccountUsdcMint>;
  offerVault?: Address<TAccountOfferVault>;
  mandateVault?: Address<TAccountMandateVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getAcceptOfferInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountOffer extends string,
  TAccountTraderProfile extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountSolfxUserAccount extends string,
  TAccountUsdcMint extends string,
  TAccountOfferVault extends string,
  TAccountMandateVault extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: AcceptOfferAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountOffer,
    TAccountTraderProfile,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountSolfxUserAccount,
    TAccountUsdcMint,
    TAccountOfferVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AcceptOfferInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountOffer,
    TAccountTraderProfile,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountSolfxUserAccount,
    TAccountUsdcMint,
    TAccountOfferVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    offer: { value: input.offer ?? null, isWritable: true },
    traderProfile: { value: input.traderProfile ?? null, isWritable: true },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    solfxUserAccount: {
      value: input.solfxUserAccount ?? null,
      isWritable: false,
    },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    offerVault: { value: input.offerVault ?? null, isWritable: true },
    mandateVault: { value: input.mandateVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.traderProfile.value) {
    accounts.traderProfile.value = await findTraderProfilePda({
      trader: expectAddress(accounts.trader.value),
    });
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.solfxUserAccount.value) {
    accounts.solfxUserAccount.value = await getProgramDerivedAddress({
      programAddress:
        "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([117, 115, 101, 114])),
        getAddressEncoder().encode(expectAddress(accounts.mandateSigner.value)),
      ],
    });
  }
  if (!accounts.offerVault.value) {
    accounts.offerVault.value = await findOfferVaultPda({
      offer: expectAddress(accounts.offer.value),
    });
  }
  if (!accounts.mandateVault.value) {
    accounts.mandateVault.value = await findMandateVaultPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.offer),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.solfxUserAccount),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.offerVault),
      getAccountMeta(accounts.mandateVault),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAcceptOfferInstructionDataEncoder().encode({}),
    programAddress,
  } as AcceptOfferInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountOffer,
    TAccountTraderProfile,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountSolfxUserAccount,
    TAccountUsdcMint,
    TAccountOfferVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type AcceptOfferInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountOffer extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountSolfxUserAccount extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountOfferVault extends string = string,
  TAccountMandateVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The trader the offer is addressed to, and the only account that can do this. */
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  offer: Address<TAccountOffer>;
  traderProfile: Address<TAccountTraderProfile>;
  /**
   * The mandate the offer becomes.
   *
   * Note the payer: the **trader**. An offer's escrow holds exactly the principal and nothing
   * for rent, and the investor is not a signer on this transaction, so the account cannot be
   * funded from either. That is the right incentive anyway — accepting capital costs the
   * trader the rent, which prices in a trader who accepts offers they do not intend to trade.
   */
  mandate: Address<TAccountMandate>;
  /**
   * Dataless, so the System Program will accept it as the `from` of the rent transfers that
   * `open_position` and `place_trigger_order` perform. See `Mandate`'s documentation.
   */
  mandateSigner: Address<TAccountMandateSigner>;
  /**
   * `solfx-core` will create for the mandate signer, and is checked here to be exactly that.
   *
   * It used to be recorded as passed. Every later instruction is pinned to the stored address
   * and settlement requires a real SolFX account there, so a trader who named anything else
   * emptied the investor's escrow into a vault no instruction could pay out of again, for the
   * price of the mandate's rent (internal review R-1, 2026-09-23). It does not exist yet —
   * `create_solfx_account` makes it — so this is a seeds check on the address alone.
   */
  solfxUserAccount: Address<TAccountSolfxUserAccount>;
  usdcMint: Address<TAccountUsdcMint>;
  offerVault: Address<TAccountOfferVault>;
  mandateVault: Address<TAccountMandateVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getAcceptOfferInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountOffer extends string,
  TAccountTraderProfile extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountSolfxUserAccount extends string,
  TAccountUsdcMint extends string,
  TAccountOfferVault extends string,
  TAccountMandateVault extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: AcceptOfferInput<
    TAccountTrader,
    TAccountConfig,
    TAccountOffer,
    TAccountTraderProfile,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountSolfxUserAccount,
    TAccountUsdcMint,
    TAccountOfferVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AcceptOfferInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountOffer,
  TAccountTraderProfile,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountSolfxUserAccount,
  TAccountUsdcMint,
  TAccountOfferVault,
  TAccountMandateVault,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    offer: { value: input.offer ?? null, isWritable: true },
    traderProfile: { value: input.traderProfile ?? null, isWritable: true },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    solfxUserAccount: {
      value: input.solfxUserAccount ?? null,
      isWritable: false,
    },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    offerVault: { value: input.offerVault ?? null, isWritable: true },
    mandateVault: { value: input.mandateVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.offer),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.solfxUserAccount),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.offerVault),
      getAccountMeta(accounts.mandateVault),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAcceptOfferInstructionDataEncoder().encode({}),
    programAddress,
  } as AcceptOfferInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountOffer,
    TAccountTraderProfile,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountSolfxUserAccount,
    TAccountUsdcMint,
    TAccountOfferVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedAcceptOfferInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The trader the offer is addressed to, and the only account that can do this. */
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    offer: TAccountMetas[2];
    traderProfile: TAccountMetas[3];
    /**
     * The mandate the offer becomes.
     *
     * Note the payer: the **trader**. An offer's escrow holds exactly the principal and nothing
     * for rent, and the investor is not a signer on this transaction, so the account cannot be
     * funded from either. That is the right incentive anyway — accepting capital costs the
     * trader the rent, which prices in a trader who accepts offers they do not intend to trade.
     */
    mandate: TAccountMetas[4];
    /**
     * Dataless, so the System Program will accept it as the `from` of the rent transfers that
     * `open_position` and `place_trigger_order` perform. See `Mandate`'s documentation.
     */
    mandateSigner: TAccountMetas[5];
    /**
     * `solfx-core` will create for the mandate signer, and is checked here to be exactly that.
     *
     * It used to be recorded as passed. Every later instruction is pinned to the stored address
     * and settlement requires a real SolFX account there, so a trader who named anything else
     * emptied the investor's escrow into a vault no instruction could pay out of again, for the
     * price of the mandate's rent (internal review R-1, 2026-09-23). It does not exist yet —
     * `create_solfx_account` makes it — so this is a seeds check on the address alone.
     */
    solfxUserAccount: TAccountMetas[6];
    usdcMint: TAccountMetas[7];
    offerVault: TAccountMetas[8];
    mandateVault: TAccountMetas[9];
    tokenProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: AcceptOfferInstructionData;
};

export function parseAcceptOfferInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAcceptOfferInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      offer: getNextAccount(),
      traderProfile: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      solfxUserAccount: getNextAccount(),
      usdcMint: getNextAccount(),
      offerVault: getNextAccount(),
      mandateVault: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAcceptOfferInstructionDataDecoder().decode(instruction.data),
  };
}
