/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findStakeVaultPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CLAIM_STAGE_PASS_DISCRIMINATOR = new Uint8Array([
  31, 92, 188, 154, 205, 34, 118, 4,
]);

export function getClaimStagePassDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_STAGE_PASS_DISCRIMINATOR,
  );
}

export type ClaimStagePassInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountTraderToken extends string | AccountMeta<string> = string,
  TAccountStakeVault extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEvaluation extends string
        ? WritableAccount<TAccountEvaluation>
        : TAccountEvaluation,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountTraderToken extends string
        ? WritableAccount<TAccountTraderToken>
        : TAccountTraderToken,
      TAccountStakeVault extends string
        ? WritableAccount<TAccountStakeVault>
        : TAccountStakeVault,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimStagePassInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClaimStagePassInstructionDataArgs = {};

export function getClaimStagePassInstructionDataEncoder(): FixedSizeEncoder<ClaimStagePassInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_STAGE_PASS_DISCRIMINATOR }),
  );
}

export function getClaimStagePassInstructionDataDecoder(): FixedSizeDecoder<ClaimStagePassInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimStagePassInstructionDataCodec(): FixedSizeCodec<
  ClaimStagePassInstructionDataArgs,
  ClaimStagePassInstructionData
> {
  return combineCodec(
    getClaimStagePassInstructionDataEncoder(),
    getClaimStagePassInstructionDataDecoder(),
  );
}

export type ClaimStagePassAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountTraderToken extends string = string,
  TAccountStakeVault extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  usdcMint: Address<TAccountUsdcMint>;
  traderToken: Address<TAccountTraderToken>;
  stakeVault?: Address<TAccountStakeVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getClaimStagePassInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountUsdcMint extends string,
  TAccountTraderToken extends string,
  TAccountStakeVault extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: ClaimStagePassAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountTraderToken,
    TAccountStakeVault,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimStagePassInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountTraderToken,
    TAccountStakeVault,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    traderToken: { value: input.traderToken ?? null, isWritable: true },
    stakeVault: { value: input.stakeVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.stakeVault.value) {
    accounts.stakeVault.value = await findStakeVaultPda({
      evaluation: expectAddress(accounts.evaluation.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.traderToken),
      getAccountMeta(accounts.stakeVault),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getClaimStagePassInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimStagePassInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountTraderToken,
    TAccountStakeVault,
    TAccountTokenProgram
  >);
}

export type ClaimStagePassInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountTraderToken extends string = string,
  TAccountStakeVault extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  usdcMint: Address<TAccountUsdcMint>;
  traderToken: Address<TAccountTraderToken>;
  stakeVault: Address<TAccountStakeVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getClaimStagePassInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountUsdcMint extends string,
  TAccountTraderToken extends string,
  TAccountStakeVault extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: ClaimStagePassInput<
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountTraderToken,
    TAccountStakeVault,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimStagePassInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountEvaluation,
  TAccountUsdcMint,
  TAccountTraderToken,
  TAccountStakeVault,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    traderToken: { value: input.traderToken ?? null, isWritable: true },
    stakeVault: { value: input.stakeVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.traderToken),
      getAccountMeta(accounts.stakeVault),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getClaimStagePassInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimStagePassInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountTraderToken,
    TAccountStakeVault,
    TAccountTokenProgram
  >);
}

export type ParsedClaimStagePassInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    evaluation: TAccountMetas[2];
    usdcMint: TAccountMetas[3];
    traderToken: TAccountMetas[4];
    stakeVault: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: ClaimStagePassInstructionData;
};

export function parseClaimStagePassInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimStagePassInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      evaluation: getNextAccount(),
      usdcMint: getNextAccount(),
      traderToken: getNextAccount(),
      stakeVault: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getClaimStagePassInstructionDataDecoder().decode(instruction.data),
  };
}
