/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CLOSE_REQUEST_DISCRIMINATOR = new Uint8Array([
  170, 46, 165, 120, 223, 102, 115, 2,
]);

export function getCloseRequestDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_REQUEST_DISCRIMINATOR,
  );
}

export type CloseRequestInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCloser extends string | AccountMeta<string> = string,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountRequest extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCloser extends string
        ? ReadonlySignerAccount<TAccountCloser> &
            AccountSignerMeta<TAccountCloser>
        : TAccountCloser,
      TAccountTrader extends string
        ? WritableAccount<TAccountTrader>
        : TAccountTrader,
      TAccountRequest extends string
        ? WritableAccount<TAccountRequest>
        : TAccountRequest,
      ...TRemainingAccounts,
    ]
  >;

export type CloseRequestInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseRequestInstructionDataArgs = {};

export function getCloseRequestInstructionDataEncoder(): FixedSizeEncoder<CloseRequestInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_REQUEST_DISCRIMINATOR }),
  );
}

export function getCloseRequestInstructionDataDecoder(): FixedSizeDecoder<CloseRequestInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseRequestInstructionDataCodec(): FixedSizeCodec<
  CloseRequestInstructionDataArgs,
  CloseRequestInstructionData
> {
  return combineCodec(
    getCloseRequestInstructionDataEncoder(),
    getCloseRequestInstructionDataDecoder(),
  );
}

export type CloseRequestInput<
  TAccountCloser extends string = string,
  TAccountTrader extends string = string,
  TAccountRequest extends string = string,
> = {
  /** Either party. The trader withdraws the ask; the investor dismisses it. */
  closer: TransactionSigner<TAccountCloser>;
  /**
   * Where the rent goes: always back to the trader who paid it, whoever closes. An investor
   * dismissing a request must not be able to pocket the trader's deposit.
   */
  trader: Address<TAccountTrader>;
  request: Address<TAccountRequest>;
};

export function getCloseRequestInstruction<
  TAccountCloser extends string,
  TAccountTrader extends string,
  TAccountRequest extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: CloseRequestInput<TAccountCloser, TAccountTrader, TAccountRequest>,
  config?: { programAddress?: TProgramAddress },
): CloseRequestInstruction<
  TProgramAddress,
  TAccountCloser,
  TAccountTrader,
  TAccountRequest
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    closer: { value: input.closer ?? null, isWritable: false },
    trader: { value: input.trader ?? null, isWritable: true },
    request: { value: input.request ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.closer),
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.request),
    ],
    data: getCloseRequestInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseRequestInstruction<
    TProgramAddress,
    TAccountCloser,
    TAccountTrader,
    TAccountRequest
  >);
}

export type ParsedCloseRequestInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Either party. The trader withdraws the ask; the investor dismisses it. */
    closer: TAccountMetas[0];
    /**
     * Where the rent goes: always back to the trader who paid it, whoever closes. An investor
     * dismissing a request must not be able to pocket the trader's deposit.
     */
    trader: TAccountMetas[1];
    request: TAccountMetas[2];
  };
  data: CloseRequestInstructionData;
};

export function parseCloseRequestInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCloseRequestInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      closer: getNextAccount(),
      trader: getNextAccount(),
      request: getNextAccount(),
    },
    data: getCloseRequestInstructionDataDecoder().decode(instruction.data),
  };
}
