/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const EVAL_CANCEL_ENTRY_ORDER_DISCRIMINATOR = new Uint8Array([
  138, 70, 125, 121, 61, 199, 90, 238,
]);

export function getEvalCancelEntryOrderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVAL_CANCEL_ENTRY_ORDER_DISCRIMINATOR,
  );
}

export type EvalCancelEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TAccountEntryOrder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTrader extends string
        ? WritableAccount<TAccountTrader>
        : TAccountTrader,
      TAccountEvaluation extends string
        ? WritableAccount<TAccountEvaluation>
        : TAccountEvaluation,
      TAccountEntryOrder extends string
        ? WritableAccount<TAccountEntryOrder>
        : TAccountEntryOrder,
      ...TRemainingAccounts,
    ]
  >;

export type EvalCancelEntryOrderInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type EvalCancelEntryOrderInstructionDataArgs = {};

export function getEvalCancelEntryOrderInstructionDataEncoder(): FixedSizeEncoder<EvalCancelEntryOrderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: EVAL_CANCEL_ENTRY_ORDER_DISCRIMINATOR,
    }),
  );
}

export function getEvalCancelEntryOrderInstructionDataDecoder(): FixedSizeDecoder<EvalCancelEntryOrderInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEvalCancelEntryOrderInstructionDataCodec(): FixedSizeCodec<
  EvalCancelEntryOrderInstructionDataArgs,
  EvalCancelEntryOrderInstructionData
> {
  return combineCodec(
    getEvalCancelEntryOrderInstructionDataEncoder(),
    getEvalCancelEntryOrderInstructionDataDecoder(),
  );
}

export type EvalCancelEntryOrderInput<
  TAccountCaller extends string = string,
  TAccountTrader extends string = string,
  TAccountEvaluation extends string = string,
  TAccountEntryOrder extends string = string,
> = {
  /** The trader at any time; anyone once the order can no longer fill. */
  caller: TransactionSigner<TAccountCaller>;
  trader: Address<TAccountTrader>;
  evaluation: Address<TAccountEvaluation>;
  entryOrder: Address<TAccountEntryOrder>;
};

export function getEvalCancelEntryOrderInstruction<
  TAccountCaller extends string,
  TAccountTrader extends string,
  TAccountEvaluation extends string,
  TAccountEntryOrder extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: EvalCancelEntryOrderInput<
    TAccountCaller,
    TAccountTrader,
    TAccountEvaluation,
    TAccountEntryOrder
  >,
  config?: { programAddress?: TProgramAddress },
): EvalCancelEntryOrderInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTrader,
  TAccountEvaluation,
  TAccountEntryOrder
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    trader: { value: input.trader ?? null, isWritable: true },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    entryOrder: { value: input.entryOrder ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.entryOrder),
    ],
    data: getEvalCancelEntryOrderInstructionDataEncoder().encode({}),
    programAddress,
  } as EvalCancelEntryOrderInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTrader,
    TAccountEvaluation,
    TAccountEntryOrder
  >);
}

export type ParsedEvalCancelEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The trader at any time; anyone once the order can no longer fill. */
    caller: TAccountMetas[0];
    trader: TAccountMetas[1];
    evaluation: TAccountMetas[2];
    entryOrder: TAccountMetas[3];
  };
  data: EvalCancelEntryOrderInstructionData;
};

export function parseEvalCancelEntryOrderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEvalCancelEntryOrderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      trader: getNextAccount(),
      evaluation: getNextAccount(),
      entryOrder: getNextAccount(),
    },
    data: getEvalCancelEntryOrderInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
