/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const EVAL_CLOSE_POSITION_DISCRIMINATOR = new Uint8Array([
  40, 137, 84, 57, 105, 46, 100, 9,
]);

export function getEvalClosePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVAL_CLOSE_POSITION_DISCRIMINATOR,
  );
}

export type EvalClosePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TAccountVirtualPosition extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPriceUpdate extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountEvaluation extends string
        ? WritableAccount<TAccountEvaluation>
        : TAccountEvaluation,
      TAccountVirtualPosition extends string
        ? WritableAccount<TAccountVirtualPosition>
        : TAccountVirtualPosition,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPriceUpdate extends string
        ? ReadonlyAccount<TAccountPriceUpdate>
        : TAccountPriceUpdate,
      ...TRemainingAccounts,
    ]
  >;

export type EvalClosePositionInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type EvalClosePositionInstructionDataArgs = {};

export function getEvalClosePositionInstructionDataEncoder(): FixedSizeEncoder<EvalClosePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EVAL_CLOSE_POSITION_DISCRIMINATOR }),
  );
}

export function getEvalClosePositionInstructionDataDecoder(): FixedSizeDecoder<EvalClosePositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEvalClosePositionInstructionDataCodec(): FixedSizeCodec<
  EvalClosePositionInstructionDataArgs,
  EvalClosePositionInstructionData
> {
  return combineCodec(
    getEvalClosePositionInstructionDataEncoder(),
    getEvalClosePositionInstructionDataDecoder(),
  );
}

export type EvalClosePositionInput<
  TAccountTrader extends string = string,
  TAccountEvaluation extends string = string,
  TAccountVirtualPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountPriceUpdate extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  evaluation: Address<TAccountEvaluation>;
  virtualPosition: Address<TAccountVirtualPosition>;
  market: Address<TAccountMarket>;
  priceUpdate: Address<TAccountPriceUpdate>;
};

export function getEvalClosePositionInstruction<
  TAccountTrader extends string,
  TAccountEvaluation extends string,
  TAccountVirtualPosition extends string,
  TAccountMarket extends string,
  TAccountPriceUpdate extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: EvalClosePositionInput<
    TAccountTrader,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate
  >,
  config?: { programAddress?: TProgramAddress },
): EvalClosePositionInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountEvaluation,
  TAccountVirtualPosition,
  TAccountMarket,
  TAccountPriceUpdate
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    virtualPosition: { value: input.virtualPosition ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.virtualPosition),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.priceUpdate),
    ],
    data: getEvalClosePositionInstructionDataEncoder().encode({}),
    programAddress,
  } as EvalClosePositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate
  >);
}

export type ParsedEvalClosePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    evaluation: TAccountMetas[1];
    virtualPosition: TAccountMetas[2];
    market: TAccountMetas[3];
    priceUpdate: TAccountMetas[4];
  };
  data: EvalClosePositionInstructionData;
};

export function parseEvalClosePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEvalClosePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      evaluation: getNextAccount(),
      virtualPosition: getNextAccount(),
      market: getNextAccount(),
      priceUpdate: getNextAccount(),
    },
    data: getEvalClosePositionInstructionDataDecoder().decode(instruction.data),
  };
}
