/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const EVAL_OBSERVE_EQUITY_DISCRIMINATOR = new Uint8Array([
  71, 249, 117, 82, 47, 216, 124, 7,
]);

export function getEvalObserveEquityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVAL_OBSERVE_EQUITY_DISCRIMINATOR,
  );
}

export type EvalObserveEquityInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountObserver extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountObserver extends string
        ? ReadonlySignerAccount<TAccountObserver> &
            AccountSignerMeta<TAccountObserver>
        : TAccountObserver,
      TAccountEvaluation extends string
        ? WritableAccount<TAccountEvaluation>
        : TAccountEvaluation,
      ...TRemainingAccounts,
    ]
  >;

export type EvalObserveEquityInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type EvalObserveEquityInstructionDataArgs = {};

export function getEvalObserveEquityInstructionDataEncoder(): FixedSizeEncoder<EvalObserveEquityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EVAL_OBSERVE_EQUITY_DISCRIMINATOR }),
  );
}

export function getEvalObserveEquityInstructionDataDecoder(): FixedSizeDecoder<EvalObserveEquityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEvalObserveEquityInstructionDataCodec(): FixedSizeCodec<
  EvalObserveEquityInstructionDataArgs,
  EvalObserveEquityInstructionData
> {
  return combineCodec(
    getEvalObserveEquityInstructionDataEncoder(),
    getEvalObserveEquityInstructionDataDecoder(),
  );
}

export type EvalObserveEquityInput<
  TAccountObserver extends string = string,
  TAccountEvaluation extends string = string,
> = {
  observer: TransactionSigner<TAccountObserver>;
  evaluation: Address<TAccountEvaluation>;
};

export function getEvalObserveEquityInstruction<
  TAccountObserver extends string,
  TAccountEvaluation extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: EvalObserveEquityInput<TAccountObserver, TAccountEvaluation>,
  config?: { programAddress?: TProgramAddress },
): EvalObserveEquityInstruction<
  TProgramAddress,
  TAccountObserver,
  TAccountEvaluation
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    observer: { value: input.observer ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.observer),
      getAccountMeta(accounts.evaluation),
    ],
    data: getEvalObserveEquityInstructionDataEncoder().encode({}),
    programAddress,
  } as EvalObserveEquityInstruction<
    TProgramAddress,
    TAccountObserver,
    TAccountEvaluation
  >);
}

export type ParsedEvalObserveEquityInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    observer: TAccountMetas[0];
    evaluation: TAccountMetas[1];
  };
  data: EvalObserveEquityInstructionData;
};

export function parseEvalObserveEquityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEvalObserveEquityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { observer: getNextAccount(), evaluation: getNextAccount() },
    data: getEvalObserveEquityInstructionDataDecoder().decode(instruction.data),
  };
}
