/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getDirectionDecoder,
  getDirectionEncoder,
  type Direction,
  type DirectionArgs,
} from "../types";

export const EVAL_OPEN_POSITION_DISCRIMINATOR = new Uint8Array([
  44, 175, 249, 12, 240, 36, 239, 100,
]);

export function getEvalOpenPositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EVAL_OPEN_POSITION_DISCRIMINATOR,
  );
}

export type EvalOpenPositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TAccountVirtualPosition extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPriceUpdate extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEvaluation extends string
        ? WritableAccount<TAccountEvaluation>
        : TAccountEvaluation,
      TAccountVirtualPosition extends string
        ? WritableAccount<TAccountVirtualPosition>
        : TAccountVirtualPosition,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPriceUpdate extends string
        ? ReadonlyAccount<TAccountPriceUpdate>
        : TAccountPriceUpdate,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type EvalOpenPositionInstructionData = {
  discriminator: ReadonlyUint8Array;
  marketIndex: number;
  nonce: number;
  direction: Direction;
  sizeBase: bigint;
  stopLossPrice: bigint;
};

export type EvalOpenPositionInstructionDataArgs = {
  marketIndex: number;
  nonce: number;
  direction: DirectionArgs;
  sizeBase: number | bigint;
  stopLossPrice: number | bigint;
};

export function getEvalOpenPositionInstructionDataEncoder(): FixedSizeEncoder<EvalOpenPositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["direction", getDirectionEncoder()],
      ["sizeBase", getU64Encoder()],
      ["stopLossPrice", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EVAL_OPEN_POSITION_DISCRIMINATOR }),
  );
}

export function getEvalOpenPositionInstructionDataDecoder(): FixedSizeDecoder<EvalOpenPositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["direction", getDirectionDecoder()],
    ["sizeBase", getU64Decoder()],
    ["stopLossPrice", getI64Decoder()],
  ]);
}

export function getEvalOpenPositionInstructionDataCodec(): FixedSizeCodec<
  EvalOpenPositionInstructionDataArgs,
  EvalOpenPositionInstructionData
> {
  return combineCodec(
    getEvalOpenPositionInstructionDataEncoder(),
    getEvalOpenPositionInstructionDataDecoder(),
  );
}

export type EvalOpenPositionAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountVirtualPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  virtualPosition: Address<TAccountVirtualPosition>;
  /**
   * SolFX's own market account. `Account<Market>` checks it is owned by `solfx-core`, which
   * is the only program that can create one, so it cannot be forged.
   */
  market: Address<TAccountMarket>;
  /**
   * Pyth's price update. `load_validated_price` checks it is the market's own feed and
   * applies every staleness and confidence gate a real fill applies.
   */
  priceUpdate: Address<TAccountPriceUpdate>;
  systemProgram?: Address<TAccountSystemProgram>;
  marketIndex: EvalOpenPositionInstructionDataArgs["marketIndex"];
  nonce: EvalOpenPositionInstructionDataArgs["nonce"];
  direction: EvalOpenPositionInstructionDataArgs["direction"];
  sizeBase: EvalOpenPositionInstructionDataArgs["sizeBase"];
  stopLossPrice: EvalOpenPositionInstructionDataArgs["stopLossPrice"];
};

export async function getEvalOpenPositionInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountVirtualPosition extends string,
  TAccountMarket extends string,
  TAccountPriceUpdate extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: EvalOpenPositionAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  EvalOpenPositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    virtualPosition: { value: input.virtualPosition ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.virtualPosition),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getEvalOpenPositionInstructionDataEncoder().encode(
      args as EvalOpenPositionInstructionDataArgs,
    ),
    programAddress,
  } as EvalOpenPositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate,
    TAccountSystemProgram
  >);
}

export type EvalOpenPositionInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountVirtualPosition extends string = string,
  TAccountMarket extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  virtualPosition: Address<TAccountVirtualPosition>;
  /**
   * SolFX's own market account. `Account<Market>` checks it is owned by `solfx-core`, which
   * is the only program that can create one, so it cannot be forged.
   */
  market: Address<TAccountMarket>;
  /**
   * Pyth's price update. `load_validated_price` checks it is the market's own feed and
   * applies every staleness and confidence gate a real fill applies.
   */
  priceUpdate: Address<TAccountPriceUpdate>;
  systemProgram?: Address<TAccountSystemProgram>;
  marketIndex: EvalOpenPositionInstructionDataArgs["marketIndex"];
  nonce: EvalOpenPositionInstructionDataArgs["nonce"];
  direction: EvalOpenPositionInstructionDataArgs["direction"];
  sizeBase: EvalOpenPositionInstructionDataArgs["sizeBase"];
  stopLossPrice: EvalOpenPositionInstructionDataArgs["stopLossPrice"];
};

export function getEvalOpenPositionInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountVirtualPosition extends string,
  TAccountMarket extends string,
  TAccountPriceUpdate extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: EvalOpenPositionInput<
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): EvalOpenPositionInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountEvaluation,
  TAccountVirtualPosition,
  TAccountMarket,
  TAccountPriceUpdate,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: true },
    virtualPosition: { value: input.virtualPosition ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.virtualPosition),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getEvalOpenPositionInstructionDataEncoder().encode(
      args as EvalOpenPositionInstructionDataArgs,
    ),
    programAddress,
  } as EvalOpenPositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountEvaluation,
    TAccountVirtualPosition,
    TAccountMarket,
    TAccountPriceUpdate,
    TAccountSystemProgram
  >);
}

export type ParsedEvalOpenPositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    evaluation: TAccountMetas[2];
    virtualPosition: TAccountMetas[3];
    /**
     * SolFX's own market account. `Account<Market>` checks it is owned by `solfx-core`, which
     * is the only program that can create one, so it cannot be forged.
     */
    market: TAccountMetas[4];
    /**
     * Pyth's price update. `load_validated_price` checks it is the market's own feed and
     * applies every staleness and confidence gate a real fill applies.
     */
    priceUpdate: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: EvalOpenPositionInstructionData;
};

export function parseEvalOpenPositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEvalOpenPositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      evaluation: getNextAccount(),
      virtualPosition: getNextAccount(),
      market: getNextAccount(),
      priceUpdate: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getEvalOpenPositionInstructionDataDecoder().decode(instruction.data),
  };
}
