/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda, findStakeVaultPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const FORFEIT_STAKE_DISCRIMINATOR = new Uint8Array([
  27, 161, 131, 64, 84, 25, 41, 228,
]);

export function getForfeitStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FORFEIT_STAKE_DISCRIMINATOR,
  );
}

export type ForfeitStakeInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEvaluation extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountStakeVault extends string | AccountMeta<string> = string,
  TAccountTreasuryToken extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEvaluation extends string
        ? ReadonlyAccount<TAccountEvaluation>
        : TAccountEvaluation,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountStakeVault extends string
        ? WritableAccount<TAccountStakeVault>
        : TAccountStakeVault,
      TAccountTreasuryToken extends string
        ? WritableAccount<TAccountTreasuryToken>
        : TAccountTreasuryToken,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ForfeitStakeInstructionData = { discriminator: ReadonlyUint8Array };

export type ForfeitStakeInstructionDataArgs = {};

export function getForfeitStakeInstructionDataEncoder(): FixedSizeEncoder<ForfeitStakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: FORFEIT_STAKE_DISCRIMINATOR }),
  );
}

export function getForfeitStakeInstructionDataDecoder(): FixedSizeDecoder<ForfeitStakeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getForfeitStakeInstructionDataCodec(): FixedSizeCodec<
  ForfeitStakeInstructionDataArgs,
  ForfeitStakeInstructionData
> {
  return combineCodec(
    getForfeitStakeInstructionDataEncoder(),
    getForfeitStakeInstructionDataDecoder(),
  );
}

export type ForfeitStakeAsyncInput<
  TAccountCaller extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountStakeVault extends string = string,
  TAccountTreasuryToken extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Anyone. The treasury should not depend on the failed trader's cooperation. */
  caller: TransactionSigner<TAccountCaller>;
  config?: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  usdcMint: Address<TAccountUsdcMint>;
  stakeVault?: Address<TAccountStakeVault>;
  /**
   * The treasury's USDC account, pinned to the configured treasury so a caller cannot send
   * the stake anywhere else.
   */
  treasuryToken: Address<TAccountTreasuryToken>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getForfeitStakeInstructionAsync<
  TAccountCaller extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountUsdcMint extends string,
  TAccountStakeVault extends string,
  TAccountTreasuryToken extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: ForfeitStakeAsyncInput<
    TAccountCaller,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountStakeVault,
    TAccountTreasuryToken,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ForfeitStakeInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountStakeVault,
    TAccountTreasuryToken,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: false },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    stakeVault: { value: input.stakeVault ?? null, isWritable: true },
    treasuryToken: { value: input.treasuryToken ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.stakeVault.value) {
    accounts.stakeVault.value = await findStakeVaultPda({
      evaluation: expectAddress(accounts.evaluation.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.stakeVault),
      getAccountMeta(accounts.treasuryToken),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getForfeitStakeInstructionDataEncoder().encode({}),
    programAddress,
  } as ForfeitStakeInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountStakeVault,
    TAccountTreasuryToken,
    TAccountTokenProgram
  >);
}

export type ForfeitStakeInput<
  TAccountCaller extends string = string,
  TAccountConfig extends string = string,
  TAccountEvaluation extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountStakeVault extends string = string,
  TAccountTreasuryToken extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Anyone. The treasury should not depend on the failed trader's cooperation. */
  caller: TransactionSigner<TAccountCaller>;
  config: Address<TAccountConfig>;
  evaluation: Address<TAccountEvaluation>;
  usdcMint: Address<TAccountUsdcMint>;
  stakeVault: Address<TAccountStakeVault>;
  /**
   * The treasury's USDC account, pinned to the configured treasury so a caller cannot send
   * the stake anywhere else.
   */
  treasuryToken: Address<TAccountTreasuryToken>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getForfeitStakeInstruction<
  TAccountCaller extends string,
  TAccountConfig extends string,
  TAccountEvaluation extends string,
  TAccountUsdcMint extends string,
  TAccountStakeVault extends string,
  TAccountTreasuryToken extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: ForfeitStakeInput<
    TAccountCaller,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountStakeVault,
    TAccountTreasuryToken,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ForfeitStakeInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountConfig,
  TAccountEvaluation,
  TAccountUsdcMint,
  TAccountStakeVault,
  TAccountTreasuryToken,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    evaluation: { value: input.evaluation ?? null, isWritable: false },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    stakeVault: { value: input.stakeVault ?? null, isWritable: true },
    treasuryToken: { value: input.treasuryToken ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.evaluation),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.stakeVault),
      getAccountMeta(accounts.treasuryToken),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getForfeitStakeInstructionDataEncoder().encode({}),
    programAddress,
  } as ForfeitStakeInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountConfig,
    TAccountEvaluation,
    TAccountUsdcMint,
    TAccountStakeVault,
    TAccountTreasuryToken,
    TAccountTokenProgram
  >);
}

export type ParsedForfeitStakeInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Anyone. The treasury should not depend on the failed trader's cooperation. */
    caller: TAccountMetas[0];
    config: TAccountMetas[1];
    evaluation: TAccountMetas[2];
    usdcMint: TAccountMetas[3];
    stakeVault: TAccountMetas[4];
    /**
     * The treasury's USDC account, pinned to the configured treasury so a caller cannot send
     * the stake anywhere else.
     */
    treasuryToken: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: ForfeitStakeInstructionData;
};

export function parseForfeitStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedForfeitStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      config: getNextAccount(),
      evaluation: getNextAccount(),
      usdcMint: getNextAccount(),
      stakeVault: getNextAccount(),
      treasuryToken: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getForfeitStakeInstructionDataDecoder().decode(instruction.data),
  };
}
