/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findMandateSignerPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const FUNDED_PLACE_TAKE_PROFIT_DISCRIMINATOR = new Uint8Array([
  195, 75, 243, 152, 49, 23, 236, 177,
]);

export function getFundedPlaceTakeProfitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDED_PLACE_TAKE_PROFIT_DISCRIMINATOR,
  );
}

export type FundedPlaceTakeProfitInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountProtocol extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TAccountPriceUpdate extends string | AccountMeta<string> = string,
  TAccountSecondaryPriceUpdate extends string | AccountMeta<string> = string,
  TAccountQuoteConversionPriceUpdate extends string | AccountMeta<string> =
    string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountSolfxCoreProgram extends string | AccountMeta<string> =
    "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? ReadonlyAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountProtocol extends string
        ? ReadonlyAccount<TAccountProtocol>
        : TAccountProtocol,
      TAccountUserAccount extends string
        ? ReadonlyAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      TAccountPriceUpdate extends string
        ? ReadonlyAccount<TAccountPriceUpdate>
        : TAccountPriceUpdate,
      TAccountSecondaryPriceUpdate extends string
        ? ReadonlyAccount<TAccountSecondaryPriceUpdate>
        : TAccountSecondaryPriceUpdate,
      TAccountQuoteConversionPriceUpdate extends string
        ? ReadonlyAccount<TAccountQuoteConversionPriceUpdate>
        : TAccountQuoteConversionPriceUpdate,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountSolfxCoreProgram extends string
        ? ReadonlyAccount<TAccountSolfxCoreProgram>
        : TAccountSolfxCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type FundedPlaceTakeProfitInstructionData = {
  discriminator: ReadonlyUint8Array;
  orderId: number;
  triggerPrice: bigint;
  sizeBase: bigint;
};

export type FundedPlaceTakeProfitInstructionDataArgs = {
  orderId: number;
  triggerPrice: number | bigint;
  sizeBase: number | bigint;
};

export function getFundedPlaceTakeProfitInstructionDataEncoder(): FixedSizeEncoder<FundedPlaceTakeProfitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["orderId", getU8Encoder()],
      ["triggerPrice", getI64Encoder()],
      ["sizeBase", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: FUNDED_PLACE_TAKE_PROFIT_DISCRIMINATOR,
    }),
  );
}

export function getFundedPlaceTakeProfitInstructionDataDecoder(): FixedSizeDecoder<FundedPlaceTakeProfitInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["orderId", getU8Decoder()],
    ["triggerPrice", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
  ]);
}

export function getFundedPlaceTakeProfitInstructionDataCodec(): FixedSizeCodec<
  FundedPlaceTakeProfitInstructionDataArgs,
  FundedPlaceTakeProfitInstructionData
> {
  return combineCodec(
    getFundedPlaceTakeProfitInstructionDataEncoder(),
    getFundedPlaceTakeProfitInstructionDataDecoder(),
  );
}

export type FundedPlaceTakeProfitAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  /**
   * Pays the transaction fee. Pays no rent: the trigger's rent comes from the mandate signer,
   * and comes back to it on a cancel.
   */
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  /** The SolFX authority: dataless, system-owned, signs the CPI and pays the trigger's rent. */
  mandateSigner?: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  /** this program can sign for. Not deserialized — this instruction prices nothing. */
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  /**
   * Read-only: `place_trigger_order` reads the position's size, direction and opening slot
   * and writes none of them. An unnecessary write lock would serialise this against a close
   * on the same position for no reason.
   */
  position: Address<TAccountPosition>;
  /**
   * the mandate signer. An `order_id` already in use fails there as "account already in use",
   * which is how a take-profit is prevented from ever overwriting the trade's stop.
   */
  triggerOrder: Address<TAccountTriggerOrder>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  systemProgram?: Address<TAccountSystemProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  orderId: FundedPlaceTakeProfitInstructionDataArgs["orderId"];
  triggerPrice: FundedPlaceTakeProfitInstructionDataArgs["triggerPrice"];
  sizeBase: FundedPlaceTakeProfitInstructionDataArgs["sizeBase"];
};

export async function getFundedPlaceTakeProfitInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountTriggerOrder extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountSystemProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedPlaceTakeProfitAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTriggerOrder,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountSystemProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  FundedPlaceTakeProfitInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTriggerOrder,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountSystemProgram,
    TAccountSolfxCoreProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: false },
    market: { value: input.market ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.triggerOrder),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedPlaceTakeProfitInstructionDataEncoder().encode(
      args as FundedPlaceTakeProfitInstructionDataArgs,
    ),
    programAddress,
  } as FundedPlaceTakeProfitInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTriggerOrder,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountSystemProgram,
    TAccountSolfxCoreProgram
  >);
}

export type FundedPlaceTakeProfitInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  /**
   * Pays the transaction fee. Pays no rent: the trigger's rent comes from the mandate signer,
   * and comes back to it on a cancel.
   */
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  /** The SolFX authority: dataless, system-owned, signs the CPI and pays the trigger's rent. */
  mandateSigner: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  /** this program can sign for. Not deserialized — this instruction prices nothing. */
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  /**
   * Read-only: `place_trigger_order` reads the position's size, direction and opening slot
   * and writes none of them. An unnecessary write lock would serialise this against a close
   * on the same position for no reason.
   */
  position: Address<TAccountPosition>;
  /**
   * the mandate signer. An `order_id` already in use fails there as "account already in use",
   * which is how a take-profit is prevented from ever overwriting the trade's stop.
   */
  triggerOrder: Address<TAccountTriggerOrder>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  systemProgram?: Address<TAccountSystemProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  orderId: FundedPlaceTakeProfitInstructionDataArgs["orderId"];
  triggerPrice: FundedPlaceTakeProfitInstructionDataArgs["triggerPrice"];
  sizeBase: FundedPlaceTakeProfitInstructionDataArgs["sizeBase"];
};

export function getFundedPlaceTakeProfitInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountTriggerOrder extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountSystemProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedPlaceTakeProfitInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTriggerOrder,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountSystemProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): FundedPlaceTakeProfitInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountProtocol,
  TAccountUserAccount,
  TAccountMarket,
  TAccountPosition,
  TAccountTriggerOrder,
  TAccountPriceUpdate,
  TAccountSecondaryPriceUpdate,
  TAccountQuoteConversionPriceUpdate,
  TAccountSystemProgram,
  TAccountSolfxCoreProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: false },
    market: { value: input.market ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.triggerOrder),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedPlaceTakeProfitInstructionDataEncoder().encode(
      args as FundedPlaceTakeProfitInstructionDataArgs,
    ),
    programAddress,
  } as FundedPlaceTakeProfitInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTriggerOrder,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountSystemProgram,
    TAccountSolfxCoreProgram
  >);
}

export type ParsedFundedPlaceTakeProfitInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /**
     * Pays the transaction fee. Pays no rent: the trigger's rent comes from the mandate signer,
     * and comes back to it on a cancel.
     */
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    /** The SolFX authority: dataless, system-owned, signs the CPI and pays the trigger's rent. */
    mandateSigner: TAccountMetas[3];
    protocol: TAccountMetas[4];
    /** this program can sign for. Not deserialized — this instruction prices nothing. */
    userAccount: TAccountMetas[5];
    market: TAccountMetas[6];
    /**
     * Read-only: `place_trigger_order` reads the position's size, direction and opening slot
     * and writes none of them. An unnecessary write lock would serialise this against a close
     * on the same position for no reason.
     */
    position: TAccountMetas[7];
    /**
     * the mandate signer. An `order_id` already in use fails there as "account already in use",
     * which is how a take-profit is prevented from ever overwriting the trade's stop.
     */
    triggerOrder: TAccountMetas[8];
    priceUpdate: TAccountMetas[9];
    secondaryPriceUpdate?: TAccountMetas[10] | undefined;
    quoteConversionPriceUpdate?: TAccountMetas[11] | undefined;
    systemProgram: TAccountMetas[12];
    solfxCoreProgram: TAccountMetas[13];
  };
  data: FundedPlaceTakeProfitInstructionData;
};

export function parseFundedPlaceTakeProfitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundedPlaceTakeProfitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === NOXFUNDS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      protocol: getNextAccount(),
      userAccount: getNextAccount(),
      market: getNextAccount(),
      position: getNextAccount(),
      triggerOrder: getNextAccount(),
      priceUpdate: getNextAccount(),
      secondaryPriceUpdate: getNextOptionalAccount(),
      quoteConversionPriceUpdate: getNextOptionalAccount(),
      systemProgram: getNextAccount(),
      solfxCoreProgram: getNextAccount(),
    },
    data: getFundedPlaceTakeProfitInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
