/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getDirectionDecoder,
  getDirectionEncoder,
  getEntryKindDecoder,
  getEntryKindEncoder,
  type Direction,
  type DirectionArgs,
  type EntryKind,
  type EntryKindArgs,
} from "../types";

export const FUNDED_PLACE_ENTRY_ORDER_DISCRIMINATOR = new Uint8Array([
  74, 137, 151, 94, 196, 254, 222, 24,
]);

export function getFundedPlaceEntryOrderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDED_PLACE_ENTRY_ORDER_DISCRIMINATOR,
  );
}

export type FundedPlaceEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountEntryOrder extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? ReadonlyAccount<TAccountMandate>
        : TAccountMandate,
      TAccountEntryOrder extends string
        ? WritableAccount<TAccountEntryOrder>
        : TAccountEntryOrder,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type FundedPlaceEntryOrderInstructionData = {
  discriminator: ReadonlyUint8Array;
  orderId: number;
  marketIndex: number;
  /** The SolFX position nonce it opens at. */
  nonce: number;
  /** The trigger order id the stop takes when it fills. */
  stopOrderId: number;
  direction: Direction;
  kind: EntryKind;
  triggerPrice: bigint;
  /**
   * The fill bound handed to `open_position` — a maximum for a buy, a minimum for a sell.
   * A limit's bound may be no worse than its trigger; a stop's no better.
   */
  priceLimit: bigint;
  sizeBase: bigint;
  collateral: bigint;
  stopLossPrice: bigint;
  /** Zero: good until cancelled. */
  expiresAt: bigint;
};

export type FundedPlaceEntryOrderInstructionDataArgs = {
  orderId: number;
  marketIndex: number;
  /** The SolFX position nonce it opens at. */
  nonce: number;
  /** The trigger order id the stop takes when it fills. */
  stopOrderId: number;
  direction: DirectionArgs;
  kind: EntryKindArgs;
  triggerPrice: number | bigint;
  /**
   * The fill bound handed to `open_position` — a maximum for a buy, a minimum for a sell.
   * A limit's bound may be no worse than its trigger; a stop's no better.
   */
  priceLimit: number | bigint;
  sizeBase: number | bigint;
  collateral: number | bigint;
  stopLossPrice: number | bigint;
  /** Zero: good until cancelled. */
  expiresAt: number | bigint;
};

export function getFundedPlaceEntryOrderInstructionDataEncoder(): FixedSizeEncoder<FundedPlaceEntryOrderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["orderId", getU8Encoder()],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["stopOrderId", getU8Encoder()],
      ["direction", getDirectionEncoder()],
      ["kind", getEntryKindEncoder()],
      ["triggerPrice", getI64Encoder()],
      ["priceLimit", getI64Encoder()],
      ["sizeBase", getU64Encoder()],
      ["collateral", getU64Encoder()],
      ["stopLossPrice", getI64Encoder()],
      ["expiresAt", getI64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: FUNDED_PLACE_ENTRY_ORDER_DISCRIMINATOR,
    }),
  );
}

export function getFundedPlaceEntryOrderInstructionDataDecoder(): FixedSizeDecoder<FundedPlaceEntryOrderInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["orderId", getU8Decoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["stopOrderId", getU8Decoder()],
    ["direction", getDirectionDecoder()],
    ["kind", getEntryKindDecoder()],
    ["triggerPrice", getI64Decoder()],
    ["priceLimit", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
    ["collateral", getU64Decoder()],
    ["stopLossPrice", getI64Decoder()],
    ["expiresAt", getI64Decoder()],
  ]);
}

export function getFundedPlaceEntryOrderInstructionDataCodec(): FixedSizeCodec<
  FundedPlaceEntryOrderInstructionDataArgs,
  FundedPlaceEntryOrderInstructionData
> {
  return combineCodec(
    getFundedPlaceEntryOrderInstructionDataEncoder(),
    getFundedPlaceEntryOrderInstructionDataDecoder(),
  );
}

export type FundedPlaceEntryOrderAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountEntryOrder extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  entryOrder: Address<TAccountEntryOrder>;
  systemProgram?: Address<TAccountSystemProgram>;
  orderId: FundedPlaceEntryOrderInstructionDataArgs["orderId"];
  marketIndex: FundedPlaceEntryOrderInstructionDataArgs["marketIndex"];
  nonce: FundedPlaceEntryOrderInstructionDataArgs["nonce"];
  stopOrderId: FundedPlaceEntryOrderInstructionDataArgs["stopOrderId"];
  direction: FundedPlaceEntryOrderInstructionDataArgs["direction"];
  kind: FundedPlaceEntryOrderInstructionDataArgs["kind"];
  triggerPrice: FundedPlaceEntryOrderInstructionDataArgs["triggerPrice"];
  priceLimit: FundedPlaceEntryOrderInstructionDataArgs["priceLimit"];
  sizeBase: FundedPlaceEntryOrderInstructionDataArgs["sizeBase"];
  collateral: FundedPlaceEntryOrderInstructionDataArgs["collateral"];
  stopLossPrice: FundedPlaceEntryOrderInstructionDataArgs["stopLossPrice"];
  expiresAt: FundedPlaceEntryOrderInstructionDataArgs["expiresAt"];
};

export async function getFundedPlaceEntryOrderInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountEntryOrder extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedPlaceEntryOrderAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountEntryOrder,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  FundedPlaceEntryOrderInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountEntryOrder,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    entryOrder: { value: input.entryOrder ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.entryOrder),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getFundedPlaceEntryOrderInstructionDataEncoder().encode(
      args as FundedPlaceEntryOrderInstructionDataArgs,
    ),
    programAddress,
  } as FundedPlaceEntryOrderInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountEntryOrder,
    TAccountSystemProgram
  >);
}

export type FundedPlaceEntryOrderInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountEntryOrder extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  entryOrder: Address<TAccountEntryOrder>;
  systemProgram?: Address<TAccountSystemProgram>;
  orderId: FundedPlaceEntryOrderInstructionDataArgs["orderId"];
  marketIndex: FundedPlaceEntryOrderInstructionDataArgs["marketIndex"];
  nonce: FundedPlaceEntryOrderInstructionDataArgs["nonce"];
  stopOrderId: FundedPlaceEntryOrderInstructionDataArgs["stopOrderId"];
  direction: FundedPlaceEntryOrderInstructionDataArgs["direction"];
  kind: FundedPlaceEntryOrderInstructionDataArgs["kind"];
  triggerPrice: FundedPlaceEntryOrderInstructionDataArgs["triggerPrice"];
  priceLimit: FundedPlaceEntryOrderInstructionDataArgs["priceLimit"];
  sizeBase: FundedPlaceEntryOrderInstructionDataArgs["sizeBase"];
  collateral: FundedPlaceEntryOrderInstructionDataArgs["collateral"];
  stopLossPrice: FundedPlaceEntryOrderInstructionDataArgs["stopLossPrice"];
  expiresAt: FundedPlaceEntryOrderInstructionDataArgs["expiresAt"];
};

export function getFundedPlaceEntryOrderInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountEntryOrder extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedPlaceEntryOrderInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountEntryOrder,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): FundedPlaceEntryOrderInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountMandate,
  TAccountEntryOrder,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    entryOrder: { value: input.entryOrder ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.entryOrder),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getFundedPlaceEntryOrderInstructionDataEncoder().encode(
      args as FundedPlaceEntryOrderInstructionDataArgs,
    ),
    programAddress,
  } as FundedPlaceEntryOrderInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountEntryOrder,
    TAccountSystemProgram
  >);
}

export type ParsedFundedPlaceEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    entryOrder: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: FundedPlaceEntryOrderInstructionData;
};

export function parseFundedPlaceEntryOrderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundedPlaceEntryOrderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      entryOrder: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getFundedPlaceEntryOrderInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
