/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const FUNDED_CANCEL_ENTRY_ORDER_DISCRIMINATOR = new Uint8Array([
  65, 245, 58, 157, 218, 148, 70, 100,
]);

export function getFundedCancelEntryOrderDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDED_CANCEL_ENTRY_ORDER_DISCRIMINATOR,
  );
}

export type FundedCancelEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountEntryOrder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTrader extends string
        ? WritableAccount<TAccountTrader>
        : TAccountTrader,
      TAccountMandate extends string
        ? ReadonlyAccount<TAccountMandate>
        : TAccountMandate,
      TAccountEntryOrder extends string
        ? WritableAccount<TAccountEntryOrder>
        : TAccountEntryOrder,
      ...TRemainingAccounts,
    ]
  >;

export type FundedCancelEntryOrderInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type FundedCancelEntryOrderInstructionDataArgs = {};

export function getFundedCancelEntryOrderInstructionDataEncoder(): FixedSizeEncoder<FundedCancelEntryOrderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: FUNDED_CANCEL_ENTRY_ORDER_DISCRIMINATOR,
    }),
  );
}

export function getFundedCancelEntryOrderInstructionDataDecoder(): FixedSizeDecoder<FundedCancelEntryOrderInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getFundedCancelEntryOrderInstructionDataCodec(): FixedSizeCodec<
  FundedCancelEntryOrderInstructionDataArgs,
  FundedCancelEntryOrderInstructionData
> {
  return combineCodec(
    getFundedCancelEntryOrderInstructionDataEncoder(),
    getFundedCancelEntryOrderInstructionDataDecoder(),
  );
}

export type FundedCancelEntryOrderInput<
  TAccountCaller extends string = string,
  TAccountTrader extends string = string,
  TAccountMandate extends string = string,
  TAccountEntryOrder extends string = string,
> = {
  /** The trader at any time; anyone once the order can no longer fill. */
  caller: TransactionSigner<TAccountCaller>;
  trader: Address<TAccountTrader>;
  mandate: Address<TAccountMandate>;
  entryOrder: Address<TAccountEntryOrder>;
};

export function getFundedCancelEntryOrderInstruction<
  TAccountCaller extends string,
  TAccountTrader extends string,
  TAccountMandate extends string,
  TAccountEntryOrder extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedCancelEntryOrderInput<
    TAccountCaller,
    TAccountTrader,
    TAccountMandate,
    TAccountEntryOrder
  >,
  config?: { programAddress?: TProgramAddress },
): FundedCancelEntryOrderInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTrader,
  TAccountMandate,
  TAccountEntryOrder
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    trader: { value: input.trader ?? null, isWritable: true },
    mandate: { value: input.mandate ?? null, isWritable: false },
    entryOrder: { value: input.entryOrder ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.entryOrder),
    ],
    data: getFundedCancelEntryOrderInstructionDataEncoder().encode({}),
    programAddress,
  } as FundedCancelEntryOrderInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTrader,
    TAccountMandate,
    TAccountEntryOrder
  >);
}

export type ParsedFundedCancelEntryOrderInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The trader at any time; anyone once the order can no longer fill. */
    caller: TAccountMetas[0];
    trader: TAccountMetas[1];
    mandate: TAccountMetas[2];
    entryOrder: TAccountMetas[3];
  };
  data: FundedCancelEntryOrderInstructionData;
};

export function parseFundedCancelEntryOrderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundedCancelEntryOrderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      trader: getNextAccount(),
      mandate: getNextAccount(),
      entryOrder: getNextAccount(),
    },
    data: getFundedCancelEntryOrderInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
