/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  findConfigPda,
  findMandateSignerPda,
  findMandateVaultPda,
} from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const FUND_SOLFX_COLLATERAL_DISCRIMINATOR = new Uint8Array([
  29, 23, 27, 204, 167, 94, 187, 211,
]);

export function getFundSolfxCollateralDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUND_SOLFX_COLLATERAL_DISCRIMINATOR,
  );
}

export type FundSolfxCollateralInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountProtocol extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountCollateralMint extends string | AccountMeta<string> = string,
  TAccountCollateralVault extends string | AccountMeta<string> = string,
  TAccountMandateVault extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSolfxCoreProgram extends string | AccountMeta<string> =
    "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? ReadonlyAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountProtocol extends string
        ? WritableAccount<TAccountProtocol>
        : TAccountProtocol,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountCollateralMint extends string
        ? WritableAccount<TAccountCollateralMint>
        : TAccountCollateralMint,
      TAccountCollateralVault extends string
        ? WritableAccount<TAccountCollateralVault>
        : TAccountCollateralVault,
      TAccountMandateVault extends string
        ? WritableAccount<TAccountMandateVault>
        : TAccountMandateVault,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSolfxCoreProgram extends string
        ? ReadonlyAccount<TAccountSolfxCoreProgram>
        : TAccountSolfxCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type FundSolfxCollateralInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type FundSolfxCollateralInstructionDataArgs = {
  amount: number | bigint;
};

export function getFundSolfxCollateralInstructionDataEncoder(): FixedSizeEncoder<FundSolfxCollateralInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: FUND_SOLFX_COLLATERAL_DISCRIMINATOR,
    }),
  );
}

export function getFundSolfxCollateralInstructionDataDecoder(): FixedSizeDecoder<FundSolfxCollateralInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getFundSolfxCollateralInstructionDataCodec(): FixedSizeCodec<
  FundSolfxCollateralInstructionDataArgs,
  FundSolfxCollateralInstructionData
> {
  return combineCodec(
    getFundSolfxCollateralInstructionDataEncoder(),
    getFundSolfxCollateralInstructionDataDecoder(),
  );
}

export type FundSolfxCollateralAsyncInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountMandateVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner?: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  userAccount: Address<TAccountUserAccount>;
  collateralMint: Address<TAccountCollateralMint>;
  collateralVault: Address<TAccountCollateralVault>;
  mandateVault?: Address<TAccountMandateVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  amount: FundSolfxCollateralInstructionDataArgs["amount"];
};

export async function getFundSolfxCollateralInstructionAsync<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountCollateralMint extends string,
  TAccountCollateralVault extends string,
  TAccountMandateVault extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundSolfxCollateralAsyncInput<
    TAccountPayer,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountCollateralMint,
    TAccountCollateralVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  FundSolfxCollateralInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountCollateralMint,
    TAccountCollateralVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    mandateVault: { value: input.mandateVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.mandateVault.value) {
    accounts.mandateVault.value = await findMandateVaultPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.mandateVault),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundSolfxCollateralInstructionDataEncoder().encode(
      args as FundSolfxCollateralInstructionDataArgs,
    ),
    programAddress,
  } as FundSolfxCollateralInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountCollateralMint,
    TAccountCollateralVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type FundSolfxCollateralInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountCollateralMint extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountMandateVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  userAccount: Address<TAccountUserAccount>;
  collateralMint: Address<TAccountCollateralMint>;
  collateralVault: Address<TAccountCollateralVault>;
  mandateVault: Address<TAccountMandateVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  amount: FundSolfxCollateralInstructionDataArgs["amount"];
};

export function getFundSolfxCollateralInstruction<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountCollateralMint extends string,
  TAccountCollateralVault extends string,
  TAccountMandateVault extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundSolfxCollateralInput<
    TAccountPayer,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountCollateralMint,
    TAccountCollateralVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): FundSolfxCollateralInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountConfig,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountProtocol,
  TAccountUserAccount,
  TAccountCollateralMint,
  TAccountCollateralVault,
  TAccountMandateVault,
  TAccountTokenProgram,
  TAccountSolfxCoreProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    collateralMint: { value: input.collateralMint ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    mandateVault: { value: input.mandateVault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.collateralMint),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.mandateVault),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundSolfxCollateralInstructionDataEncoder().encode(
      args as FundSolfxCollateralInstructionDataArgs,
    ),
    programAddress,
  } as FundSolfxCollateralInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountCollateralMint,
    TAccountCollateralVault,
    TAccountMandateVault,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type ParsedFundSolfxCollateralInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    mandateSigner: TAccountMetas[3];
    protocol: TAccountMetas[4];
    userAccount: TAccountMetas[5];
    collateralMint: TAccountMetas[6];
    collateralVault: TAccountMetas[7];
    mandateVault: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    solfxCoreProgram: TAccountMetas[10];
  };
  data: FundSolfxCollateralInstructionData;
};

export function parseFundSolfxCollateralInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundSolfxCollateralInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      protocol: getNextAccount(),
      userAccount: getNextAccount(),
      collateralMint: getNextAccount(),
      collateralVault: getNextAccount(),
      mandateVault: getNextAccount(),
      tokenProgram: getNextAccount(),
      solfxCoreProgram: getNextAccount(),
    },
    data: getFundSolfxCollateralInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
