/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findMandateSignerPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const FUNDED_CLOSE_POSITION_DISCRIMINATOR = new Uint8Array([
  227, 179, 83, 193, 193, 251, 156, 231,
]);

export function getFundedClosePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDED_CLOSE_POSITION_DISCRIMINATOR,
  );
}

export type FundedClosePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountProtocol extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountTraderProfile extends string | AccountMeta<string> = string,
  TAccountCollateralVault extends string | AccountMeta<string> = string,
  TAccountLpPool extends string | AccountMeta<string> = string,
  TAccountLpVault extends string | AccountMeta<string> = string,
  TAccountInsuranceFund extends string | AccountMeta<string> = string,
  TAccountInsuranceVault extends string | AccountMeta<string> = string,
  TAccountFeeVault extends string | AccountMeta<string> = string,
  TAccountPriceUpdate extends string | AccountMeta<string> = string,
  TAccountSecondaryPriceUpdate extends string | AccountMeta<string> = string,
  TAccountQuoteConversionPriceUpdate extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSolfxCoreProgram extends string | AccountMeta<string> =
    "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? WritableAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountProtocol extends string
        ? WritableAccount<TAccountProtocol>
        : TAccountProtocol,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountTraderProfile extends string
        ? WritableAccount<TAccountTraderProfile>
        : TAccountTraderProfile,
      TAccountCollateralVault extends string
        ? WritableAccount<TAccountCollateralVault>
        : TAccountCollateralVault,
      TAccountLpPool extends string
        ? WritableAccount<TAccountLpPool>
        : TAccountLpPool,
      TAccountLpVault extends string
        ? WritableAccount<TAccountLpVault>
        : TAccountLpVault,
      TAccountInsuranceFund extends string
        ? WritableAccount<TAccountInsuranceFund>
        : TAccountInsuranceFund,
      TAccountInsuranceVault extends string
        ? WritableAccount<TAccountInsuranceVault>
        : TAccountInsuranceVault,
      TAccountFeeVault extends string
        ? WritableAccount<TAccountFeeVault>
        : TAccountFeeVault,
      TAccountPriceUpdate extends string
        ? ReadonlyAccount<TAccountPriceUpdate>
        : TAccountPriceUpdate,
      TAccountSecondaryPriceUpdate extends string
        ? ReadonlyAccount<TAccountSecondaryPriceUpdate>
        : TAccountSecondaryPriceUpdate,
      TAccountQuoteConversionPriceUpdate extends string
        ? ReadonlyAccount<TAccountQuoteConversionPriceUpdate>
        : TAccountQuoteConversionPriceUpdate,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSolfxCoreProgram extends string
        ? ReadonlyAccount<TAccountSolfxCoreProgram>
        : TAccountSolfxCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type FundedClosePositionInstructionData = {
  discriminator: ReadonlyUint8Array;
  marketIndex: number;
  nonce: number;
  priceLimit: bigint;
};

export type FundedClosePositionInstructionDataArgs = {
  marketIndex: number;
  nonce: number;
  priceLimit: number | bigint;
};

export function getFundedClosePositionInstructionDataEncoder(): FixedSizeEncoder<FundedClosePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["priceLimit", getI64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: FUNDED_CLOSE_POSITION_DISCRIMINATOR,
    }),
  );
}

export function getFundedClosePositionInstructionDataDecoder(): FixedSizeDecoder<FundedClosePositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["priceLimit", getI64Decoder()],
  ]);
}

export function getFundedClosePositionInstructionDataCodec(): FixedSizeCodec<
  FundedClosePositionInstructionDataArgs,
  FundedClosePositionInstructionData
> {
  return combineCodec(
    getFundedClosePositionInstructionDataEncoder(),
    getFundedClosePositionInstructionDataDecoder(),
  );
}

export type FundedClosePositionAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountLpPool extends string = string,
  TAccountLpVault extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountInsuranceVault extends string = string,
  TAccountFeeVault extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner?: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  position: Address<TAccountPosition>;
  traderProfile: Address<TAccountTraderProfile>;
  collateralVault: Address<TAccountCollateralVault>;
  lpPool: Address<TAccountLpPool>;
  lpVault: Address<TAccountLpVault>;
  insuranceFund: Address<TAccountInsuranceFund>;
  insuranceVault: Address<TAccountInsuranceVault>;
  feeVault: Address<TAccountFeeVault>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  marketIndex: FundedClosePositionInstructionDataArgs["marketIndex"];
  nonce: FundedClosePositionInstructionDataArgs["nonce"];
  priceLimit: FundedClosePositionInstructionDataArgs["priceLimit"];
};

export async function getFundedClosePositionInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountTraderProfile extends string,
  TAccountCollateralVault extends string,
  TAccountLpPool extends string,
  TAccountLpVault extends string,
  TAccountInsuranceFund extends string,
  TAccountInsuranceVault extends string,
  TAccountFeeVault extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedClosePositionAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTraderProfile,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  FundedClosePositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTraderProfile,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    traderProfile: { value: input.traderProfile ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    lpPool: { value: input.lpPool ?? null, isWritable: true },
    lpVault: { value: input.lpVault ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    insuranceVault: { value: input.insuranceVault ?? null, isWritable: true },
    feeVault: { value: input.feeVault ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.lpPool),
      getAccountMeta(accounts.lpVault),
      getAccountMeta(accounts.insuranceFund),
      getAccountMeta(accounts.insuranceVault),
      getAccountMeta(accounts.feeVault),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedClosePositionInstructionDataEncoder().encode(
      args as FundedClosePositionInstructionDataArgs,
    ),
    programAddress,
  } as FundedClosePositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTraderProfile,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type FundedClosePositionInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountLpPool extends string = string,
  TAccountLpVault extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountInsuranceVault extends string = string,
  TAccountFeeVault extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  position: Address<TAccountPosition>;
  traderProfile: Address<TAccountTraderProfile>;
  collateralVault: Address<TAccountCollateralVault>;
  lpPool: Address<TAccountLpPool>;
  lpVault: Address<TAccountLpVault>;
  insuranceFund: Address<TAccountInsuranceFund>;
  insuranceVault: Address<TAccountInsuranceVault>;
  feeVault: Address<TAccountFeeVault>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  marketIndex: FundedClosePositionInstructionDataArgs["marketIndex"];
  nonce: FundedClosePositionInstructionDataArgs["nonce"];
  priceLimit: FundedClosePositionInstructionDataArgs["priceLimit"];
};

export function getFundedClosePositionInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountTraderProfile extends string,
  TAccountCollateralVault extends string,
  TAccountLpPool extends string,
  TAccountLpVault extends string,
  TAccountInsuranceFund extends string,
  TAccountInsuranceVault extends string,
  TAccountFeeVault extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedClosePositionInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTraderProfile,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): FundedClosePositionInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountProtocol,
  TAccountUserAccount,
  TAccountMarket,
  TAccountPosition,
  TAccountTraderProfile,
  TAccountCollateralVault,
  TAccountLpPool,
  TAccountLpVault,
  TAccountInsuranceFund,
  TAccountInsuranceVault,
  TAccountFeeVault,
  TAccountPriceUpdate,
  TAccountSecondaryPriceUpdate,
  TAccountQuoteConversionPriceUpdate,
  TAccountTokenProgram,
  TAccountSolfxCoreProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    traderProfile: { value: input.traderProfile ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    lpPool: { value: input.lpPool ?? null, isWritable: true },
    lpVault: { value: input.lpVault ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    insuranceVault: { value: input.insuranceVault ?? null, isWritable: true },
    feeVault: { value: input.feeVault ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.lpPool),
      getAccountMeta(accounts.lpVault),
      getAccountMeta(accounts.insuranceFund),
      getAccountMeta(accounts.insuranceVault),
      getAccountMeta(accounts.feeVault),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedClosePositionInstructionDataEncoder().encode(
      args as FundedClosePositionInstructionDataArgs,
    ),
    programAddress,
  } as FundedClosePositionInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountTraderProfile,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type ParsedFundedClosePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    mandateSigner: TAccountMetas[3];
    protocol: TAccountMetas[4];
    userAccount: TAccountMetas[5];
    market: TAccountMetas[6];
    position: TAccountMetas[7];
    traderProfile: TAccountMetas[8];
    collateralVault: TAccountMetas[9];
    lpPool: TAccountMetas[10];
    lpVault: TAccountMetas[11];
    insuranceFund: TAccountMetas[12];
    insuranceVault: TAccountMetas[13];
    feeVault: TAccountMetas[14];
    priceUpdate: TAccountMetas[15];
    secondaryPriceUpdate?: TAccountMetas[16] | undefined;
    quoteConversionPriceUpdate?: TAccountMetas[17] | undefined;
    tokenProgram: TAccountMetas[18];
    solfxCoreProgram: TAccountMetas[19];
  };
  data: FundedClosePositionInstructionData;
};

export function parseFundedClosePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundedClosePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 20) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === NOXFUNDS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      protocol: getNextAccount(),
      userAccount: getNextAccount(),
      market: getNextAccount(),
      position: getNextAccount(),
      traderProfile: getNextAccount(),
      collateralVault: getNextAccount(),
      lpPool: getNextAccount(),
      lpVault: getNextAccount(),
      insuranceFund: getNextAccount(),
      insuranceVault: getNextAccount(),
      feeVault: getNextAccount(),
      priceUpdate: getNextAccount(),
      secondaryPriceUpdate: getNextOptionalAccount(),
      quoteConversionPriceUpdate: getNextOptionalAccount(),
      tokenProgram: getNextAccount(),
      solfxCoreProgram: getNextAccount(),
    },
    data: getFundedClosePositionInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
