/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findMandateSignerPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const FUNDED_ADD_MARGIN_DISCRIMINATOR = new Uint8Array([
  181, 238, 106, 184, 181, 71, 190, 177,
]);

export function getFundedAddMarginDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FUNDED_ADD_MARGIN_DISCRIMINATOR,
  );
}

export type FundedAddMarginInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountProtocol extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCollateralVault extends string | AccountMeta<string> = string,
  TAccountLpPool extends string | AccountMeta<string> = string,
  TAccountLpVault extends string | AccountMeta<string> = string,
  TAccountInsuranceFund extends string | AccountMeta<string> = string,
  TAccountInsuranceVault extends string | AccountMeta<string> = string,
  TAccountFeeVault extends string | AccountMeta<string> = string,
  TAccountPriceUpdate extends string | AccountMeta<string> = string,
  TAccountSecondaryPriceUpdate extends string | AccountMeta<string> = string,
  TAccountQuoteConversionPriceUpdate extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSolfxCoreProgram extends string | AccountMeta<string> =
    "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? WritableAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountProtocol extends string
        ? WritableAccount<TAccountProtocol>
        : TAccountProtocol,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCollateralVault extends string
        ? WritableAccount<TAccountCollateralVault>
        : TAccountCollateralVault,
      TAccountLpPool extends string
        ? WritableAccount<TAccountLpPool>
        : TAccountLpPool,
      TAccountLpVault extends string
        ? WritableAccount<TAccountLpVault>
        : TAccountLpVault,
      TAccountInsuranceFund extends string
        ? WritableAccount<TAccountInsuranceFund>
        : TAccountInsuranceFund,
      TAccountInsuranceVault extends string
        ? WritableAccount<TAccountInsuranceVault>
        : TAccountInsuranceVault,
      TAccountFeeVault extends string
        ? WritableAccount<TAccountFeeVault>
        : TAccountFeeVault,
      TAccountPriceUpdate extends string
        ? ReadonlyAccount<TAccountPriceUpdate>
        : TAccountPriceUpdate,
      TAccountSecondaryPriceUpdate extends string
        ? ReadonlyAccount<TAccountSecondaryPriceUpdate>
        : TAccountSecondaryPriceUpdate,
      TAccountQuoteConversionPriceUpdate extends string
        ? ReadonlyAccount<TAccountQuoteConversionPriceUpdate>
        : TAccountQuoteConversionPriceUpdate,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSolfxCoreProgram extends string
        ? ReadonlyAccount<TAccountSolfxCoreProgram>
        : TAccountSolfxCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type FundedAddMarginInstructionData = {
  discriminator: ReadonlyUint8Array;
  marketIndex: number;
  nonce: number;
  amount: bigint;
};

export type FundedAddMarginInstructionDataArgs = {
  marketIndex: number;
  nonce: number;
  amount: number | bigint;
};

export function getFundedAddMarginInstructionDataEncoder(): FixedSizeEncoder<FundedAddMarginInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["marketIndex", getU16Encoder()],
      ["nonce", getU8Encoder()],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: FUNDED_ADD_MARGIN_DISCRIMINATOR }),
  );
}

export function getFundedAddMarginInstructionDataDecoder(): FixedSizeDecoder<FundedAddMarginInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getFundedAddMarginInstructionDataCodec(): FixedSizeCodec<
  FundedAddMarginInstructionDataArgs,
  FundedAddMarginInstructionData
> {
  return combineCodec(
    getFundedAddMarginInstructionDataEncoder(),
    getFundedAddMarginInstructionDataDecoder(),
  );
}

export type FundedAddMarginAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountLpPool extends string = string,
  TAccountLpVault extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountInsuranceVault extends string = string,
  TAccountFeeVault extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner?: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  /**
   * Deserialized and reloaded after the CPI: the change in its free collateral is the amount
   * that moved. `solfx-core` owns it, so Anchor never writes it back.
   */
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  /**
   * Deserialized so the position named is the position adjusted; `solfx-core` checks it
   * belongs to `user_account`.
   */
  position: Address<TAccountPosition>;
  collateralVault: Address<TAccountCollateralVault>;
  lpPool: Address<TAccountLpPool>;
  lpVault: Address<TAccountLpVault>;
  insuranceFund: Address<TAccountInsuranceFund>;
  insuranceVault: Address<TAccountInsuranceVault>;
  feeVault: Address<TAccountFeeVault>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  marketIndex: FundedAddMarginInstructionDataArgs["marketIndex"];
  nonce: FundedAddMarginInstructionDataArgs["nonce"];
  amount: FundedAddMarginInstructionDataArgs["amount"];
};

export async function getFundedAddMarginInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountCollateralVault extends string,
  TAccountLpPool extends string,
  TAccountLpVault extends string,
  TAccountInsuranceFund extends string,
  TAccountInsuranceVault extends string,
  TAccountFeeVault extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedAddMarginAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  FundedAddMarginInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    lpPool: { value: input.lpPool ?? null, isWritable: true },
    lpVault: { value: input.lpVault ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    insuranceVault: { value: input.insuranceVault ?? null, isWritable: true },
    feeVault: { value: input.feeVault ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.lpPool),
      getAccountMeta(accounts.lpVault),
      getAccountMeta(accounts.insuranceFund),
      getAccountMeta(accounts.insuranceVault),
      getAccountMeta(accounts.feeVault),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedAddMarginInstructionDataEncoder().encode(
      args as FundedAddMarginInstructionDataArgs,
    ),
    programAddress,
  } as FundedAddMarginInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type FundedAddMarginInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountProtocol extends string = string,
  TAccountUserAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountPosition extends string = string,
  TAccountCollateralVault extends string = string,
  TAccountLpPool extends string = string,
  TAccountLpVault extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountInsuranceVault extends string = string,
  TAccountFeeVault extends string = string,
  TAccountPriceUpdate extends string = string,
  TAccountSecondaryPriceUpdate extends string = string,
  TAccountQuoteConversionPriceUpdate extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner: Address<TAccountMandateSigner>;
  protocol: Address<TAccountProtocol>;
  /**
   * Deserialized and reloaded after the CPI: the change in its free collateral is the amount
   * that moved. `solfx-core` owns it, so Anchor never writes it back.
   */
  userAccount: Address<TAccountUserAccount>;
  market: Address<TAccountMarket>;
  /**
   * Deserialized so the position named is the position adjusted; `solfx-core` checks it
   * belongs to `user_account`.
   */
  position: Address<TAccountPosition>;
  collateralVault: Address<TAccountCollateralVault>;
  lpPool: Address<TAccountLpPool>;
  lpVault: Address<TAccountLpVault>;
  insuranceFund: Address<TAccountInsuranceFund>;
  insuranceVault: Address<TAccountInsuranceVault>;
  feeVault: Address<TAccountFeeVault>;
  priceUpdate: Address<TAccountPriceUpdate>;
  secondaryPriceUpdate?: Address<TAccountSecondaryPriceUpdate>;
  quoteConversionPriceUpdate?: Address<TAccountQuoteConversionPriceUpdate>;
  tokenProgram?: Address<TAccountTokenProgram>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
  marketIndex: FundedAddMarginInstructionDataArgs["marketIndex"];
  nonce: FundedAddMarginInstructionDataArgs["nonce"];
  amount: FundedAddMarginInstructionDataArgs["amount"];
};

export function getFundedAddMarginInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountProtocol extends string,
  TAccountUserAccount extends string,
  TAccountMarket extends string,
  TAccountPosition extends string,
  TAccountCollateralVault extends string,
  TAccountLpPool extends string,
  TAccountLpVault extends string,
  TAccountInsuranceFund extends string,
  TAccountInsuranceVault extends string,
  TAccountFeeVault extends string,
  TAccountPriceUpdate extends string,
  TAccountSecondaryPriceUpdate extends string,
  TAccountQuoteConversionPriceUpdate extends string,
  TAccountTokenProgram extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: FundedAddMarginInput<
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): FundedAddMarginInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountProtocol,
  TAccountUserAccount,
  TAccountMarket,
  TAccountPosition,
  TAccountCollateralVault,
  TAccountLpPool,
  TAccountLpVault,
  TAccountInsuranceFund,
  TAccountInsuranceVault,
  TAccountFeeVault,
  TAccountPriceUpdate,
  TAccountSecondaryPriceUpdate,
  TAccountQuoteConversionPriceUpdate,
  TAccountTokenProgram,
  TAccountSolfxCoreProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: true },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    protocol: { value: input.protocol ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    collateralVault: { value: input.collateralVault ?? null, isWritable: true },
    lpPool: { value: input.lpPool ?? null, isWritable: true },
    lpVault: { value: input.lpVault ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    insuranceVault: { value: input.insuranceVault ?? null, isWritable: true },
    feeVault: { value: input.feeVault ?? null, isWritable: true },
    priceUpdate: { value: input.priceUpdate ?? null, isWritable: false },
    secondaryPriceUpdate: {
      value: input.secondaryPriceUpdate ?? null,
      isWritable: false,
    },
    quoteConversionPriceUpdate: {
      value: input.quoteConversionPriceUpdate ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.protocol),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.collateralVault),
      getAccountMeta(accounts.lpPool),
      getAccountMeta(accounts.lpVault),
      getAccountMeta(accounts.insuranceFund),
      getAccountMeta(accounts.insuranceVault),
      getAccountMeta(accounts.feeVault),
      getAccountMeta(accounts.priceUpdate),
      getAccountMeta(accounts.secondaryPriceUpdate),
      getAccountMeta(accounts.quoteConversionPriceUpdate),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getFundedAddMarginInstructionDataEncoder().encode(
      args as FundedAddMarginInstructionDataArgs,
    ),
    programAddress,
  } as FundedAddMarginInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountProtocol,
    TAccountUserAccount,
    TAccountMarket,
    TAccountPosition,
    TAccountCollateralVault,
    TAccountLpPool,
    TAccountLpVault,
    TAccountInsuranceFund,
    TAccountInsuranceVault,
    TAccountFeeVault,
    TAccountPriceUpdate,
    TAccountSecondaryPriceUpdate,
    TAccountQuoteConversionPriceUpdate,
    TAccountTokenProgram,
    TAccountSolfxCoreProgram
  >);
}

export type ParsedFundedAddMarginInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    mandateSigner: TAccountMetas[3];
    protocol: TAccountMetas[4];
    /**
     * Deserialized and reloaded after the CPI: the change in its free collateral is the amount
     * that moved. `solfx-core` owns it, so Anchor never writes it back.
     */
    userAccount: TAccountMetas[5];
    market: TAccountMetas[6];
    /**
     * Deserialized so the position named is the position adjusted; `solfx-core` checks it
     * belongs to `user_account`.
     */
    position: TAccountMetas[7];
    collateralVault: TAccountMetas[8];
    lpPool: TAccountMetas[9];
    lpVault: TAccountMetas[10];
    insuranceFund: TAccountMetas[11];
    insuranceVault: TAccountMetas[12];
    feeVault: TAccountMetas[13];
    priceUpdate: TAccountMetas[14];
    secondaryPriceUpdate?: TAccountMetas[15] | undefined;
    quoteConversionPriceUpdate?: TAccountMetas[16] | undefined;
    tokenProgram: TAccountMetas[17];
    solfxCoreProgram: TAccountMetas[18];
  };
  data: FundedAddMarginInstructionData;
};

export function parseFundedAddMarginInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFundedAddMarginInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 19) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === NOXFUNDS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      protocol: getNextAccount(),
      userAccount: getNextAccount(),
      market: getNextAccount(),
      position: getNextAccount(),
      collateralVault: getNextAccount(),
      lpPool: getNextAccount(),
      lpVault: getNextAccount(),
      insuranceFund: getNextAccount(),
      insuranceVault: getNextAccount(),
      feeVault: getNextAccount(),
      priceUpdate: getNextAccount(),
      secondaryPriceUpdate: getNextOptionalAccount(),
      quoteConversionPriceUpdate: getNextOptionalAccount(),
      tokenProgram: getNextAccount(),
      solfxCoreProgram: getNextAccount(),
    },
    data: getFundedAddMarginInstructionDataDecoder().decode(instruction.data),
  };
}
