/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findProfilePda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INITIALIZE_TRADER_PROFILE_DISCRIMINATOR = new Uint8Array([
  195, 249, 92, 96, 42, 151, 172, 99,
]);

export function getInitializeTraderProfileDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_TRADER_PROFILE_DISCRIMINATOR,
  );
}

export type InitializeTraderProfileInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProfile extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlyAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountProfile extends string
        ? WritableAccount<TAccountProfile>
        : TAccountProfile,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeTraderProfileInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type InitializeTraderProfileInstructionDataArgs = {};

export function getInitializeTraderProfileInstructionDataEncoder(): FixedSizeEncoder<InitializeTraderProfileInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_TRADER_PROFILE_DISCRIMINATOR,
    }),
  );
}

export function getInitializeTraderProfileInstructionDataDecoder(): FixedSizeDecoder<InitializeTraderProfileInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getInitializeTraderProfileInstructionDataCodec(): FixedSizeCodec<
  InitializeTraderProfileInstructionDataArgs,
  InitializeTraderProfileInstructionData
> {
  return combineCodec(
    getInitializeTraderProfileInstructionDataEncoder(),
    getInitializeTraderProfileInstructionDataDecoder(),
  );
}

export type InitializeTraderProfileAsyncInput<
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /**
   * Pays the rent. Need not be the trader — an operator or an investor may open a profile
   * for someone, because the profile confers nothing until trades land on it.
   */
  payer: TransactionSigner<TAccountPayer>;
  /** the binding; nothing is read from the account and it signs nothing. */
  authority: Address<TAccountAuthority>;
  profile?: Address<TAccountProfile>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getInitializeTraderProfileInstructionAsync<
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: InitializeTraderProfileAsyncInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeTraderProfileInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProfile,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    profile: { value: input.profile ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.profile.value) {
    accounts.profile.value = await findProfilePda({
      authority: expectAddress(accounts.authority.value),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.profile),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeTraderProfileInstructionDataEncoder().encode({}),
    programAddress,
  } as InitializeTraderProfileInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProfile,
    TAccountSystemProgram
  >);
}

export type InitializeTraderProfileInput<
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /**
   * Pays the rent. Need not be the trader — an operator or an investor may open a profile
   * for someone, because the profile confers nothing until trades land on it.
   */
  payer: TransactionSigner<TAccountPayer>;
  /** the binding; nothing is read from the account and it signs nothing. */
  authority: Address<TAccountAuthority>;
  profile: Address<TAccountProfile>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getInitializeTraderProfileInstruction<
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: InitializeTraderProfileInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeTraderProfileInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountAuthority,
  TAccountProfile,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    profile: { value: input.profile ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.profile),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeTraderProfileInstructionDataEncoder().encode({}),
    programAddress,
  } as InitializeTraderProfileInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProfile,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeTraderProfileInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /**
     * Pays the rent. Need not be the trader — an operator or an investor may open a profile
     * for someone, because the profile confers nothing until trades land on it.
     */
    payer: TAccountMetas[0];
    /** the binding; nothing is read from the account and it signs nothing. */
    authority: TAccountMetas[1];
    profile: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeTraderProfileInstructionData;
};

export function parseInitializeTraderProfileInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeTraderProfileInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      authority: getNextAccount(),
      profile: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeTraderProfileInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
