/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { findConfigPda, findTraderProfilePda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const POST_REQUEST_DISCRIMINATOR = new Uint8Array([
  4, 59, 143, 187, 32, 9, 161, 253,
]);

export function getPostRequestDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POST_REQUEST_DISCRIMINATOR,
  );
}

export type PostRequestInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTraderProfile extends string | AccountMeta<string> = string,
  TAccountInvestorListing extends string | AccountMeta<string> = string,
  TAccountRequest extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? WritableSignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTraderProfile extends string
        ? ReadonlyAccount<TAccountTraderProfile>
        : TAccountTraderProfile,
      TAccountInvestorListing extends string
        ? ReadonlyAccount<TAccountInvestorListing>
        : TAccountInvestorListing,
      TAccountRequest extends string
        ? WritableAccount<TAccountRequest>
        : TAccountRequest,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PostRequestInstructionData = {
  discriminator: ReadonlyUint8Array;
  wantedPrincipal: bigint;
  wantedSplitBps: number;
  note: string;
};

export type PostRequestInstructionDataArgs = {
  wantedPrincipal: number | bigint;
  wantedSplitBps: number;
  note: string;
};

export function getPostRequestInstructionDataEncoder(): Encoder<PostRequestInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["wantedPrincipal", getU64Encoder()],
      ["wantedSplitBps", getU16Encoder()],
      ["note", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: POST_REQUEST_DISCRIMINATOR }),
  );
}

export function getPostRequestInstructionDataDecoder(): Decoder<PostRequestInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["wantedPrincipal", getU64Decoder()],
    ["wantedSplitBps", getU16Decoder()],
    ["note", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getPostRequestInstructionDataCodec(): Codec<
  PostRequestInstructionDataArgs,
  PostRequestInstructionData
> {
  return combineCodec(
    getPostRequestInstructionDataEncoder(),
    getPostRequestInstructionDataDecoder(),
  );
}

export type PostRequestAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountInvestorListing extends string = string,
  TAccountRequest extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  /** Required, so the investor reading the request can read a real track record beside it. */
  traderProfile?: Address<TAccountTraderProfile>;
  /**
   * The investor's listing, which must be open.
   *
   * This is the anti-spam rule. A request can only go to an investor who has publicly said
   * they are looking, so no wallet can be messaged merely for existing — and closing the
   * listing is how an investor shuts the door.
   */
  investorListing: Address<TAccountInvestorListing>;
  /**
   * One open request per pair. The seeds make a duplicate impossible, so a trader cannot
   * flood an inbox with copies of the same ask.
   */
  request: Address<TAccountRequest>;
  systemProgram?: Address<TAccountSystemProgram>;
  wantedPrincipal: PostRequestInstructionDataArgs["wantedPrincipal"];
  wantedSplitBps: PostRequestInstructionDataArgs["wantedSplitBps"];
  note: PostRequestInstructionDataArgs["note"];
};

export async function getPostRequestInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountTraderProfile extends string,
  TAccountInvestorListing extends string,
  TAccountRequest extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: PostRequestAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountTraderProfile,
    TAccountInvestorListing,
    TAccountRequest,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  PostRequestInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountTraderProfile,
    TAccountInvestorListing,
    TAccountRequest,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    traderProfile: { value: input.traderProfile ?? null, isWritable: false },
    investorListing: {
      value: input.investorListing ?? null,
      isWritable: false,
    },
    request: { value: input.request ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.traderProfile.value) {
    accounts.traderProfile.value = await findTraderProfilePda({
      trader: expectAddress(accounts.trader.value),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.investorListing),
      getAccountMeta(accounts.request),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getPostRequestInstructionDataEncoder().encode(
      args as PostRequestInstructionDataArgs,
    ),
    programAddress,
  } as PostRequestInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountTraderProfile,
    TAccountInvestorListing,
    TAccountRequest,
    TAccountSystemProgram
  >);
}

export type PostRequestInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountTraderProfile extends string = string,
  TAccountInvestorListing extends string = string,
  TAccountRequest extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  /** Required, so the investor reading the request can read a real track record beside it. */
  traderProfile: Address<TAccountTraderProfile>;
  /**
   * The investor's listing, which must be open.
   *
   * This is the anti-spam rule. A request can only go to an investor who has publicly said
   * they are looking, so no wallet can be messaged merely for existing — and closing the
   * listing is how an investor shuts the door.
   */
  investorListing: Address<TAccountInvestorListing>;
  /**
   * One open request per pair. The seeds make a duplicate impossible, so a trader cannot
   * flood an inbox with copies of the same ask.
   */
  request: Address<TAccountRequest>;
  systemProgram?: Address<TAccountSystemProgram>;
  wantedPrincipal: PostRequestInstructionDataArgs["wantedPrincipal"];
  wantedSplitBps: PostRequestInstructionDataArgs["wantedSplitBps"];
  note: PostRequestInstructionDataArgs["note"];
};

export function getPostRequestInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountTraderProfile extends string,
  TAccountInvestorListing extends string,
  TAccountRequest extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: PostRequestInput<
    TAccountTrader,
    TAccountConfig,
    TAccountTraderProfile,
    TAccountInvestorListing,
    TAccountRequest,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PostRequestInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountTraderProfile,
  TAccountInvestorListing,
  TAccountRequest,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    traderProfile: { value: input.traderProfile ?? null, isWritable: false },
    investorListing: {
      value: input.investorListing ?? null,
      isWritable: false,
    },
    request: { value: input.request ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.traderProfile),
      getAccountMeta(accounts.investorListing),
      getAccountMeta(accounts.request),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getPostRequestInstructionDataEncoder().encode(
      args as PostRequestInstructionDataArgs,
    ),
    programAddress,
  } as PostRequestInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountTraderProfile,
    TAccountInvestorListing,
    TAccountRequest,
    TAccountSystemProgram
  >);
}

export type ParsedPostRequestInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    /** Required, so the investor reading the request can read a real track record beside it. */
    traderProfile: TAccountMetas[2];
    /**
     * The investor's listing, which must be open.
     *
     * This is the anti-spam rule. A request can only go to an investor who has publicly said
     * they are looking, so no wallet can be messaged merely for existing — and closing the
     * listing is how an investor shuts the door.
     */
    investorListing: TAccountMetas[3];
    /**
     * One open request per pair. The seeds make a duplicate impossible, so a trader cannot
     * flood an inbox with copies of the same ask.
     */
    request: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: PostRequestInstructionData;
};

export function parsePostRequestInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPostRequestInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      traderProfile: getNextAccount(),
      investorListing: getNextAccount(),
      request: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPostRequestInstructionDataDecoder().decode(instruction.data),
  };
}
