/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const RECONCILE_POSITION_DISCRIMINATOR = new Uint8Array([
  112, 179, 103, 225, 241, 95, 12, 78,
]);

export function getReconcilePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RECONCILE_POSITION_DISCRIMINATOR,
  );
}

export type ReconcilePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountTraderProfile extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountMandate extends string
        ? WritableAccount<TAccountMandate>
        : TAccountMandate,
      TAccountUserAccount extends string
        ? ReadonlyAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountTraderProfile extends string
        ? WritableAccount<TAccountTraderProfile>
        : TAccountTraderProfile,
      ...TRemainingAccounts,
    ]
  >;

export type ReconcilePositionInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ReconcilePositionInstructionDataArgs = {};

export function getReconcilePositionInstructionDataEncoder(): FixedSizeEncoder<ReconcilePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RECONCILE_POSITION_DISCRIMINATOR }),
  );
}

export function getReconcilePositionInstructionDataDecoder(): FixedSizeDecoder<ReconcilePositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getReconcilePositionInstructionDataCodec(): FixedSizeCodec<
  ReconcilePositionInstructionDataArgs,
  ReconcilePositionInstructionData
> {
  return combineCodec(
    getReconcilePositionInstructionDataEncoder(),
    getReconcilePositionInstructionDataDecoder(),
  );
}

export type ReconcilePositionInput<
  TAccountCaller extends string = string,
  TAccountMandate extends string = string,
  TAccountUserAccount extends string = string,
  TAccountTraderProfile extends string = string,
> = {
  /** **Anyone.** */
  caller: TransactionSigner<TAccountCaller>;
  mandate: Address<TAccountMandate>;
  /**
   * SolFX's own account of this mandate: how much free collateral it holds, and how many
   * positions it still has open. Those two numbers are what makes the result recoverable.
   */
  userAccount: Address<TAccountUserAccount>;
  traderProfile: Address<TAccountTraderProfile>;
};

export function getReconcilePositionInstruction<
  TAccountCaller extends string,
  TAccountMandate extends string,
  TAccountUserAccount extends string,
  TAccountTraderProfile extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: ReconcilePositionInput<
    TAccountCaller,
    TAccountMandate,
    TAccountUserAccount,
    TAccountTraderProfile
  >,
  config?: { programAddress?: TProgramAddress },
): ReconcilePositionInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountMandate,
  TAccountUserAccount,
  TAccountTraderProfile
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: false },
    traderProfile: { value: input.traderProfile ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.traderProfile),
    ],
    data: getReconcilePositionInstructionDataEncoder().encode({}),
    programAddress,
  } as ReconcilePositionInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountMandate,
    TAccountUserAccount,
    TAccountTraderProfile
  >);
}

export type ParsedReconcilePositionInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** **Anyone.** */
    caller: TAccountMetas[0];
    mandate: TAccountMetas[1];
    /**
     * SolFX's own account of this mandate: how much free collateral it holds, and how many
     * positions it still has open. Those two numbers are what makes the result recoverable.
     */
    userAccount: TAccountMetas[2];
    traderProfile: TAccountMetas[3];
  };
  data: ReconcilePositionInstructionData;
};

export function parseReconcilePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedReconcilePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      mandate: getNextAccount(),
      userAccount: getNextAccount(),
      traderProfile: getNextAccount(),
    },
    data: getReconcilePositionInstructionDataDecoder().decode(instruction.data),
  };
}
