/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_TREASURY_DISCRIMINATOR = new Uint8Array([
  57, 97, 196, 95, 195, 206, 106, 136,
]);

export function getSetTreasuryDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_TREASURY_DISCRIMINATOR,
  );
}

export type SetTreasuryInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type SetTreasuryInstructionData = {
  discriminator: ReadonlyUint8Array;
  treasury: Address;
};

export type SetTreasuryInstructionDataArgs = { treasury: Address };

export function getSetTreasuryInstructionDataEncoder(): FixedSizeEncoder<SetTreasuryInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["treasury", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_TREASURY_DISCRIMINATOR }),
  );
}

export function getSetTreasuryInstructionDataDecoder(): FixedSizeDecoder<SetTreasuryInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["treasury", getAddressDecoder()],
  ]);
}

export function getSetTreasuryInstructionDataCodec(): FixedSizeCodec<
  SetTreasuryInstructionDataArgs,
  SetTreasuryInstructionData
> {
  return combineCodec(
    getSetTreasuryInstructionDataEncoder(),
    getSetTreasuryInstructionDataDecoder(),
  );
}

export type SetTreasuryAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
  treasury: SetTreasuryInstructionDataArgs["treasury"];
};

export async function getSetTreasuryInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: SetTreasuryAsyncInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetTreasuryInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getSetTreasuryInstructionDataEncoder().encode(
      args as SetTreasuryInstructionDataArgs,
    ),
    programAddress,
  } as SetTreasuryInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type SetTreasuryInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
  treasury: SetTreasuryInstructionDataArgs["treasury"];
};

export function getSetTreasuryInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: SetTreasuryInput<TAccountAdmin, TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): SetTreasuryInstruction<TProgramAddress, TAccountAdmin, TAccountConfig> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.admin), getAccountMeta(accounts.config)],
    data: getSetTreasuryInstructionDataEncoder().encode(
      args as SetTreasuryInstructionDataArgs,
    ),
    programAddress,
  } as SetTreasuryInstruction<TProgramAddress, TAccountAdmin, TAccountConfig>);
}

export type ParsedSetTreasuryInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
  };
  data: SetTreasuryInstructionData;
};

export function parseSetTreasuryInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetTreasuryInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), config: getNextAccount() },
    data: getSetTreasuryInstructionDataDecoder().decode(instruction.data),
  };
}
