/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda, findPostListingListingPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getListingTermsDecoder,
  getListingTermsEncoder,
  type ListingTerms,
  type ListingTermsArgs,
} from "../types";

export const UPDATE_LISTING_DISCRIMINATOR = new Uint8Array([
  192, 174, 210, 68, 116, 40, 242, 253,
]);

export function getUpdateListingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_LISTING_DISCRIMINATOR,
  );
}

export type UpdateListingInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountTrader extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTrader extends string
        ? ReadonlySignerAccount<TAccountTrader> &
            AccountSignerMeta<TAccountTrader>
        : TAccountTrader,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateListingInstructionData = {
  discriminator: ReadonlyUint8Array;
  terms: ListingTerms;
  open: boolean;
};

export type UpdateListingInstructionDataArgs = {
  terms: ListingTermsArgs;
  open: boolean;
};

export function getUpdateListingInstructionDataEncoder(): Encoder<UpdateListingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["terms", getListingTermsEncoder()],
      ["open", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_LISTING_DISCRIMINATOR }),
  );
}

export function getUpdateListingInstructionDataDecoder(): Decoder<UpdateListingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["terms", getListingTermsDecoder()],
    ["open", getBooleanDecoder()],
  ]);
}

export function getUpdateListingInstructionDataCodec(): Codec<
  UpdateListingInstructionDataArgs,
  UpdateListingInstructionData
> {
  return combineCodec(
    getUpdateListingInstructionDataEncoder(),
    getUpdateListingInstructionDataDecoder(),
  );
}

export type UpdateListingAsyncInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountListing extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config?: Address<TAccountConfig>;
  listing?: Address<TAccountListing>;
  terms: UpdateListingInstructionDataArgs["terms"];
  open: UpdateListingInstructionDataArgs["open"];
};

export async function getUpdateListingInstructionAsync<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: UpdateListingAsyncInput<
    TAccountTrader,
    TAccountConfig,
    TAccountListing
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateListingInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountListing
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.listing.value) {
    accounts.listing.value = await findPostListingListingPda({
      trader: expectAddress(accounts.trader.value),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.listing),
    ],
    data: getUpdateListingInstructionDataEncoder().encode(
      args as UpdateListingInstructionDataArgs,
    ),
    programAddress,
  } as UpdateListingInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountListing
  >);
}

export type UpdateListingInput<
  TAccountTrader extends string = string,
  TAccountConfig extends string = string,
  TAccountListing extends string = string,
> = {
  trader: TransactionSigner<TAccountTrader>;
  config: Address<TAccountConfig>;
  listing: Address<TAccountListing>;
  terms: UpdateListingInstructionDataArgs["terms"];
  open: UpdateListingInstructionDataArgs["open"];
};

export function getUpdateListingInstruction<
  TAccountTrader extends string,
  TAccountConfig extends string,
  TAccountListing extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: UpdateListingInput<TAccountTrader, TAccountConfig, TAccountListing>,
  config?: { programAddress?: TProgramAddress },
): UpdateListingInstruction<
  TProgramAddress,
  TAccountTrader,
  TAccountConfig,
  TAccountListing
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    trader: { value: input.trader ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.trader),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.listing),
    ],
    data: getUpdateListingInstructionDataEncoder().encode(
      args as UpdateListingInstructionDataArgs,
    ),
    programAddress,
  } as UpdateListingInstruction<
    TProgramAddress,
    TAccountTrader,
    TAccountConfig,
    TAccountListing
  >);
}

export type ParsedUpdateListingInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    trader: TAccountMetas[0];
    config: TAccountMetas[1];
    listing: TAccountMetas[2];
  };
  data: UpdateListingInstructionData;
};

export function parseUpdateListingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateListingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      trader: getNextAccount(),
      config: getNextAccount(),
      listing: getNextAccount(),
    },
    data: getUpdateListingInstructionDataDecoder().decode(instruction.data),
  };
}
