/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { findConfigPda, findMandateSignerPda } from "../pdas";
import { NOXFUNDS_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const WIND_DOWN_CANCEL_STOP_DISCRIMINATOR = new Uint8Array([
  47, 86, 164, 53, 15, 111, 233, 112,
]);

export function getWindDownCancelStopDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    WIND_DOWN_CANCEL_STOP_DISCRIMINATOR,
  );
}

export type WindDownCancelStopInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountCloser extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMandate extends string | AccountMeta<string> = string,
  TAccountMandateSigner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountSolfxCoreProgram extends string | AccountMeta<string> =
    "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCloser extends string
        ? ReadonlySignerAccount<TAccountCloser> &
            AccountSignerMeta<TAccountCloser>
        : TAccountCloser,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMandate extends string
        ? ReadonlyAccount<TAccountMandate>
        : TAccountMandate,
      TAccountMandateSigner extends string
        ? WritableAccount<TAccountMandateSigner>
        : TAccountMandateSigner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountSolfxCoreProgram extends string
        ? ReadonlyAccount<TAccountSolfxCoreProgram>
        : TAccountSolfxCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WindDownCancelStopInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type WindDownCancelStopInstructionDataArgs = {};

export function getWindDownCancelStopInstructionDataEncoder(): FixedSizeEncoder<WindDownCancelStopInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: WIND_DOWN_CANCEL_STOP_DISCRIMINATOR,
    }),
  );
}

export function getWindDownCancelStopInstructionDataDecoder(): FixedSizeDecoder<WindDownCancelStopInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getWindDownCancelStopInstructionDataCodec(): FixedSizeCodec<
  WindDownCancelStopInstructionDataArgs,
  WindDownCancelStopInstructionData
> {
  return combineCodec(
    getWindDownCancelStopInstructionDataEncoder(),
    getWindDownCancelStopInstructionDataDecoder(),
  );
}

export type WindDownCancelStopAsyncInput<
  TAccountCloser extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountPosition extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  /** **Anyone.** */
  closer: TransactionSigner<TAccountCloser>;
  config?: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner?: Address<TAccountMandateSigner>;
  /** Deserialized for its kind and position; see `funded_cancel_stop`. */
  triggerOrder: Address<TAccountTriggerOrder>;
  position: Address<TAccountPosition>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
};

export async function getWindDownCancelStopInstructionAsync<
  TAccountCloser extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountTriggerOrder extends string,
  TAccountPosition extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: WindDownCancelStopAsyncInput<
    TAccountCloser,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountTriggerOrder,
    TAccountPosition,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  WindDownCancelStopInstruction<
    TProgramAddress,
    TAccountCloser,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountTriggerOrder,
    TAccountPosition,
    TAccountSolfxCoreProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    closer: { value: input.closer ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mandateSigner.value) {
    accounts.mandateSigner.value = await findMandateSignerPda({
      mandate: expectAddress(accounts.mandate.value),
    });
  }
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.closer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.triggerOrder),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getWindDownCancelStopInstructionDataEncoder().encode({}),
    programAddress,
  } as WindDownCancelStopInstruction<
    TProgramAddress,
    TAccountCloser,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountTriggerOrder,
    TAccountPosition,
    TAccountSolfxCoreProgram
  >);
}

export type WindDownCancelStopInput<
  TAccountCloser extends string = string,
  TAccountConfig extends string = string,
  TAccountMandate extends string = string,
  TAccountMandateSigner extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountPosition extends string = string,
  TAccountSolfxCoreProgram extends string = string,
> = {
  /** **Anyone.** */
  closer: TransactionSigner<TAccountCloser>;
  config: Address<TAccountConfig>;
  mandate: Address<TAccountMandate>;
  mandateSigner: Address<TAccountMandateSigner>;
  /** Deserialized for its kind and position; see `funded_cancel_stop`. */
  triggerOrder: Address<TAccountTriggerOrder>;
  position: Address<TAccountPosition>;
  solfxCoreProgram?: Address<TAccountSolfxCoreProgram>;
};

export function getWindDownCancelStopInstruction<
  TAccountCloser extends string,
  TAccountConfig extends string,
  TAccountMandate extends string,
  TAccountMandateSigner extends string,
  TAccountTriggerOrder extends string,
  TAccountPosition extends string,
  TAccountSolfxCoreProgram extends string,
  TProgramAddress extends Address = typeof NOXFUNDS_PROGRAM_ADDRESS,
>(
  input: WindDownCancelStopInput<
    TAccountCloser,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountTriggerOrder,
    TAccountPosition,
    TAccountSolfxCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): WindDownCancelStopInstruction<
  TProgramAddress,
  TAccountCloser,
  TAccountConfig,
  TAccountMandate,
  TAccountMandateSigner,
  TAccountTriggerOrder,
  TAccountPosition,
  TAccountSolfxCoreProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOXFUNDS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    closer: { value: input.closer ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    mandate: { value: input.mandate ?? null, isWritable: false },
    mandateSigner: { value: input.mandateSigner ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: false },
    solfxCoreProgram: {
      value: input.solfxCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.solfxCoreProgram.value) {
    accounts.solfxCoreProgram.value =
      "2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi" as Address<"2EQzy2Mzixi54tJkMbWWqJFoayUoGBNwZCEJCy44ZVKi">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.closer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.mandate),
      getAccountMeta(accounts.mandateSigner),
      getAccountMeta(accounts.triggerOrder),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.solfxCoreProgram),
    ],
    data: getWindDownCancelStopInstructionDataEncoder().encode({}),
    programAddress,
  } as WindDownCancelStopInstruction<
    TProgramAddress,
    TAccountCloser,
    TAccountConfig,
    TAccountMandate,
    TAccountMandateSigner,
    TAccountTriggerOrder,
    TAccountPosition,
    TAccountSolfxCoreProgram
  >);
}

export type ParsedWindDownCancelStopInstruction<
  TProgram extends string = typeof NOXFUNDS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** **Anyone.** */
    closer: TAccountMetas[0];
    config: TAccountMetas[1];
    mandate: TAccountMetas[2];
    mandateSigner: TAccountMetas[3];
    /** Deserialized for its kind and position; see `funded_cancel_stop`. */
    triggerOrder: TAccountMetas[4];
    position: TAccountMetas[5];
    solfxCoreProgram: TAccountMetas[6];
  };
  data: WindDownCancelStopInstructionData;
};

export function parseWindDownCancelStopInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWindDownCancelStopInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      closer: getNextAccount(),
      config: getNextAccount(),
      mandate: getNextAccount(),
      mandateSigner: getNextAccount(),
      triggerOrder: getNextAccount(),
      position: getNextAccount(),
      solfxCoreProgram: getNextAccount(),
    },
    data: getWindDownCancelStopInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
