/**
 * GENERATED by scripts/generate-events.ts from target/idl/solfx_core.json. DO NOT EDIT.
 *
 * Codama does not render event structs — it only emits types that an instruction or account
 * references, and nothing references an event. Every codec here is the same one Codama emits
 * for that field type elsewhere in this client.
 *
 * 35 events.
 */
import {
  addDecoderSizePrefix,
  fixDecoderSize,
  getAddressDecoder,
  getBooleanDecoder,
  getBytesDecoder,
  getI128Decoder,
  getI64Decoder,
  getStructDecoder,
  getU128Decoder,
  getU16Decoder,
  getU32Decoder,
  getU64Decoder,
  getU8Decoder,
  getUtf8Decoder,
  type Address,
  type Decoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AdminTransferAccepted = {
  oldAdmin: Address;
  newAdmin: Address;
  ts: bigint;
};

export const ADMIN_TRANSFER_ACCEPTED_DISCRIMINATOR = new Uint8Array([79, 229, 204, 202, 134, 43, 177, 26]);

export function getAdminTransferAcceptedDecoder(): Decoder<AdminTransferAccepted> {
  return getStructDecoder([
    ["oldAdmin", getAddressDecoder()],
    ["newAdmin", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type AdminTransferInitiated = {
  currentAdmin: Address;
  pendingAdmin: Address;
  ts: bigint;
};

export const ADMIN_TRANSFER_INITIATED_DISCRIMINATOR = new Uint8Array([157, 255, 0, 92, 52, 106, 16, 156]);

export function getAdminTransferInitiatedDecoder(): Decoder<AdminTransferInitiated> {
  return getStructDecoder([
    ["currentAdmin", getAddressDecoder()],
    ["pendingAdmin", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type BadDebtIncurred = {
  marketIndex: number;
  position: Address;
  amount: bigint;
  ts: bigint;
};

export const BAD_DEBT_INCURRED_DISCRIMINATOR = new Uint8Array([104, 204, 110, 189, 70, 253, 145, 249]);

export function getBadDebtIncurredDecoder(): Decoder<BadDebtIncurred> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["position", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type CircuitBreakerTripped = {
  marketIndex: number;
  reason: number;
  observed: bigint;
  limit: bigint;
  ts: bigint;
};

export const CIRCUIT_BREAKER_TRIPPED_DISCRIMINATOR = new Uint8Array([188, 9, 111, 118, 136, 206, 199, 65]);

export function getCircuitBreakerTrippedDecoder(): Decoder<CircuitBreakerTripped> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["reason", getU8Decoder()],
    ["observed", getU64Decoder()],
    ["limit", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type CollateralDeposited = {
  userAccount: Address;
  authority: Address;
  amount: bigint;
  freeCollateralAfter: bigint;
  totalUserCollateralAfter: bigint;
  ts: bigint;
};

export const COLLATERAL_DEPOSITED_DISCRIMINATOR = new Uint8Array([244, 62, 77, 11, 135, 112, 61, 96]);

export function getCollateralDepositedDecoder(): Decoder<CollateralDeposited> {
  return getStructDecoder([
    ["userAccount", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["freeCollateralAfter", getU64Decoder()],
    ["totalUserCollateralAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type CollateralWithdrawn = {
  userAccount: Address;
  authority: Address;
  amount: bigint;
  freeCollateralAfter: bigint;
  totalUserCollateralAfter: bigint;
  ts: bigint;
};

export const COLLATERAL_WITHDRAWN_DISCRIMINATOR = new Uint8Array([51, 224, 133, 106, 74, 173, 72, 82]);

export function getCollateralWithdrawnDecoder(): Decoder<CollateralWithdrawn> {
  return getStructDecoder([
    ["userAccount", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["freeCollateralAfter", getU64Decoder()],
    ["totalUserCollateralAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type FeeCollected = {
  marketIndex: number;
  userAccount: Address;
  referrer: Address;
  total: bigint;
  lp: bigint;
  treasury: bigint;
  insurance: bigint;
  referral: bigint;
  ts: bigint;
};

export const FEE_COLLECTED_DISCRIMINATOR = new Uint8Array([12, 28, 17, 248, 244, 36, 8, 73]);

export function getFeeCollectedDecoder(): Decoder<FeeCollected> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["userAccount", getAddressDecoder()],
    ["referrer", getAddressDecoder()],
    ["total", getU64Decoder()],
    ["lp", getU64Decoder()],
    ["treasury", getU64Decoder()],
    ["insurance", getU64Decoder()],
    ["referral", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type FeeSplitUpdated = {
  lpBps: number;
  treasuryBps: number;
  insuranceBps: number;
  referralBps: number;
  ts: bigint;
};

export const FEE_SPLIT_UPDATED_DISCRIMINATOR = new Uint8Array([125, 91, 141, 252, 205, 113, 171, 92]);

export function getFeeSplitUpdatedDecoder(): Decoder<FeeSplitUpdated> {
  return getStructDecoder([
    ["lpBps", getU16Decoder()],
    ["treasuryBps", getU16Decoder()],
    ["insuranceBps", getU16Decoder()],
    ["referralBps", getU16Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type FundingUpdated = {
  marketIndex: number;
  fundingRatePerHour: bigint;
  carryRatePerHour: bigint;
  cumFundingLong: bigint;
  cumFundingShort: bigint;
  cumBorrowIndex: bigint;
  skewRatio: bigint;
  elapsedSeconds: bigint;
  ts: bigint;
};

export const FUNDING_UPDATED_DISCRIMINATOR = new Uint8Array([206, 76, 89, 81, 126, 37, 255, 224]);

export function getFundingUpdatedDecoder(): Decoder<FundingUpdated> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["fundingRatePerHour", getI64Decoder()],
    ["carryRatePerHour", getI64Decoder()],
    ["cumFundingLong", getI128Decoder()],
    ["cumFundingShort", getI128Decoder()],
    ["cumBorrowIndex", getU128Decoder()],
    ["skewRatio", getI64Decoder()],
    ["elapsedSeconds", getI64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type LiquidityAdded = {
  provider: Address;
  usdcIn: bigint;
  lpTokensOut: bigint;
  aumAfter: bigint;
  ts: bigint;
};

export const LIQUIDITY_ADDED_DISCRIMINATOR = new Uint8Array([154, 26, 221, 108, 238, 64, 217, 161]);

export function getLiquidityAddedDecoder(): Decoder<LiquidityAdded> {
  return getStructDecoder([
    ["provider", getAddressDecoder()],
    ["usdcIn", getU64Decoder()],
    ["lpTokensOut", getU64Decoder()],
    ["aumAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type LiquidityRemoved = {
  provider: Address;
  shares: bigint;
  gross: bigint;
  exitFee: bigint;
  performanceFee: bigint;
  payout: bigint;
  aumAfter: bigint;
  supplyAfter: bigint;
  navPerShareAfter: bigint;
  ts: bigint;
};

export const LIQUIDITY_REMOVED_DISCRIMINATOR = new Uint8Array([225, 105, 216, 39, 124, 116, 169, 189]);

export function getLiquidityRemovedDecoder(): Decoder<LiquidityRemoved> {
  return getStructDecoder([
    ["provider", getAddressDecoder()],
    ["shares", getU64Decoder()],
    ["gross", getU64Decoder()],
    ["exitFee", getU64Decoder()],
    ["performanceFee", getU64Decoder()],
    ["payout", getU64Decoder()],
    ["aumAfter", getU64Decoder()],
    ["supplyAfter", getU64Decoder()],
    ["navPerShareAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketFeeParamsUpdated = {
  marketIndex: number;
  openFeeRate: bigint;
  closeFeeRate: bigint;
  baseSpreadBps: number;
  confSpreadMultiplierBps: number;
  ts: bigint;
};

export const MARKET_FEE_PARAMS_UPDATED_DISCRIMINATOR = new Uint8Array([241, 20, 174, 73, 119, 157, 166, 207]);

export function getMarketFeeParamsUpdatedDecoder(): Decoder<MarketFeeParamsUpdated> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["openFeeRate", getU64Decoder()],
    ["closeFeeRate", getU64Decoder()],
    ["baseSpreadBps", getU16Decoder()],
    ["confSpreadMultiplierBps", getU16Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketInitialized = {
  marketIndex: number;
  symbol: string;
  feedKind: number;
  pythFeedId: ReadonlyUint8Array;
  isSynthetic: boolean;
  needsQuoteConversion: boolean;
  maxLeverage: number;
  ts: bigint;
};

export const MARKET_INITIALIZED_DISCRIMINATOR = new Uint8Array([134, 160, 122, 87, 50, 3, 255, 81]);

export function getMarketInitializedDecoder(): Decoder<MarketInitialized> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["symbol", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["feedKind", getU8Decoder()],
    ["pythFeedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["isSynthetic", getBooleanDecoder()],
    ["needsQuoteConversion", getBooleanDecoder()],
    ["maxLeverage", getU16Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketOracleChanged = {
  marketIndex: number;
  oldFeedId: ReadonlyUint8Array;
  newFeedId: ReadonlyUint8Array;
  ts: bigint;
};

export const MARKET_ORACLE_CHANGED_DISCRIMINATOR = new Uint8Array([18, 215, 178, 65, 128, 141, 149, 66]);

export function getMarketOracleChangedDecoder(): Decoder<MarketOracleChanged> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["oldFeedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["newFeedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketPriceUpdated = {
  marketIndex: number;
  price: bigint;
  conf: bigint;
  confBps: bigint;
  emaPrice: bigint;
  deviationBps: bigint;
  publishTime: bigint;
  ts: bigint;
};

export const MARKET_PRICE_UPDATED_DISCRIMINATOR = new Uint8Array([123, 163, 196, 40, 134, 142, 47, 5]);

export function getMarketPriceUpdatedDecoder(): Decoder<MarketPriceUpdated> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["price", getI64Decoder()],
    ["conf", getU64Decoder()],
    ["confBps", getU64Decoder()],
    ["emaPrice", getI64Decoder()],
    ["deviationBps", getU64Decoder()],
    ["publishTime", getI64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketRiskParamsUpdated = {
  marketIndex: number;
  maxLeverage: number;
  imrBps: number;
  mmrBps: number;
  maxConfBps: number;
  maxDeviationBps: number;
  maxStalenessSeconds: number;
  ts: bigint;
};

export const MARKET_RISK_PARAMS_UPDATED_DISCRIMINATOR = new Uint8Array([250, 253, 38, 71, 171, 148, 102, 217]);

export function getMarketRiskParamsUpdatedDecoder(): Decoder<MarketRiskParamsUpdated> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["maxLeverage", getU16Decoder()],
    ["imrBps", getU16Decoder()],
    ["mmrBps", getU16Decoder()],
    ["maxConfBps", getU16Decoder()],
    ["maxDeviationBps", getU16Decoder()],
    ["maxStalenessSeconds", getU32Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type MarketStatusChanged = {
  marketIndex: number;
  oldStatus: number;
  newStatus: number;
  actor: number;
  ts: bigint;
};

export const MARKET_STATUS_CHANGED_DISCRIMINATOR = new Uint8Array([53, 72, 160, 209, 15, 222, 46, 157]);

export function getMarketStatusChangedDecoder(): Decoder<MarketStatusChanged> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["oldStatus", getU8Decoder()],
    ["newStatus", getU8Decoder()],
    ["actor", getU8Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PoolSettlement = {
  marketIndex: number;
  amount: bigint;
  aumAfter: bigint;
  ts: bigint;
};

export const POOL_SETTLEMENT_DISCRIMINATOR = new Uint8Array([133, 41, 206, 79, 140, 157, 155, 114]);

export function getPoolSettlementDecoder(): Decoder<PoolSettlement> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["amount", getI64Decoder()],
    ["aumAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionAutoDeleveraged = {
  position: Address;
  userAccount: Address;
  marketIndex: number;
  sizeBase: bigint;
  exitPrice: bigint;
  grossPnl: bigint;
  socialised: bigint;
  paidOut: bigint;
  remainingAdlDebt: bigint;
  ts: bigint;
};

export const POSITION_AUTO_DELEVERAGED_DISCRIMINATOR = new Uint8Array([230, 215, 16, 242, 166, 232, 191, 254]);

export function getPositionAutoDeleveragedDecoder(): Decoder<PositionAutoDeleveraged> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["userAccount", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["sizeBase", getU64Decoder()],
    ["exitPrice", getI64Decoder()],
    ["grossPnl", getI64Decoder()],
    ["socialised", getU64Decoder()],
    ["paidOut", getU64Decoder()],
    ["remainingAdlDebt", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionCollateralChanged = {
  position: Address;
  marketIndex: number;
  delta: bigint;
  collateralAfter: bigint;
  ts: bigint;
};

export const POSITION_COLLATERAL_CHANGED_DISCRIMINATOR = new Uint8Array([69, 115, 239, 28, 225, 56, 85, 110]);

export function getPositionCollateralChangedDecoder(): Decoder<PositionCollateralChanged> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["delta", getI64Decoder()],
    ["collateralAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionDecreased = {
  position: Address;
  userAccount: Address;
  marketIndex: number;
  sizeClosed: bigint;
  remainingSize: bigint;
  oraclePrice: bigint;
  execPrice: bigint;
  realizedPnl: bigint;
  fee: bigint;
  collateralReturned: bigint;
  fullyClosed: boolean;
  ts: bigint;
};

export const POSITION_DECREASED_DISCRIMINATOR = new Uint8Array([251, 151, 37, 204, 127, 87, 115, 232]);

export function getPositionDecreasedDecoder(): Decoder<PositionDecreased> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["userAccount", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["sizeClosed", getU64Decoder()],
    ["remainingSize", getU64Decoder()],
    ["oraclePrice", getI64Decoder()],
    ["execPrice", getI64Decoder()],
    ["realizedPnl", getI64Decoder()],
    ["fee", getU64Decoder()],
    ["collateralReturned", getU64Decoder()],
    ["fullyClosed", getBooleanDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionIncreased = {
  position: Address;
  marketIndex: number;
  sizeAdded: bigint;
  collateralAdded: bigint;
  execPrice: bigint;
  newSizeBase: bigint;
  newEntryPrice: bigint;
  fee: bigint;
  ts: bigint;
};

export const POSITION_INCREASED_DISCRIMINATOR = new Uint8Array([73, 58, 247, 181, 100, 237, 249, 81]);

export function getPositionIncreasedDecoder(): Decoder<PositionIncreased> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["sizeAdded", getU64Decoder()],
    ["collateralAdded", getU64Decoder()],
    ["execPrice", getI64Decoder()],
    ["newSizeBase", getU64Decoder()],
    ["newEntryPrice", getI64Decoder()],
    ["fee", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionLiquidated = {
  position: Address;
  userAccount: Address;
  liquidator: Address;
  marketIndex: number;
  sizeBase: bigint;
  exitPrice: bigint;
  equity: bigint;
  maintenanceMargin: bigint;
  penalty: bigint;
  liquidatorReward: bigint;
  residualToOwner: bigint;
  badDebt: bigint;
  insuranceDrawn: bigint;
  uncoveredBadDebt: bigint;
  ts: bigint;
};

export const POSITION_LIQUIDATED_DISCRIMINATOR = new Uint8Array([40, 107, 90, 214, 96, 30, 61, 128]);

export function getPositionLiquidatedDecoder(): Decoder<PositionLiquidated> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["userAccount", getAddressDecoder()],
    ["liquidator", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["sizeBase", getU64Decoder()],
    ["exitPrice", getI64Decoder()],
    ["equity", getI64Decoder()],
    ["maintenanceMargin", getU64Decoder()],
    ["penalty", getU64Decoder()],
    ["liquidatorReward", getU64Decoder()],
    ["residualToOwner", getU64Decoder()],
    ["badDebt", getU64Decoder()],
    ["insuranceDrawn", getU64Decoder()],
    ["uncoveredBadDebt", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type PositionOpened = {
  position: Address;
  userAccount: Address;
  marketIndex: number;
  direction: number;
  sizeBase: bigint;
  oraclePrice: bigint;
  execPrice: bigint;
  spreadBps: bigint;
  notionalCollateral: bigint;
  collateral: bigint;
  fee: bigint;
  referrer: Address;
  ts: bigint;
};

export const POSITION_OPENED_DISCRIMINATOR = new Uint8Array([237, 175, 243, 230, 147, 117, 101, 121]);

export function getPositionOpenedDecoder(): Decoder<PositionOpened> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["userAccount", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["direction", getU8Decoder()],
    ["sizeBase", getU64Decoder()],
    ["oraclePrice", getI64Decoder()],
    ["execPrice", getI64Decoder()],
    ["spreadBps", getU64Decoder()],
    ["notionalCollateral", getU64Decoder()],
    ["collateral", getU64Decoder()],
    ["fee", getU64Decoder()],
    ["referrer", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type ProtocolInitialized = {
  admin: Address;
  guardian: Address;
  usdcMint: Address;
  lpMint: Address;
  ts: bigint;
};

export const PROTOCOL_INITIALIZED_DISCRIMINATOR = new Uint8Array([173, 122, 168, 254, 9, 118, 76, 132]);

export function getProtocolInitializedDecoder(): Decoder<ProtocolInitialized> {
  return getStructDecoder([
    ["admin", getAddressDecoder()],
    ["guardian", getAddressDecoder()],
    ["usdcMint", getAddressDecoder()],
    ["lpMint", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type ProtocolPauseChanged = {
  paused: boolean;
  actor: Address;
  ts: bigint;
};

export const PROTOCOL_PAUSE_CHANGED_DISCRIMINATOR = new Uint8Array([67, 33, 235, 73, 71, 124, 172, 110]);

export function getProtocolPauseChangedDecoder(): Decoder<ProtocolPauseChanged> {
  return getStructDecoder([
    ["paused", getBooleanDecoder()],
    ["actor", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type ReferralPaid = {
  destination: Address;
  amount: bigint;
  totalClaimed: bigint;
  totalAccrued: bigint;
  ts: bigint;
};

export const REFERRAL_PAID_DISCRIMINATOR = new Uint8Array([70, 190, 133, 42, 145, 213, 87, 197]);

export function getReferralPaidDecoder(): Decoder<ReferralPaid> {
  return getStructDecoder([
    ["destination", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["totalClaimed", getU64Decoder()],
    ["totalAccrued", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type SessionCranked = {
  marketIndex: number;
  status: number;
  feedLive: boolean;
  calendarOpen: boolean;
  secondsToClose: bigint;
  ts: bigint;
};

export const SESSION_CRANKED_DISCRIMINATOR = new Uint8Array([174, 119, 142, 165, 17, 150, 55, 169]);

export function getSessionCrankedDecoder(): Decoder<SessionCranked> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["status", getU8Decoder()],
    ["feedLive", getBooleanDecoder()],
    ["calendarOpen", getBooleanDecoder()],
    ["secondsToClose", getI64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type TreasuryFeesWithdrawn = {
  destination: Address;
  amount: bigint;
  ts: bigint;
};

export const TREASURY_FEES_WITHDRAWN_DISCRIMINATOR = new Uint8Array([28, 138, 35, 235, 37, 79, 145, 40]);

export function getTreasuryFeesWithdrawnDecoder(): Decoder<TreasuryFeesWithdrawn> {
  return getStructDecoder([
    ["destination", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type TriggerOrderCancelled = {
  order: Address;
  position: Address;
  authority: Address;
  orderId: number;
  ts: bigint;
};

export const TRIGGER_ORDER_CANCELLED_DISCRIMINATOR = new Uint8Array([255, 151, 206, 140, 98, 153, 223, 121]);

export function getTriggerOrderCancelledDecoder(): Decoder<TriggerOrderCancelled> {
  return getStructDecoder([
    ["order", getAddressDecoder()],
    ["position", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["orderId", getU8Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type TriggerOrderExecuted = {
  order: Address;
  position: Address;
  keeper: Address;
  marketIndex: number;
  orderId: number;
  kind: number;
  triggerPrice: bigint;
  oraclePrice: bigint;
  sizeBase: bigint;
  keeperTipLamports: bigint;
  ts: bigint;
};

export const TRIGGER_ORDER_EXECUTED_DISCRIMINATOR = new Uint8Array([47, 181, 92, 44, 141, 93, 45, 145]);

export function getTriggerOrderExecutedDecoder(): Decoder<TriggerOrderExecuted> {
  return getStructDecoder([
    ["order", getAddressDecoder()],
    ["position", getAddressDecoder()],
    ["keeper", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["orderId", getU8Decoder()],
    ["kind", getU8Decoder()],
    ["triggerPrice", getI64Decoder()],
    ["oraclePrice", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
    ["keeperTipLamports", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type TriggerOrderPlaced = {
  order: Address;
  position: Address;
  authority: Address;
  marketIndex: number;
  orderId: number;
  kind: number;
  triggerPrice: bigint;
  sizeBase: bigint;
  spotAtPlacement: bigint;
  ts: bigint;
};

export const TRIGGER_ORDER_PLACED_DISCRIMINATOR = new Uint8Array([216, 192, 75, 95, 249, 205, 52, 124]);

export function getTriggerOrderPlacedDecoder(): Decoder<TriggerOrderPlaced> {
  return getStructDecoder([
    ["order", getAddressDecoder()],
    ["position", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["orderId", getU8Decoder()],
    ["kind", getU8Decoder()],
    ["triggerPrice", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
    ["spotAtPlacement", getI64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type UserAccountInitialized = {
  userAccount: Address;
  authority: Address;
  referrer: Address;
  ts: bigint;
};

export const USER_ACCOUNT_INITIALIZED_DISCRIMINATOR = new Uint8Array([248, 93, 107, 233, 72, 9, 130, 57]);

export function getUserAccountInitializedDecoder(): Decoder<UserAccountInitialized> {
  return getStructDecoder([
    ["userAccount", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["referrer", getAddressDecoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type WithdrawalCancelled = {
  provider: Address;
  shares: bigint;
  pendingSharesAfter: bigint;
  ts: bigint;
};

export const WITHDRAWAL_CANCELLED_DISCRIMINATOR = new Uint8Array([119, 175, 207, 80, 186, 237, 229, 9]);

export function getWithdrawalCancelledDecoder(): Decoder<WithdrawalCancelled> {
  return getStructDecoder([
    ["provider", getAddressDecoder()],
    ["shares", getU64Decoder()],
    ["pendingSharesAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

export type WithdrawalRequested = {
  provider: Address;
  shares: bigint;
  unlockAt: bigint;
  pendingSharesAfter: bigint;
  ts: bigint;
};

export const WITHDRAWAL_REQUESTED_DISCRIMINATOR = new Uint8Array([75, 207, 21, 12, 160, 102, 150, 55]);

export function getWithdrawalRequestedDecoder(): Decoder<WithdrawalRequested> {
  return getStructDecoder([
    ["provider", getAddressDecoder()],
    ["shares", getU64Decoder()],
    ["unlockAt", getI64Decoder()],
    ["pendingSharesAfter", getU64Decoder()],
    ["ts", getI64Decoder()],
  ]);
}

/** Every event, for dispatch by discriminator. */
export const SOLFX_EVENTS = [
  { name: "AdminTransferAccepted" as const, discriminator: ADMIN_TRANSFER_ACCEPTED_DISCRIMINATOR, decoder: getAdminTransferAcceptedDecoder() },
  { name: "AdminTransferInitiated" as const, discriminator: ADMIN_TRANSFER_INITIATED_DISCRIMINATOR, decoder: getAdminTransferInitiatedDecoder() },
  { name: "BadDebtIncurred" as const, discriminator: BAD_DEBT_INCURRED_DISCRIMINATOR, decoder: getBadDebtIncurredDecoder() },
  { name: "CircuitBreakerTripped" as const, discriminator: CIRCUIT_BREAKER_TRIPPED_DISCRIMINATOR, decoder: getCircuitBreakerTrippedDecoder() },
  { name: "CollateralDeposited" as const, discriminator: COLLATERAL_DEPOSITED_DISCRIMINATOR, decoder: getCollateralDepositedDecoder() },
  { name: "CollateralWithdrawn" as const, discriminator: COLLATERAL_WITHDRAWN_DISCRIMINATOR, decoder: getCollateralWithdrawnDecoder() },
  { name: "FeeCollected" as const, discriminator: FEE_COLLECTED_DISCRIMINATOR, decoder: getFeeCollectedDecoder() },
  { name: "FeeSplitUpdated" as const, discriminator: FEE_SPLIT_UPDATED_DISCRIMINATOR, decoder: getFeeSplitUpdatedDecoder() },
  { name: "FundingUpdated" as const, discriminator: FUNDING_UPDATED_DISCRIMINATOR, decoder: getFundingUpdatedDecoder() },
  { name: "LiquidityAdded" as const, discriminator: LIQUIDITY_ADDED_DISCRIMINATOR, decoder: getLiquidityAddedDecoder() },
  { name: "LiquidityRemoved" as const, discriminator: LIQUIDITY_REMOVED_DISCRIMINATOR, decoder: getLiquidityRemovedDecoder() },
  { name: "MarketFeeParamsUpdated" as const, discriminator: MARKET_FEE_PARAMS_UPDATED_DISCRIMINATOR, decoder: getMarketFeeParamsUpdatedDecoder() },
  { name: "MarketInitialized" as const, discriminator: MARKET_INITIALIZED_DISCRIMINATOR, decoder: getMarketInitializedDecoder() },
  { name: "MarketOracleChanged" as const, discriminator: MARKET_ORACLE_CHANGED_DISCRIMINATOR, decoder: getMarketOracleChangedDecoder() },
  { name: "MarketPriceUpdated" as const, discriminator: MARKET_PRICE_UPDATED_DISCRIMINATOR, decoder: getMarketPriceUpdatedDecoder() },
  { name: "MarketRiskParamsUpdated" as const, discriminator: MARKET_RISK_PARAMS_UPDATED_DISCRIMINATOR, decoder: getMarketRiskParamsUpdatedDecoder() },
  { name: "MarketStatusChanged" as const, discriminator: MARKET_STATUS_CHANGED_DISCRIMINATOR, decoder: getMarketStatusChangedDecoder() },
  { name: "PoolSettlement" as const, discriminator: POOL_SETTLEMENT_DISCRIMINATOR, decoder: getPoolSettlementDecoder() },
  { name: "PositionAutoDeleveraged" as const, discriminator: POSITION_AUTO_DELEVERAGED_DISCRIMINATOR, decoder: getPositionAutoDeleveragedDecoder() },
  { name: "PositionCollateralChanged" as const, discriminator: POSITION_COLLATERAL_CHANGED_DISCRIMINATOR, decoder: getPositionCollateralChangedDecoder() },
  { name: "PositionDecreased" as const, discriminator: POSITION_DECREASED_DISCRIMINATOR, decoder: getPositionDecreasedDecoder() },
  { name: "PositionIncreased" as const, discriminator: POSITION_INCREASED_DISCRIMINATOR, decoder: getPositionIncreasedDecoder() },
  { name: "PositionLiquidated" as const, discriminator: POSITION_LIQUIDATED_DISCRIMINATOR, decoder: getPositionLiquidatedDecoder() },
  { name: "PositionOpened" as const, discriminator: POSITION_OPENED_DISCRIMINATOR, decoder: getPositionOpenedDecoder() },
  { name: "ProtocolInitialized" as const, discriminator: PROTOCOL_INITIALIZED_DISCRIMINATOR, decoder: getProtocolInitializedDecoder() },
  { name: "ProtocolPauseChanged" as const, discriminator: PROTOCOL_PAUSE_CHANGED_DISCRIMINATOR, decoder: getProtocolPauseChangedDecoder() },
  { name: "ReferralPaid" as const, discriminator: REFERRAL_PAID_DISCRIMINATOR, decoder: getReferralPaidDecoder() },
  { name: "SessionCranked" as const, discriminator: SESSION_CRANKED_DISCRIMINATOR, decoder: getSessionCrankedDecoder() },
  { name: "TreasuryFeesWithdrawn" as const, discriminator: TREASURY_FEES_WITHDRAWN_DISCRIMINATOR, decoder: getTreasuryFeesWithdrawnDecoder() },
  { name: "TriggerOrderCancelled" as const, discriminator: TRIGGER_ORDER_CANCELLED_DISCRIMINATOR, decoder: getTriggerOrderCancelledDecoder() },
  { name: "TriggerOrderExecuted" as const, discriminator: TRIGGER_ORDER_EXECUTED_DISCRIMINATOR, decoder: getTriggerOrderExecutedDecoder() },
  { name: "TriggerOrderPlaced" as const, discriminator: TRIGGER_ORDER_PLACED_DISCRIMINATOR, decoder: getTriggerOrderPlacedDecoder() },
  { name: "UserAccountInitialized" as const, discriminator: USER_ACCOUNT_INITIALIZED_DISCRIMINATOR, decoder: getUserAccountInitializedDecoder() },
  { name: "WithdrawalCancelled" as const, discriminator: WITHDRAWAL_CANCELLED_DISCRIMINATOR, decoder: getWithdrawalCancelledDecoder() },
  { name: "WithdrawalRequested" as const, discriminator: WITHDRAWAL_REQUESTED_DISCRIMINATOR, decoder: getWithdrawalRequestedDecoder() },
] as const;

export type SolfxEventName = (typeof SOLFX_EVENTS)[number]["name"];
