/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * How an entry order is triggered, judged on the oracle price like every trigger in SolFX.
 *
 * | | Long (a buy) | Short (a sell) |
 * |---|---|---|
 * | `Limit` | at or **below** the trigger | at or **above** the trigger |
 * | `Stop` | at or **above** the trigger | at or **below** the trigger |
 *
 * Written out rather than folded into a sign trick, for the reason `TriggerKind::is_met`
 * gives: a limit wired backwards buys the breakout it was meant to fade and reads as bad luck.
 */
export enum EntryKind {
  Limit,
  Stop,
}

export type EntryKindArgs = EntryKind;

export function getEntryKindEncoder(): FixedSizeEncoder<EntryKindArgs> {
  return getEnumEncoder(EntryKind);
}

export function getEntryKindDecoder(): FixedSizeDecoder<EntryKind> {
  return getEnumDecoder(EntryKind);
}

export function getEntryKindCodec(): FixedSizeCodec<EntryKindArgs, EntryKind> {
  return combineCodec(getEntryKindEncoder(), getEntryKindDecoder());
}
