/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * Why an evaluation failed, recorded on the account and in the event. Never a generic
 * "rule violation" — a trader who failed must be able to read which rule ended it.
 */
export enum EvalRule {
  None,
  DailyLoss,
  Drawdown,
  Abandoned,
}

export type EvalRuleArgs = EvalRule;

export function getEvalRuleEncoder(): FixedSizeEncoder<EvalRuleArgs> {
  return getEnumEncoder(EvalRule);
}

export function getEvalRuleDecoder(): FixedSizeDecoder<EvalRule> {
  return getEnumDecoder(EvalRule);
}

export function getEvalRuleCodec(): FixedSizeCodec<EvalRuleArgs, EvalRule> {
  return combineCodec(getEvalRuleEncoder(), getEvalRuleDecoder());
}
