/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * Which regime state machine a market follows (`ARCHITECTURE.md` § 7.3).
 *
 * A new asset class is a new variant plus its regime rules — never new maths. That is the
 * § 5.6 generic-engine constraint expressed as a type.
 */
export enum FeedKind {
  SpotFx,
  ContinuousIndex,
  Crypto,
}

export type FeedKindArgs = FeedKind;

export function getFeedKindEncoder(): FixedSizeEncoder<FeedKindArgs> {
  return getEnumEncoder(FeedKind);
}

export function getFeedKindDecoder(): FixedSizeDecoder<FeedKind> {
  return getEnumDecoder(FeedKind);
}

export function getFeedKindCodec(): FixedSizeCodec<FeedKindArgs, FeedKind> {
  return combineCodec(getFeedKindEncoder(), getFeedKindDecoder());
}
