/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

/** What an investor advertises. Advisory throughout: the binding numbers are on the offer. */
export type InvestorListingTerms = {
  nickname: string;
  minPrincipal: bigint;
  maxPrincipal: bigint;
  maxDrawdownBps: number;
  maxRiskPerTradeBps: number;
  allowedMarkets: bigint;
  offeredSplitBps: number;
  note: string;
};

export type InvestorListingTermsArgs = {
  nickname: string;
  minPrincipal: number | bigint;
  maxPrincipal: number | bigint;
  maxDrawdownBps: number;
  maxRiskPerTradeBps: number;
  allowedMarkets: number | bigint;
  offeredSplitBps: number;
  note: string;
};

export function getInvestorListingTermsEncoder(): Encoder<InvestorListingTermsArgs> {
  return getStructEncoder([
    ["nickname", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["minPrincipal", getU64Encoder()],
    ["maxPrincipal", getU64Encoder()],
    ["maxDrawdownBps", getU16Encoder()],
    ["maxRiskPerTradeBps", getU16Encoder()],
    ["allowedMarkets", getU128Encoder()],
    ["offeredSplitBps", getU16Encoder()],
    ["note", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getInvestorListingTermsDecoder(): Decoder<InvestorListingTerms> {
  return getStructDecoder([
    ["nickname", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["minPrincipal", getU64Decoder()],
    ["maxPrincipal", getU64Decoder()],
    ["maxDrawdownBps", getU16Decoder()],
    ["maxRiskPerTradeBps", getU16Decoder()],
    ["allowedMarkets", getU128Decoder()],
    ["offeredSplitBps", getU16Decoder()],
    ["note", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getInvestorListingTermsCodec(): Codec<
  InvestorListingTermsArgs,
  InvestorListingTerms
> {
  return combineCodec(
    getInvestorListingTermsEncoder(),
    getInvestorListingTermsDecoder(),
  );
}
