/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

/** What a trader advertises. One struct, for the same reason `MandateRules` is one. */
export type ListingTerms = {
  minPrincipal: bigint;
  maxPrincipal: bigint;
  wantedMarkets: bigint;
  wantedSplitBps: number;
  note: string;
};

export type ListingTermsArgs = {
  minPrincipal: number | bigint;
  maxPrincipal: number | bigint;
  wantedMarkets: number | bigint;
  wantedSplitBps: number;
  note: string;
};

export function getListingTermsEncoder(): Encoder<ListingTermsArgs> {
  return getStructEncoder([
    ["minPrincipal", getU64Encoder()],
    ["maxPrincipal", getU64Encoder()],
    ["wantedMarkets", getU128Encoder()],
    ["wantedSplitBps", getU16Encoder()],
    ["note", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getListingTermsDecoder(): Decoder<ListingTerms> {
  return getStructDecoder([
    ["minPrincipal", getU64Decoder()],
    ["maxPrincipal", getU64Decoder()],
    ["wantedMarkets", getU128Decoder()],
    ["wantedSplitBps", getU16Decoder()],
    ["note", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getListingTermsCodec(): Codec<ListingTermsArgs, ListingTerms> {
  return combineCodec(getListingTermsEncoder(), getListingTermsDecoder());
}
