/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * The rules an investor sets. Passed as one struct because nine loose arguments at a call
 * site is how a `max_drawdown_bps` ends up in the `max_daily_loss_bps` slot.
 */
export type MandateRules = {
  maxTradeNotional: bigint;
  maxTotalNotional: bigint;
  maxDrawdownBps: number;
  maxDailyLossBps: number;
  maxRiskPerTradeBps: number;
  maxStopDistanceBps: number;
  maxConcurrentPositions: number;
  allowedMarkets: bigint;
  minHoldSlots: bigint;
};

export type MandateRulesArgs = {
  maxTradeNotional: number | bigint;
  maxTotalNotional: number | bigint;
  maxDrawdownBps: number;
  maxDailyLossBps: number;
  maxRiskPerTradeBps: number;
  maxStopDistanceBps: number;
  maxConcurrentPositions: number;
  allowedMarkets: number | bigint;
  minHoldSlots: number | bigint;
};

export function getMandateRulesEncoder(): FixedSizeEncoder<MandateRulesArgs> {
  return getStructEncoder([
    ["maxTradeNotional", getU64Encoder()],
    ["maxTotalNotional", getU64Encoder()],
    ["maxDrawdownBps", getU16Encoder()],
    ["maxDailyLossBps", getU16Encoder()],
    ["maxRiskPerTradeBps", getU16Encoder()],
    ["maxStopDistanceBps", getU16Encoder()],
    ["maxConcurrentPositions", getU8Encoder()],
    ["allowedMarkets", getU128Encoder()],
    ["minHoldSlots", getU64Encoder()],
  ]);
}

export function getMandateRulesDecoder(): FixedSizeDecoder<MandateRules> {
  return getStructDecoder([
    ["maxTradeNotional", getU64Decoder()],
    ["maxTotalNotional", getU64Decoder()],
    ["maxDrawdownBps", getU16Decoder()],
    ["maxDailyLossBps", getU16Decoder()],
    ["maxRiskPerTradeBps", getU16Decoder()],
    ["maxStopDistanceBps", getU16Decoder()],
    ["maxConcurrentPositions", getU8Decoder()],
    ["allowedMarkets", getU128Decoder()],
    ["minHoldSlots", getU64Decoder()],
  ]);
}

export function getMandateRulesCodec(): FixedSizeCodec<
  MandateRulesArgs,
  MandateRules
> {
  return combineCodec(getMandateRulesEncoder(), getMandateRulesDecoder());
}
