/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI128Decoder,
  getI128Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getFeedKindDecoder,
  getFeedKindEncoder,
  getMarketStatusDecoder,
  getMarketStatusEncoder,
  getPriceSourceDecoder,
  getPriceSourceEncoder,
  getQuoteConversionKindDecoder,
  getQuoteConversionKindEncoder,
  type FeedKind,
  type FeedKindArgs,
  type MarketStatus,
  type MarketStatusArgs,
  type PriceSource,
  type PriceSourceArgs,
  type QuoteConversionKind,
  type QuoteConversionKindArgs,
} from ".";

export type Market = {
  marketIndex: number;
  symbol: ReadonlyUint8Array;
  status: MarketStatus;
  feedKind: FeedKind;
  priceSource: PriceSource;
  pythFeedId: ReadonlyUint8Array;
  secondaryFeedId: ReadonlyUint8Array;
  quoteConversionFeed: ReadonlyUint8Array;
  quoteConversionKind: QuoteConversionKind;
  sessionOpenDow: number;
  sessionOpenSeconds: number;
  sessionCloseDow: number;
  sessionCloseSeconds: number;
  weekendMaxLeverage: number;
  weekendOiCapBps: number;
  weekendSpreadBps: number;
  weekendMaxConfBps: number;
  maxLeverage: number;
  imrBps: number;
  mmrBps: number;
  liquidationFeeBps: number;
  maxOiLong: bigint;
  maxOiShort: bigint;
  maxPositionSize: bigint;
  minPositionSize: bigint;
  maxStalenessSeconds: number;
  maxConfBps: number;
  maxDeviationBps: number;
  baseSpreadBps: number;
  confSpreadMultiplierBps: number;
  skewImpactBpsPerUnit: number;
  openFeeRate: bigint;
  closeFeeRate: bigint;
  cumFundingLong: bigint;
  cumFundingShort: bigint;
  cumBorrowIndex: bigint;
  lastFundingUpdateTs: bigint;
  fundingRateCapPerHour: bigint;
  carryRatePerHour: bigint;
  oiLong: bigint;
  oiShort: bigint;
  baseOiLong: bigint;
  baseOiShort: bigint;
  lastPrice: bigint;
  emaPrice: bigint;
  lastPriceUpdateTs: bigint;
  totalFeesCollected: bigint;
  bump: number;
  minHoldSlots: bigint;
  openPositionCount: bigint;
  fundingBalance: bigint;
  fundingRateK: bigint;
  rateBaseAnnual: bigint;
  rateQuoteAnnual: bigint;
  lastSessionCrankTs: bigint;
  statusChangedAt: bigint;
  pendingAdlDebt: bigint;
  liquidationMaxConfBps: number;
  reserved: ReadonlyUint8Array;
};

export type MarketArgs = {
  marketIndex: number;
  symbol: ReadonlyUint8Array;
  status: MarketStatusArgs;
  feedKind: FeedKindArgs;
  priceSource: PriceSourceArgs;
  pythFeedId: ReadonlyUint8Array;
  secondaryFeedId: ReadonlyUint8Array;
  quoteConversionFeed: ReadonlyUint8Array;
  quoteConversionKind: QuoteConversionKindArgs;
  sessionOpenDow: number;
  sessionOpenSeconds: number;
  sessionCloseDow: number;
  sessionCloseSeconds: number;
  weekendMaxLeverage: number;
  weekendOiCapBps: number;
  weekendSpreadBps: number;
  weekendMaxConfBps: number;
  maxLeverage: number;
  imrBps: number;
  mmrBps: number;
  liquidationFeeBps: number;
  maxOiLong: number | bigint;
  maxOiShort: number | bigint;
  maxPositionSize: number | bigint;
  minPositionSize: number | bigint;
  maxStalenessSeconds: number;
  maxConfBps: number;
  maxDeviationBps: number;
  baseSpreadBps: number;
  confSpreadMultiplierBps: number;
  skewImpactBpsPerUnit: number;
  openFeeRate: number | bigint;
  closeFeeRate: number | bigint;
  cumFundingLong: number | bigint;
  cumFundingShort: number | bigint;
  cumBorrowIndex: number | bigint;
  lastFundingUpdateTs: number | bigint;
  fundingRateCapPerHour: number | bigint;
  carryRatePerHour: number | bigint;
  oiLong: number | bigint;
  oiShort: number | bigint;
  baseOiLong: number | bigint;
  baseOiShort: number | bigint;
  lastPrice: number | bigint;
  emaPrice: number | bigint;
  lastPriceUpdateTs: number | bigint;
  totalFeesCollected: number | bigint;
  bump: number;
  minHoldSlots: number | bigint;
  openPositionCount: number | bigint;
  fundingBalance: number | bigint;
  fundingRateK: number | bigint;
  rateBaseAnnual: number | bigint;
  rateQuoteAnnual: number | bigint;
  lastSessionCrankTs: number | bigint;
  statusChangedAt: number | bigint;
  pendingAdlDebt: number | bigint;
  liquidationMaxConfBps: number;
  reserved: ReadonlyUint8Array;
};

export function getMarketEncoder(): Encoder<MarketArgs> {
  return getStructEncoder([
    ["marketIndex", getU16Encoder()],
    ["symbol", fixEncoderSize(getBytesEncoder(), 16)],
    ["status", getMarketStatusEncoder()],
    ["feedKind", getFeedKindEncoder()],
    ["priceSource", getPriceSourceEncoder()],
    ["pythFeedId", fixEncoderSize(getBytesEncoder(), 32)],
    ["secondaryFeedId", fixEncoderSize(getBytesEncoder(), 32)],
    ["quoteConversionFeed", fixEncoderSize(getBytesEncoder(), 32)],
    ["quoteConversionKind", getQuoteConversionKindEncoder()],
    ["sessionOpenDow", getU8Encoder()],
    ["sessionOpenSeconds", getU32Encoder()],
    ["sessionCloseDow", getU8Encoder()],
    ["sessionCloseSeconds", getU32Encoder()],
    ["weekendMaxLeverage", getU16Encoder()],
    ["weekendOiCapBps", getU16Encoder()],
    ["weekendSpreadBps", getU16Encoder()],
    ["weekendMaxConfBps", getU16Encoder()],
    ["maxLeverage", getU16Encoder()],
    ["imrBps", getU16Encoder()],
    ["mmrBps", getU16Encoder()],
    ["liquidationFeeBps", getU16Encoder()],
    ["maxOiLong", getU64Encoder()],
    ["maxOiShort", getU64Encoder()],
    ["maxPositionSize", getU64Encoder()],
    ["minPositionSize", getU64Encoder()],
    ["maxStalenessSeconds", getU32Encoder()],
    ["maxConfBps", getU16Encoder()],
    ["maxDeviationBps", getU16Encoder()],
    ["baseSpreadBps", getU16Encoder()],
    ["confSpreadMultiplierBps", getU16Encoder()],
    ["skewImpactBpsPerUnit", getU32Encoder()],
    ["openFeeRate", getU64Encoder()],
    ["closeFeeRate", getU64Encoder()],
    ["cumFundingLong", getI128Encoder()],
    ["cumFundingShort", getI128Encoder()],
    ["cumBorrowIndex", getU128Encoder()],
    ["lastFundingUpdateTs", getI64Encoder()],
    ["fundingRateCapPerHour", getI64Encoder()],
    ["carryRatePerHour", getI64Encoder()],
    ["oiLong", getU64Encoder()],
    ["oiShort", getU64Encoder()],
    ["baseOiLong", getI128Encoder()],
    ["baseOiShort", getI128Encoder()],
    ["lastPrice", getI64Encoder()],
    ["emaPrice", getI64Encoder()],
    ["lastPriceUpdateTs", getI64Encoder()],
    ["totalFeesCollected", getU64Encoder()],
    ["bump", getU8Encoder()],
    ["minHoldSlots", getU64Encoder()],
    ["openPositionCount", getU64Encoder()],
    ["fundingBalance", getU64Encoder()],
    ["fundingRateK", getU64Encoder()],
    ["rateBaseAnnual", getI64Encoder()],
    ["rateQuoteAnnual", getI64Encoder()],
    ["lastSessionCrankTs", getI64Encoder()],
    ["statusChangedAt", getI64Encoder()],
    ["pendingAdlDebt", getU64Encoder()],
    ["liquidationMaxConfBps", getU16Encoder()],
    ["reserved", fixEncoderSize(getBytesEncoder(), 62)],
  ]);
}

export function getMarketDecoder(): Decoder<Market> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["symbol", fixDecoderSize(getBytesDecoder(), 16)],
    ["status", getMarketStatusDecoder()],
    ["feedKind", getFeedKindDecoder()],
    ["priceSource", getPriceSourceDecoder()],
    ["pythFeedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["secondaryFeedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["quoteConversionFeed", fixDecoderSize(getBytesDecoder(), 32)],
    ["quoteConversionKind", getQuoteConversionKindDecoder()],
    ["sessionOpenDow", getU8Decoder()],
    ["sessionOpenSeconds", getU32Decoder()],
    ["sessionCloseDow", getU8Decoder()],
    ["sessionCloseSeconds", getU32Decoder()],
    ["weekendMaxLeverage", getU16Decoder()],
    ["weekendOiCapBps", getU16Decoder()],
    ["weekendSpreadBps", getU16Decoder()],
    ["weekendMaxConfBps", getU16Decoder()],
    ["maxLeverage", getU16Decoder()],
    ["imrBps", getU16Decoder()],
    ["mmrBps", getU16Decoder()],
    ["liquidationFeeBps", getU16Decoder()],
    ["maxOiLong", getU64Decoder()],
    ["maxOiShort", getU64Decoder()],
    ["maxPositionSize", getU64Decoder()],
    ["minPositionSize", getU64Decoder()],
    ["maxStalenessSeconds", getU32Decoder()],
    ["maxConfBps", getU16Decoder()],
    ["maxDeviationBps", getU16Decoder()],
    ["baseSpreadBps", getU16Decoder()],
    ["confSpreadMultiplierBps", getU16Decoder()],
    ["skewImpactBpsPerUnit", getU32Decoder()],
    ["openFeeRate", getU64Decoder()],
    ["closeFeeRate", getU64Decoder()],
    ["cumFundingLong", getI128Decoder()],
    ["cumFundingShort", getI128Decoder()],
    ["cumBorrowIndex", getU128Decoder()],
    ["lastFundingUpdateTs", getI64Decoder()],
    ["fundingRateCapPerHour", getI64Decoder()],
    ["carryRatePerHour", getI64Decoder()],
    ["oiLong", getU64Decoder()],
    ["oiShort", getU64Decoder()],
    ["baseOiLong", getI128Decoder()],
    ["baseOiShort", getI128Decoder()],
    ["lastPrice", getI64Decoder()],
    ["emaPrice", getI64Decoder()],
    ["lastPriceUpdateTs", getI64Decoder()],
    ["totalFeesCollected", getU64Decoder()],
    ["bump", getU8Decoder()],
    ["minHoldSlots", getU64Decoder()],
    ["openPositionCount", getU64Decoder()],
    ["fundingBalance", getU64Decoder()],
    ["fundingRateK", getU64Decoder()],
    ["rateBaseAnnual", getI64Decoder()],
    ["rateQuoteAnnual", getI64Decoder()],
    ["lastSessionCrankTs", getI64Decoder()],
    ["statusChangedAt", getI64Decoder()],
    ["pendingAdlDebt", getU64Decoder()],
    ["liquidationMaxConfBps", getU16Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 62)],
  ]);
}

export function getMarketCodec(): Codec<MarketArgs, Market> {
  return combineCodec(getMarketEncoder(), getMarketDecoder());
}
