/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PositionSlot = {
  open: boolean;
  marketIndex: number;
  nonce: number;
  notional: bigint;
};

export type PositionSlotArgs = {
  open: boolean;
  marketIndex: number;
  nonce: number;
  notional: number | bigint;
};

export function getPositionSlotEncoder(): FixedSizeEncoder<PositionSlotArgs> {
  return getStructEncoder([
    ["open", getBooleanEncoder()],
    ["marketIndex", getU16Encoder()],
    ["nonce", getU8Encoder()],
    ["notional", getU64Encoder()],
  ]);
}

export function getPositionSlotDecoder(): FixedSizeDecoder<PositionSlot> {
  return getStructDecoder([
    ["open", getBooleanDecoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["notional", getU64Decoder()],
  ]);
}

export function getPositionSlotCodec(): FixedSizeCodec<
  PositionSlotArgs,
  PositionSlot
> {
  return combineCodec(getPositionSlotEncoder(), getPositionSlotDecoder());
}
