/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI128Decoder,
  getI128Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getDirectionDecoder,
  getDirectionEncoder,
  type Direction,
  type DirectionArgs,
} from ".";

export type Position = {
  userAccount: Address;
  marketIndex: number;
  nonce: number;
  direction: Direction;
  sizeBase: bigint;
  entryPrice: bigint;
  collateral: bigint;
  entryNotional: bigint;
  cumFundingEntry: bigint;
  cumBorrowEntry: bigint;
  realizedFunding: bigint;
  openedAt: bigint;
  openedAtSlot: bigint;
  lastUpdatedAt: bigint;
  openFeePaid: bigint;
  referrer: Address;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export type PositionArgs = {
  userAccount: Address;
  marketIndex: number;
  nonce: number;
  direction: DirectionArgs;
  sizeBase: number | bigint;
  entryPrice: number | bigint;
  collateral: number | bigint;
  entryNotional: number | bigint;
  cumFundingEntry: number | bigint;
  cumBorrowEntry: number | bigint;
  realizedFunding: number | bigint;
  openedAt: number | bigint;
  openedAtSlot: number | bigint;
  lastUpdatedAt: number | bigint;
  openFeePaid: number | bigint;
  referrer: Address;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export function getPositionEncoder(): FixedSizeEncoder<PositionArgs> {
  return getStructEncoder([
    ["userAccount", getAddressEncoder()],
    ["marketIndex", getU16Encoder()],
    ["nonce", getU8Encoder()],
    ["direction", getDirectionEncoder()],
    ["sizeBase", getU64Encoder()],
    ["entryPrice", getI64Encoder()],
    ["collateral", getU64Encoder()],
    ["entryNotional", getU64Encoder()],
    ["cumFundingEntry", getI128Encoder()],
    ["cumBorrowEntry", getU128Encoder()],
    ["realizedFunding", getI64Encoder()],
    ["openedAt", getI64Encoder()],
    ["openedAtSlot", getU64Encoder()],
    ["lastUpdatedAt", getI64Encoder()],
    ["openFeePaid", getU64Encoder()],
    ["referrer", getAddressEncoder()],
    ["bump", getU8Encoder()],
    ["reserved", fixEncoderSize(getBytesEncoder(), 64)],
  ]);
}

export function getPositionDecoder(): FixedSizeDecoder<Position> {
  return getStructDecoder([
    ["userAccount", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["direction", getDirectionDecoder()],
    ["sizeBase", getU64Decoder()],
    ["entryPrice", getI64Decoder()],
    ["collateral", getU64Decoder()],
    ["entryNotional", getU64Decoder()],
    ["cumFundingEntry", getI128Decoder()],
    ["cumBorrowEntry", getU128Decoder()],
    ["realizedFunding", getI64Decoder()],
    ["openedAt", getI64Decoder()],
    ["openedAtSlot", getU64Decoder()],
    ["lastUpdatedAt", getI64Decoder()],
    ["openFeePaid", getU64Decoder()],
    ["referrer", getAddressDecoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 64)],
  ]);
}

export function getPositionCodec(): FixedSizeCodec<PositionArgs, Position> {
  return combineCodec(getPositionEncoder(), getPositionDecoder());
}
