/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * One open position, as NOXFUNDS booked it.
 *
 * # Why the mandate tracks positions individually
 *
 * A counter and a running notional total were not enough, and three bugs proved it:
 *
 * - **A stop-out never came back.** A stop fires through `solfx-core`'s own
 * `execute_trigger_order`, which never enters NOXFUNDS, so the counter stayed high forever.
 * Settlement needs it at zero and the equity crank needs a triple per counted position that
 * no longer exists — a stopped-out mandate could never settle or be observed again.
 * - **The book drifted.** Opens booked notional at the oracle price; closes unbooked core's
 * `entry_notional`, which is at the fill price after spread. A short left a residue on every
 * round trip until the book refused trades it had room for.
 * - **The crank could be fooled.** It checked only the *count* of triples, so the same
 * profitable position supplied twice inflated equity and hid a breach.
 *
 * A slot records exactly what was booked and where, so each close releases the exact figure it
 * added, a stop-out can be reconciled against the chain, and the crank can demand each open
 * position once.
 */
export type PositionSlot = {
  open: boolean;
  marketIndex: number;
  nonce: number;
  /** Notional as NOXFUNDS booked it at open, in USDC. Released at this exact figure. */
  notional: bigint;
};

export type PositionSlotArgs = {
  open: boolean;
  marketIndex: number;
  nonce: number;
  /** Notional as NOXFUNDS booked it at open, in USDC. Released at this exact figure. */
  notional: number | bigint;
};

export function getPositionSlotEncoder(): FixedSizeEncoder<PositionSlotArgs> {
  return getStructEncoder([
    ["open", getBooleanEncoder()],
    ["marketIndex", getU16Encoder()],
    ["nonce", getU8Encoder()],
    ["notional", getU64Encoder()],
  ]);
}

export function getPositionSlotDecoder(): FixedSizeDecoder<PositionSlot> {
  return getStructDecoder([
    ["open", getBooleanDecoder()],
    ["marketIndex", getU16Decoder()],
    ["nonce", getU8Decoder()],
    ["notional", getU64Decoder()],
  ]);
}

export function getPositionSlotCodec(): FixedSizeCodec<
  PositionSlotArgs,
  PositionSlot
> {
  return combineCodec(getPositionSlotEncoder(), getPositionSlotDecoder());
}
