/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";
import {
  getPriceFeedMessageDecoder,
  getPriceFeedMessageEncoder,
  getVerificationLevelDecoder,
  getVerificationLevelEncoder,
  type PriceFeedMessage,
  type PriceFeedMessageArgs,
  type VerificationLevel,
  type VerificationLevelArgs,
} from ".";

export type PriceUpdateV2 = {
  writeAuthority: Address;
  verificationLevel: VerificationLevel;
  priceMessage: PriceFeedMessage;
  postedSlot: bigint;
};

export type PriceUpdateV2Args = {
  writeAuthority: Address;
  verificationLevel: VerificationLevelArgs;
  priceMessage: PriceFeedMessageArgs;
  postedSlot: number | bigint;
};

export function getPriceUpdateV2Encoder(): Encoder<PriceUpdateV2Args> {
  return getStructEncoder([
    ["writeAuthority", getAddressEncoder()],
    ["verificationLevel", getVerificationLevelEncoder()],
    ["priceMessage", getPriceFeedMessageEncoder()],
    ["postedSlot", getU64Encoder()],
  ]);
}

export function getPriceUpdateV2Decoder(): Decoder<PriceUpdateV2> {
  return getStructDecoder([
    ["writeAuthority", getAddressDecoder()],
    ["verificationLevel", getVerificationLevelDecoder()],
    ["priceMessage", getPriceFeedMessageDecoder()],
    ["postedSlot", getU64Decoder()],
  ]);
}

export function getPriceUpdateV2Codec(): Codec<
  PriceUpdateV2Args,
  PriceUpdateV2
> {
  return combineCodec(getPriceUpdateV2Encoder(), getPriceUpdateV2Decoder());
}
