/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type PriceFeedMessage = {
  feedId: ReadonlyUint8Array;
  price: bigint;
  conf: bigint;
  exponent: number;
  publishTime: bigint;
  prevPublishTime: bigint;
  emaPrice: bigint;
  emaConf: bigint;
};

export type PriceFeedMessageArgs = {
  feedId: ReadonlyUint8Array;
  price: number | bigint;
  conf: number | bigint;
  exponent: number;
  publishTime: number | bigint;
  prevPublishTime: number | bigint;
  emaPrice: number | bigint;
  emaConf: number | bigint;
};

export function getPriceFeedMessageEncoder(): FixedSizeEncoder<PriceFeedMessageArgs> {
  return getStructEncoder([
    ["feedId", fixEncoderSize(getBytesEncoder(), 32)],
    ["price", getI64Encoder()],
    ["conf", getU64Encoder()],
    ["exponent", getI32Encoder()],
    ["publishTime", getI64Encoder()],
    ["prevPublishTime", getI64Encoder()],
    ["emaPrice", getI64Encoder()],
    ["emaConf", getU64Encoder()],
  ]);
}

export function getPriceFeedMessageDecoder(): FixedSizeDecoder<PriceFeedMessage> {
  return getStructDecoder([
    ["feedId", fixDecoderSize(getBytesDecoder(), 32)],
    ["price", getI64Decoder()],
    ["conf", getU64Decoder()],
    ["exponent", getI32Decoder()],
    ["publishTime", getI64Decoder()],
    ["prevPublishTime", getI64Decoder()],
    ["emaPrice", getI64Decoder()],
    ["emaConf", getU64Decoder()],
  ]);
}

export function getPriceFeedMessageCodec(): FixedSizeCodec<
  PriceFeedMessageArgs,
  PriceFeedMessage
> {
  return combineCodec(
    getPriceFeedMessageEncoder(),
    getPriceFeedMessageDecoder(),
  );
}
