/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getTriggerKindDecoder,
  getTriggerKindEncoder,
  type TriggerKind,
  type TriggerKindArgs,
} from ".";

/**
 * A resting take-profit or stop-loss. PDA at `["order", position, order_id]`.
 *
 * # Why this is on chain rather than in the keeper
 *
 * A stop-loss held off-chain is a promise from whoever runs the bot. On chain it is an
 * account with rules: **anyone** can execute it, the conditions are public, and the trader
 * can verify the order exists without trusting us. That is the same argument as the IB
 * ledger (§ 8.5) applied to risk management — and it is why this arrived with its executor
 * in Phase 7 rather than alone in Phase 4, since an order nothing fires is worse than no
 * order at all.
 *
 * # What it does not promise
 *
 * **A trigger is not a guaranteed fill price.** It fires when the *oracle* crosses the
 * trigger, and then fills at the execution price — which includes the adverse spread, and in
 * a gap may be far past the trigger. This is exactly how a stop works at any broker, and the
 * UI must say so, because the alternative is a trader who believes they were promised
 * something and discovers otherwise during the one event that matters.
 */
export type TriggerOrder = {
  position: Address;
  userAccount: Address;
  /** The wallet that placed it — also the only one that can cancel it. */
  authority: Address;
  marketIndex: number;
  /** Distinguishes several orders on one position: a TP and an SL are the usual pair. */
  orderId: number;
  kind: TriggerKind;
  /** At `PRICE_PRECISION`. Compared against the oracle price, not the fill price. */
  triggerPrice: bigint;
  /** Base units to close. May be less than the position, for scaling out. */
  sizeBase: bigint;
  createdAt: bigint;
  bump: number;
  /**
   * The `opened_at_slot` of the position this order was placed against.
   *
   * # Why an order needs to know which position it belongs to
   *
   * A position's address is `["position", user_account, market_index, nonce]`, and a client
   * picks the lowest free nonce — so closing a position and opening another on the same
   * market lands on the **same address**. `close_position` does not cancel outstanding
   * orders, and without this field nothing distinguishes one occupant of that address from
   * the next: a stop left behind by the closed position silently re-arms itself against
   * whatever opens there, carrying the old direction's meaning.
   *
   * Measured on devnet 2026-09-13. A take-profit at 2500 left by a closed ETH **short** was
   * inherited by a fresh ETH **long** entered at 2509.61; a take-profit on a long fires when
   * the price rises past it, so it was already met the instant the position existed and the
   * keeper closed it nineteen seconds after it opened. Every layer behaved correctly — the
   * account model let two logical objects share one identity, which `.claude/rules/solana.md`
   * § 3 already calls a bug rather than a collision to handle later.
   *
   * The slot rather than the timestamp because it is strictly monotonic: two positions
   * cannot occupy one address in the same slot, since the first must be closed and § 6.6's
   * minimum-hold rule forbids reopening that fast. `Position` already stores it for exactly
   * that check.
   *
   * # Why this costs no migration
   *
   * The eight bytes come out of the former `[u8; 32]` reserve, so `InitSpace` is unchanged
   * at 32 and every account written by the previous program still passes Anchor's
   * minimum-length check. Those accounts read back as slot `0`, which matches no real
   * position, so they refuse to execute — **fail-closed on purpose**. Grandfathering in the
   * orders that caused the bug is the one outcome worth ruling out, and their rent is still
   * reclaimable through `cancel_trigger_order`, which does not consult this field.
   */
  positionOpenedAtSlot: bigint;
  reserved: ReadonlyUint8Array;
};

export type TriggerOrderArgs = {
  position: Address;
  userAccount: Address;
  /** The wallet that placed it — also the only one that can cancel it. */
  authority: Address;
  marketIndex: number;
  /** Distinguishes several orders on one position: a TP and an SL are the usual pair. */
  orderId: number;
  kind: TriggerKindArgs;
  /** At `PRICE_PRECISION`. Compared against the oracle price, not the fill price. */
  triggerPrice: number | bigint;
  /** Base units to close. May be less than the position, for scaling out. */
  sizeBase: number | bigint;
  createdAt: number | bigint;
  bump: number;
  /**
   * The `opened_at_slot` of the position this order was placed against.
   *
   * # Why an order needs to know which position it belongs to
   *
   * A position's address is `["position", user_account, market_index, nonce]`, and a client
   * picks the lowest free nonce — so closing a position and opening another on the same
   * market lands on the **same address**. `close_position` does not cancel outstanding
   * orders, and without this field nothing distinguishes one occupant of that address from
   * the next: a stop left behind by the closed position silently re-arms itself against
   * whatever opens there, carrying the old direction's meaning.
   *
   * Measured on devnet 2026-09-13. A take-profit at 2500 left by a closed ETH **short** was
   * inherited by a fresh ETH **long** entered at 2509.61; a take-profit on a long fires when
   * the price rises past it, so it was already met the instant the position existed and the
   * keeper closed it nineteen seconds after it opened. Every layer behaved correctly — the
   * account model let two logical objects share one identity, which `.claude/rules/solana.md`
   * § 3 already calls a bug rather than a collision to handle later.
   *
   * The slot rather than the timestamp because it is strictly monotonic: two positions
   * cannot occupy one address in the same slot, since the first must be closed and § 6.6's
   * minimum-hold rule forbids reopening that fast. `Position` already stores it for exactly
   * that check.
   *
   * # Why this costs no migration
   *
   * The eight bytes come out of the former `[u8; 32]` reserve, so `InitSpace` is unchanged
   * at 32 and every account written by the previous program still passes Anchor's
   * minimum-length check. Those accounts read back as slot `0`, which matches no real
   * position, so they refuse to execute — **fail-closed on purpose**. Grandfathering in the
   * orders that caused the bug is the one outcome worth ruling out, and their rent is still
   * reclaimable through `cancel_trigger_order`, which does not consult this field.
   */
  positionOpenedAtSlot: number | bigint;
  reserved: ReadonlyUint8Array;
};

export function getTriggerOrderEncoder(): FixedSizeEncoder<TriggerOrderArgs> {
  return getStructEncoder([
    ["position", getAddressEncoder()],
    ["userAccount", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["marketIndex", getU16Encoder()],
    ["orderId", getU8Encoder()],
    ["kind", getTriggerKindEncoder()],
    ["triggerPrice", getI64Encoder()],
    ["sizeBase", getU64Encoder()],
    ["createdAt", getI64Encoder()],
    ["bump", getU8Encoder()],
    ["positionOpenedAtSlot", getU64Encoder()],
    ["reserved", fixEncoderSize(getBytesEncoder(), 24)],
  ]);
}

export function getTriggerOrderDecoder(): FixedSizeDecoder<TriggerOrder> {
  return getStructDecoder([
    ["position", getAddressDecoder()],
    ["userAccount", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["marketIndex", getU16Decoder()],
    ["orderId", getU8Decoder()],
    ["kind", getTriggerKindDecoder()],
    ["triggerPrice", getI64Decoder()],
    ["sizeBase", getU64Decoder()],
    ["createdAt", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["positionOpenedAtSlot", getU64Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 24)],
  ]);
}

export function getTriggerOrderCodec(): FixedSizeCodec<
  TriggerOrderArgs,
  TriggerOrder
> {
  return combineCodec(getTriggerOrderEncoder(), getTriggerOrderDecoder());
}
