/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type UserAccount = {
  authority: Address;
  freeCollateral: bigint;
  openPositions: number;
  referrer: Address;
  thirtyDayVolume: bigint;
  volumeWindowStartTs: bigint;
  totalDeposits: bigint;
  totalWithdrawals: bigint;
  createdAt: bigint;
  referralFeesGenerated: bigint;
  lifetimeVolume: bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export type UserAccountArgs = {
  authority: Address;
  freeCollateral: number | bigint;
  openPositions: number;
  referrer: Address;
  thirtyDayVolume: number | bigint;
  volumeWindowStartTs: number | bigint;
  totalDeposits: number | bigint;
  totalWithdrawals: number | bigint;
  createdAt: number | bigint;
  referralFeesGenerated: number | bigint;
  lifetimeVolume: number | bigint;
  bump: number;
  reserved: ReadonlyUint8Array;
};

export function getUserAccountEncoder(): FixedSizeEncoder<UserAccountArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["freeCollateral", getU64Encoder()],
    ["openPositions", getU16Encoder()],
    ["referrer", getAddressEncoder()],
    ["thirtyDayVolume", getU64Encoder()],
    ["volumeWindowStartTs", getI64Encoder()],
    ["totalDeposits", getU64Encoder()],
    ["totalWithdrawals", getU64Encoder()],
    ["createdAt", getI64Encoder()],
    ["referralFeesGenerated", getU64Encoder()],
    ["lifetimeVolume", getU64Encoder()],
    ["bump", getU8Encoder()],
    ["reserved", fixEncoderSize(getBytesEncoder(), 48)],
  ]);
}

export function getUserAccountDecoder(): FixedSizeDecoder<UserAccount> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["freeCollateral", getU64Decoder()],
    ["openPositions", getU16Decoder()],
    ["referrer", getAddressDecoder()],
    ["thirtyDayVolume", getU64Decoder()],
    ["volumeWindowStartTs", getI64Decoder()],
    ["totalDeposits", getU64Decoder()],
    ["totalWithdrawals", getU64Decoder()],
    ["createdAt", getI64Decoder()],
    ["referralFeesGenerated", getU64Decoder()],
    ["lifetimeVolume", getU64Decoder()],
    ["bump", getU8Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 48)],
  ]);
}

export function getUserAccountCodec(): FixedSizeCodec<
  UserAccountArgs,
  UserAccount
> {
  return combineCodec(getUserAccountEncoder(), getUserAccountDecoder());
}
