/**
 * Writes `src/lib/globe-dots.ts`: which points of a 280 × 140 latitude/longitude lattice are on
 * land, for the landing page's dotted globe.
 *
 *   cd app
 *   node scripts/globe-dots.mts      # Node 22.18+ runs TypeScript directly
 *
 * Computed here, once, rather than in the browser. Testing 39,200 points against the Natural
 * Earth land polygons takes about three seconds on the VPS, which is a frozen page if a visitor
 * has to do it, and the answer never changes. The output is one bit per point, so the browser
 * decodes about 5 KB instead of measuring anything.
 *
 * The polygons are `world-atlas`'s `land-110m`, the same file the globe draws its outlines from,
 * so dots and outlines cannot disagree. Its winding follows d3's spherical convention, which is
 * why containment uses `geoContains` and not a flat point-in-polygon test: Antarctica's ring
 * encloses the pole without ever reaching it, and only the spherical test reads that right.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { geoBounds, geoContains } from "d3-geo";
import { feature } from "topojson-client";
import type { Polygon } from "geojson";
import type { GeometryCollection, Topology } from "topojson-specification";

const COLS = 280;
const ROWS = 140;
/** 9/7 of a degree: the closest even divisor of 360 to the original design's 1.28° spacing. */
const STEP = 360 / COLS;

const topology = JSON.parse(
  readFileSync(
    new URL(import.meta.resolve("world-atlas/land-110m.json")),
    "utf8"
  )
) as Topology<{ land: GeometryCollection }>;
const land = feature(topology, topology.objects.land);

const polygons: {
  shape: Polygon;
  box: [[number, number], [number, number]];
}[] = land.features.flatMap((f) => {
  const g = f.geometry;
  const rings =
    g.type === "MultiPolygon"
      ? g.coordinates
      : g.type === "Polygon"
        ? [g.coordinates]
        : [];
  return rings.map((coordinates) => {
    const shape: Polygon = { type: "Polygon", coordinates };
    return { shape, box: geoBounds(shape) };
  });
});

/** A box crossing the antimeridian has west > east. */
function inBox(
  [[w, s], [e, n]]: [[number, number], [number, number]],
  lng: number,
  lat: number
) {
  if (lat < s || lat > n) return false;
  return w <= e ? lng >= w && lng <= e : lng >= w || lng <= e;
}

const bits = new Uint8Array(Math.ceil((COLS * ROWS) / 8));
let count = 0;
for (let row = 0; row < ROWS; row++) {
  const lat = -90 + (row + 0.5) * STEP;
  for (let col = 0; col < COLS; col++) {
    const lng = -180 + (col + 0.5) * STEP;
    const onLand = polygons.some(
      ({ shape, box }) => inBox(box, lng, lat) && geoContains(shape, [lng, lat])
    );
    if (onLand) {
      const i = row * COLS + col;
      bits[i >> 3] |= 1 << (i & 7);
      count++;
    }
  }
}

const out = new URL("../src/lib/globe-dots.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/globe-dots.mts from world-atlas land-110m. Do not edit; re-run it.

/** Lattice size: columns of longitude and rows of latitude, every ${STEP.toFixed(4)} degrees. */
export const LAND_COLS = ${COLS};
export const LAND_ROWS = ${ROWS};

/** How many lattice points are on land. */
export const LAND_DOT_COUNT = ${count};

/**
 * One bit per lattice point, row by row from the south-west corner, least significant bit first,
 * base64. A set bit is land.
 */
export const LAND_BITS =
  "${Buffer.from(bits).toString("base64")}";
`
);
console.log(`${count} of ${COLS * ROWS} points on land; wrote ${out.pathname}`);
